<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blogs.proto

namespace Lexmodo\V1\Blog;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.blog.COMMENTABLE_TYPE</code>
 */
class COMMENTABLE_TYPE
{
    /**
     * Generated from protobuf enum <code>disabled = 0;</code>
     */
    const disabled = 0;
    /**
     * Generated from protobuf enum <code>approval = 1;</code>
     */
    const approval = 1;
    /**
     * Generated from protobuf enum <code>publish = 2;</code>
     */
    const publish = 2;

    private static $valueToName = [
        self::disabled => 'disabled',
        self::approval => 'approval',
        self::publish => 'publish',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

