<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blogs.proto

namespace Lexmodo\V1\Blog;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.blog.PostSearch</code>
 */
class PostSearch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string rule_query = 1;</code>
     */
    protected $rule_query = '';
    /**
     * Generated from protobuf field <code>string pit = 2;</code>
     */
    protected $pit = '';
    /**
     * Generated from protobuf field <code>uint64 display_result = 3;</code>
     */
    protected $display_result = 0;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.blog.RuleSortBy sort_by = 4;</code>
     */
    private $sort_by;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $rule_query
     *     @type string $pit
     *     @type int|string $display_result
     *     @type \Lexmodo\V1\Blog\RuleSortBy[]|\Google\Protobuf\Internal\RepeatedField $sort_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blogs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string rule_query = 1;</code>
     * @return string
     */
    public function getRuleQuery()
    {
        return $this->rule_query;
    }

    /**
     * Generated from protobuf field <code>string rule_query = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->rule_query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pit = 2;</code>
     * @return string
     */
    public function getPit()
    {
        return $this->pit;
    }

    /**
     * Generated from protobuf field <code>string pit = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPit($var)
    {
        GPBUtil::checkString($var, True);
        $this->pit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 display_result = 3;</code>
     * @return int|string
     */
    public function getDisplayResult()
    {
        return $this->display_result;
    }

    /**
     * Generated from protobuf field <code>uint64 display_result = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDisplayResult($var)
    {
        GPBUtil::checkUint64($var);
        $this->display_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.blog.RuleSortBy sort_by = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSortBy()
    {
        return $this->sort_by;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.blog.RuleSortBy sort_by = 4;</code>
     * @param \Lexmodo\V1\Blog\RuleSortBy[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSortBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Blog\RuleSortBy::class);
        $this->sort_by = $arr;

        return $this;
    }

}

