<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blogs.proto

namespace Lexmodo\V1\Blog;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.blog.SearchFieldPosts</code>
 */
class SearchFieldPosts extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blogs::initOnce();
        parent::__construct($data);
    }

}

