// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package blog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlogClient is the client API for Blog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogClient interface {
	AddComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ApproveComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	AddBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	UpdateBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	BlogListing(ctx context.Context, in *BlogSearch, opts ...grpc.CallOption) (*ResultResponse, error)
	AddPosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetPost(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	PostsListing(ctx context.Context, in *PostSearch, opts ...grpc.CallOption) (*ResultResponse, error)
	UpdatePosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeletePosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type blogClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogClient(cc grpc.ClientConnInterface) BlogClient {
	return &blogClient{cc}
}

func (c *blogClient) AddComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/AddComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) ApproveComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/ApproveComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) DeleteComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetComment(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/GetComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) AddBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/AddBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) UpdateBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/UpdateBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) DeleteBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/DeleteBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/GetBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) BlogListing(ctx context.Context, in *BlogSearch, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/BlogListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) AddPosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/AddPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetPost(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) PostsListing(ctx context.Context, in *PostSearch, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/PostsListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) UpdatePosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/UpdatePosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) DeletePosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.blog.Blog/DeletePosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServer is the server API for Blog service.
// All implementations must embed UnimplementedBlogServer
// for forward compatibility
type BlogServer interface {
	AddComment(context.Context, *CommentsRequest) (*ResultResponse, error)
	ApproveComment(context.Context, *CommentsRequest) (*ResultResponse, error)
	DeleteComment(context.Context, *CommentsRequest) (*ResultResponse, error)
	GetComment(context.Context, *CommentsRequest) (*ResultResponse, error)
	AddBlog(context.Context, *BlogRequest) (*ResultResponse, error)
	UpdateBlog(context.Context, *BlogRequest) (*ResultResponse, error)
	DeleteBlog(context.Context, *BlogRequest) (*ResultResponse, error)
	GetBlog(context.Context, *BlogRequest) (*ResultResponse, error)
	BlogListing(context.Context, *BlogSearch) (*ResultResponse, error)
	AddPosts(context.Context, *PostsRequest) (*ResultResponse, error)
	GetPost(context.Context, *PostsRequest) (*ResultResponse, error)
	PostsListing(context.Context, *PostSearch) (*ResultResponse, error)
	UpdatePosts(context.Context, *PostsRequest) (*ResultResponse, error)
	DeletePosts(context.Context, *PostsRequest) (*ResultResponse, error)
	mustEmbedUnimplementedBlogServer()
}

// UnimplementedBlogServer must be embedded to have forward compatible implementations.
type UnimplementedBlogServer struct {
}

func (UnimplementedBlogServer) AddComment(context.Context, *CommentsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedBlogServer) ApproveComment(context.Context, *CommentsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveComment not implemented")
}
func (UnimplementedBlogServer) DeleteComment(context.Context, *CommentsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedBlogServer) GetComment(context.Context, *CommentsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedBlogServer) AddBlog(context.Context, *BlogRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlog not implemented")
}
func (UnimplementedBlogServer) UpdateBlog(context.Context, *BlogRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBlog not implemented")
}
func (UnimplementedBlogServer) DeleteBlog(context.Context, *BlogRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBlog not implemented")
}
func (UnimplementedBlogServer) GetBlog(context.Context, *BlogRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlog not implemented")
}
func (UnimplementedBlogServer) BlogListing(context.Context, *BlogSearch) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlogListing not implemented")
}
func (UnimplementedBlogServer) AddPosts(context.Context, *PostsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPosts not implemented")
}
func (UnimplementedBlogServer) GetPost(context.Context, *PostsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedBlogServer) PostsListing(context.Context, *PostSearch) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostsListing not implemented")
}
func (UnimplementedBlogServer) UpdatePosts(context.Context, *PostsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosts not implemented")
}
func (UnimplementedBlogServer) DeletePosts(context.Context, *PostsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePosts not implemented")
}
func (UnimplementedBlogServer) mustEmbedUnimplementedBlogServer() {}

// UnsafeBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogServer will
// result in compilation errors.
type UnsafeBlogServer interface {
	mustEmbedUnimplementedBlogServer()
}

func RegisterBlogServer(s grpc.ServiceRegistrar, srv BlogServer) {
	s.RegisterService(&Blog_ServiceDesc, srv)
}

func _Blog_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/AddComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).AddComment(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_ApproveComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).ApproveComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/ApproveComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).ApproveComment(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).DeleteComment(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetComment(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_AddBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).AddBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/AddBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).AddBlog(ctx, req.(*BlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_UpdateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).UpdateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/UpdateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).UpdateBlog(ctx, req.(*BlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_DeleteBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).DeleteBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/DeleteBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).DeleteBlog(ctx, req.(*BlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/GetBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetBlog(ctx, req.(*BlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_BlogListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).BlogListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/BlogListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).BlogListing(ctx, req.(*BlogSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_AddPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).AddPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/AddPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).AddPosts(ctx, req.(*PostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetPost(ctx, req.(*PostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_PostsListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).PostsListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/PostsListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).PostsListing(ctx, req.(*PostSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_UpdatePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).UpdatePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/UpdatePosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).UpdatePosts(ctx, req.(*PostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_DeletePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).DeletePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.blog.Blog/DeletePosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).DeletePosts(ctx, req.(*PostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blog_ServiceDesc is the grpc.ServiceDesc for Blog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.blog.Blog",
	HandlerType: (*BlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddComment",
			Handler:    _Blog_AddComment_Handler,
		},
		{
			MethodName: "ApproveComment",
			Handler:    _Blog_ApproveComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Blog_DeleteComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _Blog_GetComment_Handler,
		},
		{
			MethodName: "AddBlog",
			Handler:    _Blog_AddBlog_Handler,
		},
		{
			MethodName: "UpdateBlog",
			Handler:    _Blog_UpdateBlog_Handler,
		},
		{
			MethodName: "DeleteBlog",
			Handler:    _Blog_DeleteBlog_Handler,
		},
		{
			MethodName: "GetBlog",
			Handler:    _Blog_GetBlog_Handler,
		},
		{
			MethodName: "BlogListing",
			Handler:    _Blog_BlogListing_Handler,
		},
		{
			MethodName: "AddPosts",
			Handler:    _Blog_AddPosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _Blog_GetPost_Handler,
		},
		{
			MethodName: "PostsListing",
			Handler:    _Blog_PostsListing_Handler,
		},
		{
			MethodName: "UpdatePosts",
			Handler:    _Blog_UpdatePosts_Handler,
		},
		{
			MethodName: "DeletePosts",
			Handler:    _Blog_DeletePosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blogs.proto",
}
