<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pages.proto

namespace Lexmodo\V1\Pages;

if (false) {
    /**
     * This class is deprecated. Use Lexmodo\V1\Pages\RuleSortBy\SORT instead.
     * @deprecated
     */
    class RuleSortBy_SORT {}
}
class_exists(RuleSortBy\SORT::class);
@trigger_error('Lexmodo\V1\Pages\RuleSortBy_SORT is deprecated and will be removed in the next major release. Use Lexmodo\V1\Pages\RuleSortBy\SORT instead', E_USER_DEPRECATED);

