// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package template

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TemplatesClient is the client API for Templates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplatesClient interface {
	SetTemplateSetting(ctx context.Context, in *TemplateSettings, opts ...grpc.CallOption) (*ResultResponse, error)
	GetTemplateSetting(ctx context.Context, in *TemplateSettings, opts ...grpc.CallOption) (*ResultResponse, error)
	GetFileHistory(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error)
	ActivateTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error)
	GetTemplates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultResponse, error)
	CreateTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error)
	GetTemplateFiles(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteNode(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error)
	FetchFile(ctx context.Context, in *Template, opts ...grpc.CallOption) (Templates_FetchFileClient, error)
	PreviewSchema(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	Preview(ctx context.Context, opts ...grpc.CallOption) (Templates_PreviewClient, error)
	ExportTemplate(ctx context.Context, in *ExportTemplateRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (Templates_UploadFileClient, error)
	RequestThemeBuilderToken(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error)
}

type templatesClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplatesClient(cc grpc.ClientConnInterface) TemplatesClient {
	return &templatesClient{cc}
}

func (c *templatesClient) SetTemplateSetting(ctx context.Context, in *TemplateSettings, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/SetTemplateSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) GetTemplateSetting(ctx context.Context, in *TemplateSettings, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/GetTemplateSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) GetFileHistory(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/GetFileHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) ActivateTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/ActivateTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) DeleteTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/DeleteTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) GetTemplates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/GetTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) CreateTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/CreateTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) GetTemplateFiles(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/GetTemplateFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) DeleteNode(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) FetchFile(ctx context.Context, in *Template, opts ...grpc.CallOption) (Templates_FetchFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Templates_ServiceDesc.Streams[0], "/lexmodo.v1.template.Templates/FetchFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &templatesFetchFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Templates_FetchFileClient interface {
	Recv() (*ResultResponse, error)
	grpc.ClientStream
}

type templatesFetchFileClient struct {
	grpc.ClientStream
}

func (x *templatesFetchFileClient) Recv() (*ResultResponse, error) {
	m := new(ResultResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templatesClient) PreviewSchema(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/PreviewSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) Preview(ctx context.Context, opts ...grpc.CallOption) (Templates_PreviewClient, error) {
	stream, err := c.cc.NewStream(ctx, &Templates_ServiceDesc.Streams[1], "/lexmodo.v1.template.Templates/Preview", opts...)
	if err != nil {
		return nil, err
	}
	x := &templatesPreviewClient{stream}
	return x, nil
}

type Templates_PreviewClient interface {
	Send(*PreviewRequest) error
	Recv() (*ResultResponse, error)
	grpc.ClientStream
}

type templatesPreviewClient struct {
	grpc.ClientStream
}

func (x *templatesPreviewClient) Send(m *PreviewRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *templatesPreviewClient) Recv() (*ResultResponse, error) {
	m := new(ResultResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templatesClient) ExportTemplate(ctx context.Context, in *ExportTemplateRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/ExportTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (Templates_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Templates_ServiceDesc.Streams[2], "/lexmodo.v1.template.Templates/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &templatesUploadFileClient{stream}
	return x, nil
}

type Templates_UploadFileClient interface {
	Send(*Template) error
	CloseAndRecv() (*ResultResponse, error)
	grpc.ClientStream
}

type templatesUploadFileClient struct {
	grpc.ClientStream
}

func (x *templatesUploadFileClient) Send(m *Template) error {
	return x.ClientStream.SendMsg(m)
}

func (x *templatesUploadFileClient) CloseAndRecv() (*ResultResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResultResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templatesClient) RequestThemeBuilderToken(ctx context.Context, in *Template, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.template.Templates/RequestThemeBuilderToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplatesServer is the server API for Templates service.
// All implementations must embed UnimplementedTemplatesServer
// for forward compatibility
type TemplatesServer interface {
	SetTemplateSetting(context.Context, *TemplateSettings) (*ResultResponse, error)
	GetTemplateSetting(context.Context, *TemplateSettings) (*ResultResponse, error)
	GetFileHistory(context.Context, *Template) (*ResultResponse, error)
	ActivateTemplate(context.Context, *Template) (*ResultResponse, error)
	DeleteTemplate(context.Context, *Template) (*ResultResponse, error)
	GetTemplates(context.Context, *emptypb.Empty) (*ResultResponse, error)
	CreateTemplate(context.Context, *Template) (*ResultResponse, error)
	GetTemplateFiles(context.Context, *Template) (*ResultResponse, error)
	DeleteNode(context.Context, *Template) (*ResultResponse, error)
	FetchFile(*Template, Templates_FetchFileServer) error
	PreviewSchema(context.Context, *PreviewRequest) (*ResultResponse, error)
	Preview(Templates_PreviewServer) error
	ExportTemplate(context.Context, *ExportTemplateRequest) (*ResultResponse, error)
	UploadFile(Templates_UploadFileServer) error
	RequestThemeBuilderToken(context.Context, *Template) (*ResultResponse, error)
	mustEmbedUnimplementedTemplatesServer()
}

// UnimplementedTemplatesServer must be embedded to have forward compatible implementations.
type UnimplementedTemplatesServer struct {
}

func (UnimplementedTemplatesServer) SetTemplateSetting(context.Context, *TemplateSettings) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTemplateSetting not implemented")
}
func (UnimplementedTemplatesServer) GetTemplateSetting(context.Context, *TemplateSettings) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateSetting not implemented")
}
func (UnimplementedTemplatesServer) GetFileHistory(context.Context, *Template) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileHistory not implemented")
}
func (UnimplementedTemplatesServer) ActivateTemplate(context.Context, *Template) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateTemplate not implemented")
}
func (UnimplementedTemplatesServer) DeleteTemplate(context.Context, *Template) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedTemplatesServer) GetTemplates(context.Context, *emptypb.Empty) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplates not implemented")
}
func (UnimplementedTemplatesServer) CreateTemplate(context.Context, *Template) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedTemplatesServer) GetTemplateFiles(context.Context, *Template) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateFiles not implemented")
}
func (UnimplementedTemplatesServer) DeleteNode(context.Context, *Template) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedTemplatesServer) FetchFile(*Template, Templates_FetchFileServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchFile not implemented")
}
func (UnimplementedTemplatesServer) PreviewSchema(context.Context, *PreviewRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewSchema not implemented")
}
func (UnimplementedTemplatesServer) Preview(Templates_PreviewServer) error {
	return status.Errorf(codes.Unimplemented, "method Preview not implemented")
}
func (UnimplementedTemplatesServer) ExportTemplate(context.Context, *ExportTemplateRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportTemplate not implemented")
}
func (UnimplementedTemplatesServer) UploadFile(Templates_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedTemplatesServer) RequestThemeBuilderToken(context.Context, *Template) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestThemeBuilderToken not implemented")
}
func (UnimplementedTemplatesServer) mustEmbedUnimplementedTemplatesServer() {}

// UnsafeTemplatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplatesServer will
// result in compilation errors.
type UnsafeTemplatesServer interface {
	mustEmbedUnimplementedTemplatesServer()
}

func RegisterTemplatesServer(s grpc.ServiceRegistrar, srv TemplatesServer) {
	s.RegisterService(&Templates_ServiceDesc, srv)
}

func _Templates_SetTemplateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).SetTemplateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/SetTemplateSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).SetTemplateSetting(ctx, req.(*TemplateSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_GetTemplateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).GetTemplateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/GetTemplateSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).GetTemplateSetting(ctx, req.(*TemplateSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_GetFileHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).GetFileHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/GetFileHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).GetFileHistory(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_ActivateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).ActivateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/ActivateTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).ActivateTemplate(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/DeleteTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).DeleteTemplate(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_GetTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).GetTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/GetTemplates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).GetTemplates(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/CreateTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).CreateTemplate(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_GetTemplateFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).GetTemplateFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/GetTemplateFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).GetTemplateFiles(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).DeleteNode(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Template)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TemplatesServer).FetchFile(m, &templatesFetchFileServer{stream})
}

type Templates_FetchFileServer interface {
	Send(*ResultResponse) error
	grpc.ServerStream
}

type templatesFetchFileServer struct {
	grpc.ServerStream
}

func (x *templatesFetchFileServer) Send(m *ResultResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Templates_PreviewSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).PreviewSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/PreviewSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).PreviewSchema(ctx, req.(*PreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_Preview_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemplatesServer).Preview(&templatesPreviewServer{stream})
}

type Templates_PreviewServer interface {
	Send(*ResultResponse) error
	Recv() (*PreviewRequest, error)
	grpc.ServerStream
}

type templatesPreviewServer struct {
	grpc.ServerStream
}

func (x *templatesPreviewServer) Send(m *ResultResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *templatesPreviewServer) Recv() (*PreviewRequest, error) {
	m := new(PreviewRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Templates_ExportTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).ExportTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/ExportTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).ExportTemplate(ctx, req.(*ExportTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemplatesServer).UploadFile(&templatesUploadFileServer{stream})
}

type Templates_UploadFileServer interface {
	SendAndClose(*ResultResponse) error
	Recv() (*Template, error)
	grpc.ServerStream
}

type templatesUploadFileServer struct {
	grpc.ServerStream
}

func (x *templatesUploadFileServer) SendAndClose(m *ResultResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *templatesUploadFileServer) Recv() (*Template, error) {
	m := new(Template)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Templates_RequestThemeBuilderToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).RequestThemeBuilderToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.template.Templates/RequestThemeBuilderToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).RequestThemeBuilderToken(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

// Templates_ServiceDesc is the grpc.ServiceDesc for Templates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Templates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.template.Templates",
	HandlerType: (*TemplatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTemplateSetting",
			Handler:    _Templates_SetTemplateSetting_Handler,
		},
		{
			MethodName: "GetTemplateSetting",
			Handler:    _Templates_GetTemplateSetting_Handler,
		},
		{
			MethodName: "GetFileHistory",
			Handler:    _Templates_GetFileHistory_Handler,
		},
		{
			MethodName: "ActivateTemplate",
			Handler:    _Templates_ActivateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _Templates_DeleteTemplate_Handler,
		},
		{
			MethodName: "GetTemplates",
			Handler:    _Templates_GetTemplates_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _Templates_CreateTemplate_Handler,
		},
		{
			MethodName: "GetTemplateFiles",
			Handler:    _Templates_GetTemplateFiles_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _Templates_DeleteNode_Handler,
		},
		{
			MethodName: "PreviewSchema",
			Handler:    _Templates_PreviewSchema_Handler,
		},
		{
			MethodName: "ExportTemplate",
			Handler:    _Templates_ExportTemplate_Handler,
		},
		{
			MethodName: "RequestThemeBuilderToken",
			Handler:    _Templates_RequestThemeBuilderToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchFile",
			Handler:       _Templates_FetchFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Preview",
			Handler:       _Templates_Preview_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _Templates_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "template.proto",
}
