<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto

namespace Lexmodo\V1\Categories;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.categories.ImageUpload</code>
 */
class ImageUpload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes file_content = 1;</code>
     */
    protected $file_content = '';
    /**
     * Generated from protobuf field <code>string image_name = 2;</code>
     */
    protected $image_name = '';
    /**
     * Generated from protobuf field <code>string category_id = 3;</code>
     */
    protected $category_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file_content
     *     @type string $image_name
     *     @type string $category_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Category::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes file_content = 1;</code>
     * @return string
     */
    public function getFileContent()
    {
        return $this->file_content;
    }

    /**
     * Generated from protobuf field <code>bytes file_content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->file_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image_name = 2;</code>
     * @return string
     */
    public function getImageName()
    {
        return $this->image_name;
    }

    /**
     * Generated from protobuf field <code>string image_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setImageName($var)
    {
        GPBUtil::checkString($var, True);
        $this->image_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_id = 3;</code>
     * @return string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * Generated from protobuf field <code>string category_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

}

