<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto

namespace Lexmodo\V1\Categories;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.categories.RuleSortBy</code>
 */
class RuleSortBy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string column_name = 1;</code>
     */
    protected $column_name = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.categories.RuleSortBy.SORT sort_order = 2;</code>
     */
    protected $sort_order = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $column_name
     *     @type int $sort_order
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Category::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string column_name = 1;</code>
     * @return string
     */
    public function getColumnName()
    {
        return $this->column_name;
    }

    /**
     * Generated from protobuf field <code>string column_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setColumnName($var)
    {
        GPBUtil::checkString($var, True);
        $this->column_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.categories.RuleSortBy.SORT sort_order = 2;</code>
     * @return int
     */
    public function getSortOrder()
    {
        return $this->sort_order;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.categories.RuleSortBy.SORT sort_order = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSortOrder($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Categories\RuleSortBy\SORT::class);
        $this->sort_order = $var;

        return $this;
    }

}

