<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipping.proto

namespace Lexmodo\V1\Shipping;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.shipping.ItemsLocations</code>
 */
class ItemsLocations extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lexmodo.v1.locations.Location fulfillment_location = 1;</code>
     */
    protected $fulfillment_location = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.labels.Parcel warehouse_parcel = 2;</code>
     */
    protected $warehouse_parcel = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lexmodo\V1\Locations\Location $fulfillment_location
     *     @type \Lexmodo\V1\Labels\Parcel $warehouse_parcel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shipping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.locations.Location fulfillment_location = 1;</code>
     * @return \Lexmodo\V1\Locations\Location|null
     */
    public function getFulfillmentLocation()
    {
        return isset($this->fulfillment_location) ? $this->fulfillment_location : null;
    }

    public function hasFulfillmentLocation()
    {
        return isset($this->fulfillment_location);
    }

    public function clearFulfillmentLocation()
    {
        unset($this->fulfillment_location);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.locations.Location fulfillment_location = 1;</code>
     * @param \Lexmodo\V1\Locations\Location $var
     * @return $this
     */
    public function setFulfillmentLocation($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Locations\Location::class);
        $this->fulfillment_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.labels.Parcel warehouse_parcel = 2;</code>
     * @return \Lexmodo\V1\Labels\Parcel|null
     */
    public function getWarehouseParcel()
    {
        return isset($this->warehouse_parcel) ? $this->warehouse_parcel : null;
    }

    public function hasWarehouseParcel()
    {
        return isset($this->warehouse_parcel);
    }

    public function clearWarehouseParcel()
    {
        unset($this->warehouse_parcel);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.labels.Parcel warehouse_parcel = 2;</code>
     * @param \Lexmodo\V1\Labels\Parcel $var
     * @return $this
     */
    public function setWarehouseParcel($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Labels\Parcel::class);
        $this->warehouse_parcel = $var;

        return $this;
    }

}

