<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipping.proto

namespace Lexmodo\V1\Shipping;

if (false) {
    /**
     * This class is deprecated. Use Lexmodo\V1\Shipping\ShippingRequest\SHIPPING_METHOD_TYPE instead.
     * @deprecated
     */
    class ShippingRequest_SHIPPING_METHOD_TYPE {}
}
class_exists(ShippingRequest\SHIPPING_METHOD_TYPE::class);
@trigger_error('Lexmodo\V1\Shipping\ShippingRequest_SHIPPING_METHOD_TYPE is deprecated and will be removed in the next major release. Use Lexmodo\V1\Shipping\ShippingRequest\SHIPPING_METHOD_TYPE instead', E_USER_DEPRECATED);

