// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: group_redis.proto

package group_redis

import (
	users "bitbucket.org/lexmodo/proto/users"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupChannel_ACTION_TYPE int32

const (
	GroupChannel_unknown       GroupChannel_ACTION_TYPE = 0
	GroupChannel_create        GroupChannel_ACTION_TYPE = 1
	GroupChannel_delete        GroupChannel_ACTION_TYPE = 2
	GroupChannel_update        GroupChannel_ACTION_TYPE = 3
	GroupChannel_member_add    GroupChannel_ACTION_TYPE = 4
	GroupChannel_member_delete GroupChannel_ACTION_TYPE = 5
	GroupChannel_get           GroupChannel_ACTION_TYPE = 6
	GroupChannel_member_groups GroupChannel_ACTION_TYPE = 7
	GroupChannel_get_all       GroupChannel_ACTION_TYPE = 8
)

// Enum value maps for GroupChannel_ACTION_TYPE.
var (
	GroupChannel_ACTION_TYPE_name = map[int32]string{
		0: "unknown",
		1: "create",
		2: "delete",
		3: "update",
		4: "member_add",
		5: "member_delete",
		6: "get",
		7: "member_groups",
		8: "get_all",
	}
	GroupChannel_ACTION_TYPE_value = map[string]int32{
		"unknown":       0,
		"create":        1,
		"delete":        2,
		"update":        3,
		"member_add":    4,
		"member_delete": 5,
		"get":           6,
		"member_groups": 7,
		"get_all":       8,
	}
)

func (x GroupChannel_ACTION_TYPE) Enum() *GroupChannel_ACTION_TYPE {
	p := new(GroupChannel_ACTION_TYPE)
	*p = x
	return p
}

func (x GroupChannel_ACTION_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupChannel_ACTION_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_group_redis_proto_enumTypes[0].Descriptor()
}

func (GroupChannel_ACTION_TYPE) Type() protoreflect.EnumType {
	return &file_group_redis_proto_enumTypes[0]
}

func (x GroupChannel_ACTION_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupChannel_ACTION_TYPE.Descriptor instead.
func (GroupChannel_ACTION_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_group_redis_proto_rawDescGZIP(), []int{0, 0}
}

type GroupChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId     uint64                   `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id"`
	ActionType   GroupChannel_ACTION_TYPE `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=lexmodo.v1.group_redis.GroupChannel_ACTION_TYPE" json:"action_type"`
	Success      bool                     `protobuf:"varint,3,opt,name=success,proto3" json:"success"`
	ErrorMessage string                   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message"`
	ReplyUuid    string                   `protobuf:"bytes,5,opt,name=reply_uuid,json=replyUuid,proto3" json:"reply_uuid"`
	Group        *users.Group             `protobuf:"bytes,6,opt,name=group,proto3" json:"group"`
}

func (x *GroupChannel) Reset() {
	*x = GroupChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_redis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChannel) ProtoMessage() {}

func (x *GroupChannel) ProtoReflect() protoreflect.Message {
	mi := &file_group_redis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChannel.ProtoReflect.Descriptor instead.
func (*GroupChannel) Descriptor() ([]byte, []int) {
	return file_group_redis_proto_rawDescGZIP(), []int{0}
}

func (x *GroupChannel) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GroupChannel) GetActionType() GroupChannel_ACTION_TYPE {
	if x != nil {
		return x.ActionType
	}
	return GroupChannel_unknown
}

func (x *GroupChannel) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GroupChannel) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GroupChannel) GetReplyUuid() string {
	if x != nil {
		return x.ReplyUuid
	}
	return ""
}

func (x *GroupChannel) GetGroup() *users.Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type ResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	ErrorMessage string         `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message"`
	Groups       []*users.Group `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups"`
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_redis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_redis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_group_redis_proto_rawDescGZIP(), []int{1}
}

func (x *ResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ResultResponse) GetGroups() []*users.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_group_redis_proto protoreflect.FileDescriptor

var file_group_redis_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6c, 0x65, 0x78, 0x6d, 0x6f, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x1a, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x03, 0x0a, 0x0c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x51, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x6c, 0x65,
	0x78, 0x6d, 0x6f, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72,
	0x65, 0x64, 0x69, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x55, 0x75, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x65, 0x78, 0x6d, 0x6f, 0x64, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x8a, 0x01, 0x0a, 0x0b, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x05, 0x12, 0x07, 0x0a,
	0x03, 0x67, 0x65, 0x74, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x67, 0x65, 0x74,
	0x5f, 0x61, 0x6c, 0x6c, 0x10, 0x08, 0x22, 0x83, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x65, 0x78, 0x6d, 0x6f,
	0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x42, 0x29, 0x5a, 0x27,
	0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x6c, 0x65,
	0x78, 0x6d, 0x6f, 0x64, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_group_redis_proto_rawDescOnce sync.Once
	file_group_redis_proto_rawDescData = file_group_redis_proto_rawDesc
)

func file_group_redis_proto_rawDescGZIP() []byte {
	file_group_redis_proto_rawDescOnce.Do(func() {
		file_group_redis_proto_rawDescData = protoimpl.X.CompressGZIP(file_group_redis_proto_rawDescData)
	})
	return file_group_redis_proto_rawDescData
}

var file_group_redis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_group_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_group_redis_proto_goTypes = []interface{}{
	(GroupChannel_ACTION_TYPE)(0), // 0: lexmodo.v1.group_redis.GroupChannel.ACTION_TYPE
	(*GroupChannel)(nil),          // 1: lexmodo.v1.group_redis.GroupChannel
	(*ResultResponse)(nil),        // 2: lexmodo.v1.group_redis.ResultResponse
	(*users.Group)(nil),           // 3: lexmodo.v1.accounts.Group
}
var file_group_redis_proto_depIdxs = []int32{
	0, // 0: lexmodo.v1.group_redis.GroupChannel.action_type:type_name -> lexmodo.v1.group_redis.GroupChannel.ACTION_TYPE
	3, // 1: lexmodo.v1.group_redis.GroupChannel.group:type_name -> lexmodo.v1.accounts.Group
	3, // 2: lexmodo.v1.group_redis.ResultResponse.groups:type_name -> lexmodo.v1.accounts.Group
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_group_redis_proto_init() }
func file_group_redis_proto_init() {
	if File_group_redis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_group_redis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_redis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_group_redis_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_redis_proto_goTypes,
		DependencyIndexes: file_group_redis_proto_depIdxs,
		EnumInfos:         file_group_redis_proto_enumTypes,
		MessageInfos:      file_group_redis_proto_msgTypes,
	}.Build()
	File_group_redis_proto = out.File
	file_group_redis_proto_rawDesc = nil
	file_group_redis_proto_goTypes = nil
	file_group_redis_proto_depIdxs = nil
}
