<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: menu.proto

namespace Lexmodo\V1\Menu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.menu.MenuItem</code>
 */
class MenuItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string seo_url = 2;</code>
     */
    protected $seo_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $seo_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Menu::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string seo_url = 2;</code>
     * @return string
     */
    public function getSeoUrl()
    {
        return $this->seo_url;
    }

    /**
     * Generated from protobuf field <code>string seo_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSeoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->seo_url = $var;

        return $this;
    }

}

