// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package customers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomersClient is the client API for Customers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomersClient interface {
	CustomerPasswordResetToken(ctx context.Context, in *CustomerResetPassword, opts ...grpc.CallOption) (*ResultResponse, error)
	CustomerPasswordReset(ctx context.Context, in *CustomerResetPassword, opts ...grpc.CallOption) (*ResultResponse, error)
	CustomerLogin(ctx context.Context, in *CustomerLoginRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	CustomerSearch(ctx context.Context, in *CustomerSearchRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCustomerRule(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCustomerByID(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCustomerAddress(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCustomerBasicInfoByID(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ConfrimCustomerRuleExists(ctx context.Context, in *CustomerRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteCustomer(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	UpdateCustomer(ctx context.Context, in *CustomerInfo, opts ...grpc.CallOption) (*ResultResponse, error)
	CreateAddress(ctx context.Context, in *AddressInfoRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteAddress(ctx context.Context, in *AddressIdRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	UpdateAddress(ctx context.Context, in *AddressInfoRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	CreateCustomerRule(ctx context.Context, in *CustomerRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteCustomerRule(ctx context.Context, in *CustomerRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCustomerListing(ctx context.Context, in *CustomerListing, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCustomerEmailLog(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetEmailContents(ctx context.Context, in *EmailLog, opts ...grpc.CallOption) (Customers_GetEmailContentsClient, error)
	ResendEmail(ctx context.Context, in *EmailLog, opts ...grpc.CallOption) (*ResultResponse, error)
	NotifyCustomer(ctx context.Context, in *CustomerNotify, opts ...grpc.CallOption) (*ResultResponse, error)
	CustomerPartOfRule(ctx context.Context, in *ApplyRuleToCustomerRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type customersClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomersClient(cc grpc.ClientConnInterface) CustomersClient {
	return &customersClient{cc}
}

func (c *customersClient) CustomerPasswordResetToken(ctx context.Context, in *CustomerResetPassword, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CustomerPasswordResetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) CustomerPasswordReset(ctx context.Context, in *CustomerResetPassword, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CustomerPasswordReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) CustomerLogin(ctx context.Context, in *CustomerLoginRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CustomerLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) CustomerSearch(ctx context.Context, in *CustomerSearchRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CustomerSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) GetCustomerRule(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/GetCustomerRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) GetCustomerByID(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/GetCustomerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) GetCustomerAddress(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/GetCustomerAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) GetCustomerBasicInfoByID(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/GetCustomerBasicInfoByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) ConfrimCustomerRuleExists(ctx context.Context, in *CustomerRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/ConfrimCustomerRuleExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) DeleteCustomer(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/DeleteCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) UpdateCustomer(ctx context.Context, in *CustomerInfo, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/UpdateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) CreateAddress(ctx context.Context, in *AddressInfoRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CreateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) DeleteAddress(ctx context.Context, in *AddressIdRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/DeleteAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) UpdateAddress(ctx context.Context, in *AddressInfoRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/UpdateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) CreateCustomerRule(ctx context.Context, in *CustomerRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CreateCustomerRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) DeleteCustomerRule(ctx context.Context, in *CustomerRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/DeleteCustomerRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) GetCustomerListing(ctx context.Context, in *CustomerListing, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/GetCustomerListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) GetCustomerEmailLog(ctx context.Context, in *CustomerIdRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/GetCustomerEmailLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) GetEmailContents(ctx context.Context, in *EmailLog, opts ...grpc.CallOption) (Customers_GetEmailContentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Customers_ServiceDesc.Streams[0], "/lexmodo.v1.customers.Customers/GetEmailContents", opts...)
	if err != nil {
		return nil, err
	}
	x := &customersGetEmailContentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Customers_GetEmailContentsClient interface {
	Recv() (*ResultResponse, error)
	grpc.ClientStream
}

type customersGetEmailContentsClient struct {
	grpc.ClientStream
}

func (x *customersGetEmailContentsClient) Recv() (*ResultResponse, error) {
	m := new(ResultResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customersClient) ResendEmail(ctx context.Context, in *EmailLog, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/ResendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) NotifyCustomer(ctx context.Context, in *CustomerNotify, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/NotifyCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) CustomerPartOfRule(ctx context.Context, in *ApplyRuleToCustomerRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.customers.Customers/CustomerPartOfRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomersServer is the server API for Customers service.
// All implementations must embed UnimplementedCustomersServer
// for forward compatibility
type CustomersServer interface {
	CustomerPasswordResetToken(context.Context, *CustomerResetPassword) (*ResultResponse, error)
	CustomerPasswordReset(context.Context, *CustomerResetPassword) (*ResultResponse, error)
	CustomerLogin(context.Context, *CustomerLoginRequest) (*ResultResponse, error)
	CustomerSearch(context.Context, *CustomerSearchRequest) (*ResultResponse, error)
	CreateCustomer(context.Context, *CreateCustomerRequest) (*ResultResponse, error)
	GetCustomerRule(context.Context, *emptypb.Empty) (*ResultResponse, error)
	GetCustomerByID(context.Context, *CustomerIdRequest) (*ResultResponse, error)
	GetCustomerAddress(context.Context, *CustomerIdRequest) (*ResultResponse, error)
	GetCustomerBasicInfoByID(context.Context, *CustomerIdRequest) (*ResultResponse, error)
	ConfrimCustomerRuleExists(context.Context, *CustomerRuleRequest) (*ResultResponse, error)
	DeleteCustomer(context.Context, *CustomerIdRequest) (*ResultResponse, error)
	UpdateCustomer(context.Context, *CustomerInfo) (*ResultResponse, error)
	CreateAddress(context.Context, *AddressInfoRequest) (*ResultResponse, error)
	DeleteAddress(context.Context, *AddressIdRequest) (*ResultResponse, error)
	UpdateAddress(context.Context, *AddressInfoRequest) (*ResultResponse, error)
	CreateCustomerRule(context.Context, *CustomerRuleRequest) (*ResultResponse, error)
	DeleteCustomerRule(context.Context, *CustomerRuleRequest) (*ResultResponse, error)
	GetCustomerListing(context.Context, *CustomerListing) (*ResultResponse, error)
	GetCustomerEmailLog(context.Context, *CustomerIdRequest) (*ResultResponse, error)
	GetEmailContents(*EmailLog, Customers_GetEmailContentsServer) error
	ResendEmail(context.Context, *EmailLog) (*ResultResponse, error)
	NotifyCustomer(context.Context, *CustomerNotify) (*ResultResponse, error)
	CustomerPartOfRule(context.Context, *ApplyRuleToCustomerRequest) (*ResultResponse, error)
	mustEmbedUnimplementedCustomersServer()
}

// UnimplementedCustomersServer must be embedded to have forward compatible implementations.
type UnimplementedCustomersServer struct {
}

func (UnimplementedCustomersServer) CustomerPasswordResetToken(context.Context, *CustomerResetPassword) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerPasswordResetToken not implemented")
}
func (UnimplementedCustomersServer) CustomerPasswordReset(context.Context, *CustomerResetPassword) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerPasswordReset not implemented")
}
func (UnimplementedCustomersServer) CustomerLogin(context.Context, *CustomerLoginRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerLogin not implemented")
}
func (UnimplementedCustomersServer) CustomerSearch(context.Context, *CustomerSearchRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerSearch not implemented")
}
func (UnimplementedCustomersServer) CreateCustomer(context.Context, *CreateCustomerRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedCustomersServer) GetCustomerRule(context.Context, *emptypb.Empty) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerRule not implemented")
}
func (UnimplementedCustomersServer) GetCustomerByID(context.Context, *CustomerIdRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerByID not implemented")
}
func (UnimplementedCustomersServer) GetCustomerAddress(context.Context, *CustomerIdRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerAddress not implemented")
}
func (UnimplementedCustomersServer) GetCustomerBasicInfoByID(context.Context, *CustomerIdRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerBasicInfoByID not implemented")
}
func (UnimplementedCustomersServer) ConfrimCustomerRuleExists(context.Context, *CustomerRuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfrimCustomerRuleExists not implemented")
}
func (UnimplementedCustomersServer) DeleteCustomer(context.Context, *CustomerIdRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomer not implemented")
}
func (UnimplementedCustomersServer) UpdateCustomer(context.Context, *CustomerInfo) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomer not implemented")
}
func (UnimplementedCustomersServer) CreateAddress(context.Context, *AddressInfoRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddress not implemented")
}
func (UnimplementedCustomersServer) DeleteAddress(context.Context, *AddressIdRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAddress not implemented")
}
func (UnimplementedCustomersServer) UpdateAddress(context.Context, *AddressInfoRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedCustomersServer) CreateCustomerRule(context.Context, *CustomerRuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomerRule not implemented")
}
func (UnimplementedCustomersServer) DeleteCustomerRule(context.Context, *CustomerRuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomerRule not implemented")
}
func (UnimplementedCustomersServer) GetCustomerListing(context.Context, *CustomerListing) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerListing not implemented")
}
func (UnimplementedCustomersServer) GetCustomerEmailLog(context.Context, *CustomerIdRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerEmailLog not implemented")
}
func (UnimplementedCustomersServer) GetEmailContents(*EmailLog, Customers_GetEmailContentsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEmailContents not implemented")
}
func (UnimplementedCustomersServer) ResendEmail(context.Context, *EmailLog) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendEmail not implemented")
}
func (UnimplementedCustomersServer) NotifyCustomer(context.Context, *CustomerNotify) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyCustomer not implemented")
}
func (UnimplementedCustomersServer) CustomerPartOfRule(context.Context, *ApplyRuleToCustomerRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerPartOfRule not implemented")
}
func (UnimplementedCustomersServer) mustEmbedUnimplementedCustomersServer() {}

// UnsafeCustomersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomersServer will
// result in compilation errors.
type UnsafeCustomersServer interface {
	mustEmbedUnimplementedCustomersServer()
}

func RegisterCustomersServer(s grpc.ServiceRegistrar, srv CustomersServer) {
	s.RegisterService(&Customers_ServiceDesc, srv)
}

func _Customers_CustomerPasswordResetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerResetPassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CustomerPasswordResetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CustomerPasswordResetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CustomerPasswordResetToken(ctx, req.(*CustomerResetPassword))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_CustomerPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerResetPassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CustomerPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CustomerPasswordReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CustomerPasswordReset(ctx, req.(*CustomerResetPassword))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_CustomerLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CustomerLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CustomerLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CustomerLogin(ctx, req.(*CustomerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_CustomerSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CustomerSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CustomerSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CustomerSearch(ctx, req.(*CustomerSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_GetCustomerRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).GetCustomerRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/GetCustomerRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).GetCustomerRule(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_GetCustomerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).GetCustomerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/GetCustomerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).GetCustomerByID(ctx, req.(*CustomerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_GetCustomerAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).GetCustomerAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/GetCustomerAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).GetCustomerAddress(ctx, req.(*CustomerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_GetCustomerBasicInfoByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).GetCustomerBasicInfoByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/GetCustomerBasicInfoByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).GetCustomerBasicInfoByID(ctx, req.(*CustomerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_ConfrimCustomerRuleExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).ConfrimCustomerRuleExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/ConfrimCustomerRuleExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).ConfrimCustomerRuleExists(ctx, req.(*CustomerRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/DeleteCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).DeleteCustomer(ctx, req.(*CustomerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/UpdateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).UpdateCustomer(ctx, req.(*CustomerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CreateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CreateAddress(ctx, req.(*AddressInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/DeleteAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).DeleteAddress(ctx, req.(*AddressIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/UpdateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).UpdateAddress(ctx, req.(*AddressInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_CreateCustomerRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CreateCustomerRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CreateCustomerRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CreateCustomerRule(ctx, req.(*CustomerRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_DeleteCustomerRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).DeleteCustomerRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/DeleteCustomerRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).DeleteCustomerRule(ctx, req.(*CustomerRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_GetCustomerListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerListing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).GetCustomerListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/GetCustomerListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).GetCustomerListing(ctx, req.(*CustomerListing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_GetCustomerEmailLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).GetCustomerEmailLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/GetCustomerEmailLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).GetCustomerEmailLog(ctx, req.(*CustomerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_GetEmailContents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmailLog)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomersServer).GetEmailContents(m, &customersGetEmailContentsServer{stream})
}

type Customers_GetEmailContentsServer interface {
	Send(*ResultResponse) error
	grpc.ServerStream
}

type customersGetEmailContentsServer struct {
	grpc.ServerStream
}

func (x *customersGetEmailContentsServer) Send(m *ResultResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Customers_ResendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).ResendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/ResendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).ResendEmail(ctx, req.(*EmailLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_NotifyCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).NotifyCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/NotifyCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).NotifyCustomer(ctx, req.(*CustomerNotify))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_CustomerPartOfRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRuleToCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).CustomerPartOfRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.customers.Customers/CustomerPartOfRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).CustomerPartOfRule(ctx, req.(*ApplyRuleToCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Customers_ServiceDesc is the grpc.ServiceDesc for Customers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Customers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.customers.Customers",
	HandlerType: (*CustomersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomerPasswordResetToken",
			Handler:    _Customers_CustomerPasswordResetToken_Handler,
		},
		{
			MethodName: "CustomerPasswordReset",
			Handler:    _Customers_CustomerPasswordReset_Handler,
		},
		{
			MethodName: "CustomerLogin",
			Handler:    _Customers_CustomerLogin_Handler,
		},
		{
			MethodName: "CustomerSearch",
			Handler:    _Customers_CustomerSearch_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _Customers_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomerRule",
			Handler:    _Customers_GetCustomerRule_Handler,
		},
		{
			MethodName: "GetCustomerByID",
			Handler:    _Customers_GetCustomerByID_Handler,
		},
		{
			MethodName: "GetCustomerAddress",
			Handler:    _Customers_GetCustomerAddress_Handler,
		},
		{
			MethodName: "GetCustomerBasicInfoByID",
			Handler:    _Customers_GetCustomerBasicInfoByID_Handler,
		},
		{
			MethodName: "ConfrimCustomerRuleExists",
			Handler:    _Customers_ConfrimCustomerRuleExists_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _Customers_DeleteCustomer_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _Customers_UpdateCustomer_Handler,
		},
		{
			MethodName: "CreateAddress",
			Handler:    _Customers_CreateAddress_Handler,
		},
		{
			MethodName: "DeleteAddress",
			Handler:    _Customers_DeleteAddress_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _Customers_UpdateAddress_Handler,
		},
		{
			MethodName: "CreateCustomerRule",
			Handler:    _Customers_CreateCustomerRule_Handler,
		},
		{
			MethodName: "DeleteCustomerRule",
			Handler:    _Customers_DeleteCustomerRule_Handler,
		},
		{
			MethodName: "GetCustomerListing",
			Handler:    _Customers_GetCustomerListing_Handler,
		},
		{
			MethodName: "GetCustomerEmailLog",
			Handler:    _Customers_GetCustomerEmailLog_Handler,
		},
		{
			MethodName: "ResendEmail",
			Handler:    _Customers_ResendEmail_Handler,
		},
		{
			MethodName: "NotifyCustomer",
			Handler:    _Customers_NotifyCustomer_Handler,
		},
		{
			MethodName: "CustomerPartOfRule",
			Handler:    _Customers_CustomerPartOfRule_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEmailContents",
			Handler:       _Customers_GetEmailContents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "customers.proto",
}
