// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugins

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PluginsClient is the client API for Plugins service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginsClient interface {
	UnInstallPlugin(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetPlugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetAllPlugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	LoginChallenge(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ConsentChallenge(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	PinWidgets(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	PinnedWidgets(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GenerateSessionToken(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type pluginsClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginsClient(cc grpc.ClientConnInterface) PluginsClient {
	return &pluginsClient{cc}
}

func (c *pluginsClient) UnInstallPlugin(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/UnInstallPlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) GetPlugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/GetPlugins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) GetAllPlugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/GetAllPlugins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) LoginChallenge(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/LoginChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) ConsentChallenge(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/ConsentChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) PinWidgets(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/PinWidgets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) PinnedWidgets(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/PinnedWidgets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) GenerateSessionToken(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.plugins.Plugins/GenerateSessionToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginsServer is the server API for Plugins service.
// All implementations must embed UnimplementedPluginsServer
// for forward compatibility
type PluginsServer interface {
	UnInstallPlugin(context.Context, *PluginsRequest) (*ResultResponse, error)
	GetPlugins(context.Context, *PluginsRequest) (*ResultResponse, error)
	GetAllPlugins(context.Context, *PluginsRequest) (*ResultResponse, error)
	LoginChallenge(context.Context, *PluginsRequest) (*ResultResponse, error)
	ConsentChallenge(context.Context, *PluginsRequest) (*ResultResponse, error)
	PinWidgets(context.Context, *PluginsRequest) (*ResultResponse, error)
	PinnedWidgets(context.Context, *PluginsRequest) (*ResultResponse, error)
	GenerateSessionToken(context.Context, *PluginsRequest) (*ResultResponse, error)
	mustEmbedUnimplementedPluginsServer()
}

// UnimplementedPluginsServer must be embedded to have forward compatible implementations.
type UnimplementedPluginsServer struct {
}

func (UnimplementedPluginsServer) UnInstallPlugin(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnInstallPlugin not implemented")
}
func (UnimplementedPluginsServer) GetPlugins(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlugins not implemented")
}
func (UnimplementedPluginsServer) GetAllPlugins(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPlugins not implemented")
}
func (UnimplementedPluginsServer) LoginChallenge(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginChallenge not implemented")
}
func (UnimplementedPluginsServer) ConsentChallenge(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsentChallenge not implemented")
}
func (UnimplementedPluginsServer) PinWidgets(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PinWidgets not implemented")
}
func (UnimplementedPluginsServer) PinnedWidgets(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PinnedWidgets not implemented")
}
func (UnimplementedPluginsServer) GenerateSessionToken(context.Context, *PluginsRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSessionToken not implemented")
}
func (UnimplementedPluginsServer) mustEmbedUnimplementedPluginsServer() {}

// UnsafePluginsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginsServer will
// result in compilation errors.
type UnsafePluginsServer interface {
	mustEmbedUnimplementedPluginsServer()
}

func RegisterPluginsServer(s grpc.ServiceRegistrar, srv PluginsServer) {
	s.RegisterService(&Plugins_ServiceDesc, srv)
}

func _Plugins_UnInstallPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).UnInstallPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/UnInstallPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).UnInstallPlugin(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_GetPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).GetPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/GetPlugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).GetPlugins(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_GetAllPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).GetAllPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/GetAllPlugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).GetAllPlugins(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_LoginChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).LoginChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/LoginChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).LoginChallenge(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_ConsentChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).ConsentChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/ConsentChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).ConsentChallenge(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_PinWidgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).PinWidgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/PinWidgets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).PinWidgets(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_PinnedWidgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).PinnedWidgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/PinnedWidgets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).PinnedWidgets(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_GenerateSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).GenerateSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.plugins.Plugins/GenerateSessionToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).GenerateSessionToken(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugins_ServiceDesc is the grpc.ServiceDesc for Plugins service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugins_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.plugins.Plugins",
	HandlerType: (*PluginsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnInstallPlugin",
			Handler:    _Plugins_UnInstallPlugin_Handler,
		},
		{
			MethodName: "GetPlugins",
			Handler:    _Plugins_GetPlugins_Handler,
		},
		{
			MethodName: "GetAllPlugins",
			Handler:    _Plugins_GetAllPlugins_Handler,
		},
		{
			MethodName: "LoginChallenge",
			Handler:    _Plugins_LoginChallenge_Handler,
		},
		{
			MethodName: "ConsentChallenge",
			Handler:    _Plugins_ConsentChallenge_Handler,
		},
		{
			MethodName: "PinWidgets",
			Handler:    _Plugins_PinWidgets_Handler,
		},
		{
			MethodName: "PinnedWidgets",
			Handler:    _Plugins_PinnedWidgets_Handler,
		},
		{
			MethodName: "GenerateSessionToken",
			Handler:    _Plugins_GenerateSessionToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins.proto",
}
