<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupons.proto

namespace Lexmodo\V1\Coupons;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.coupons.ApplyOrderModuleRequest</code>
 */
class ApplyOrderModuleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 1;</code>
     */
    protected $invoice = null;
    /**
     * Generated from protobuf field <code>string coupon_code = 2;</code>
     */
    protected $coupon_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lexmodo\V1\Orders\Invoice $invoice
     *     @type string $coupon_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupons::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 1;</code>
     * @return \Lexmodo\V1\Orders\Invoice|null
     */
    public function getInvoice()
    {
        return isset($this->invoice) ? $this->invoice : null;
    }

    public function hasInvoice()
    {
        return isset($this->invoice);
    }

    public function clearInvoice()
    {
        unset($this->invoice);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 1;</code>
     * @param \Lexmodo\V1\Orders\Invoice $var
     * @return $this
     */
    public function setInvoice($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\Invoice::class);
        $this->invoice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string coupon_code = 2;</code>
     * @return string
     */
    public function getCouponCode()
    {
        return $this->coupon_code;
    }

    /**
     * Generated from protobuf field <code>string coupon_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCouponCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->coupon_code = $var;

        return $this;
    }

}

