<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupons.proto

namespace Lexmodo\V1\Coupons;

if (false) {
    /**
     * This class is deprecated. Use Lexmodo\V1\Coupons\CouponRequest\COUPON_STATUS instead.
     * @deprecated
     */
    class CouponRequest_COUPON_STATUS {}
}
class_exists(CouponRequest\COUPON_STATUS::class);
@trigger_error('Lexmodo\V1\Coupons\CouponRequest_COUPON_STATUS is deprecated and will be removed in the next major release. Use Lexmodo\V1\Coupons\CouponRequest\COUPON_STATUS instead', E_USER_DEPRECATED);

