<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupons.proto

namespace Lexmodo\V1\Coupons;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.coupons.CustomerGets</code>
 */
class CustomerGets extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.APPLY_TYPE apply_type_setting = 1;</code>
     */
    protected $apply_type_setting = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value maximum_number_uses_per_order = 6;</code>
     */
    protected $maximum_number_uses_per_order = null;
    /**
     * Generated from protobuf field <code>double quantity_items = 7;</code>
     */
    protected $quantity_items = 0.0;
    protected $apply_to;
    protected $reward;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $apply_type_setting
     *     @type string $id
     *     @type \Lexmodo\V1\Coupons\ProductVariant $apply_to_products
     *     @type \Google\Protobuf\StringValue $at_a_discount_amount_percentage
     *     @type \Google\Protobuf\BoolValue $item_free
     *     @type \Google\Protobuf\Int32Value $maximum_number_uses_per_order
     *     @type float $quantity_items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupons::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.APPLY_TYPE apply_type_setting = 1;</code>
     * @return int
     */
    public function getApplyTypeSetting()
    {
        return $this->apply_type_setting;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.APPLY_TYPE apply_type_setting = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setApplyTypeSetting($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Coupons\APPLY_TYPE::class);
        $this->apply_type_setting = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->readOneof(2);
    }

    public function hasId()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.ProductVariant apply_to_products = 3;</code>
     * @return \Lexmodo\V1\Coupons\ProductVariant|null
     */
    public function getApplyToProducts()
    {
        return $this->readOneof(3);
    }

    public function hasApplyToProducts()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.ProductVariant apply_to_products = 3;</code>
     * @param \Lexmodo\V1\Coupons\ProductVariant $var
     * @return $this
     */
    public function setApplyToProducts($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Coupons\ProductVariant::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue at_a_discount_amount_percentage = 4;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getAtADiscountAmountPercentage()
    {
        return $this->readOneof(4);
    }

    public function hasAtADiscountAmountPercentage()
    {
        return $this->hasOneof(4);
    }

    /**
     * Returns the unboxed value from <code>getAtADiscountAmountPercentage()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue at_a_discount_amount_percentage = 4;</code>
     * @return string|null
     */
    public function getAtADiscountAmountPercentageUnwrapped()
    {
        return $this->readWrapperValue("at_a_discount_amount_percentage");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue at_a_discount_amount_percentage = 4;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setAtADiscountAmountPercentage($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue at_a_discount_amount_percentage = 4;</code>
     * @param string|null $var
     * @return $this
     */
    public function setAtADiscountAmountPercentageUnwrapped($var)
    {
        $this->writeWrapperValue("at_a_discount_amount_percentage", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue item_free = 5;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getItemFree()
    {
        return $this->readOneof(5);
    }

    public function hasItemFree()
    {
        return $this->hasOneof(5);
    }

    /**
     * Returns the unboxed value from <code>getItemFree()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue item_free = 5;</code>
     * @return bool|null
     */
    public function getItemFreeUnwrapped()
    {
        return $this->readWrapperValue("item_free");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue item_free = 5;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setItemFree($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue item_free = 5;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setItemFreeUnwrapped($var)
    {
        $this->writeWrapperValue("item_free", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value maximum_number_uses_per_order = 6;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getMaximumNumberUsesPerOrder()
    {
        return isset($this->maximum_number_uses_per_order) ? $this->maximum_number_uses_per_order : null;
    }

    public function hasMaximumNumberUsesPerOrder()
    {
        return isset($this->maximum_number_uses_per_order);
    }

    public function clearMaximumNumberUsesPerOrder()
    {
        unset($this->maximum_number_uses_per_order);
    }

    /**
     * Returns the unboxed value from <code>getMaximumNumberUsesPerOrder()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value maximum_number_uses_per_order = 6;</code>
     * @return int|null
     */
    public function getMaximumNumberUsesPerOrderUnwrapped()
    {
        return $this->readWrapperValue("maximum_number_uses_per_order");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value maximum_number_uses_per_order = 6;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setMaximumNumberUsesPerOrder($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->maximum_number_uses_per_order = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value maximum_number_uses_per_order = 6;</code>
     * @param int|null $var
     * @return $this
     */
    public function setMaximumNumberUsesPerOrderUnwrapped($var)
    {
        $this->writeWrapperValue("maximum_number_uses_per_order", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>double quantity_items = 7;</code>
     * @return float
     */
    public function getQuantityItems()
    {
        return $this->quantity_items;
    }

    /**
     * Generated from protobuf field <code>double quantity_items = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setQuantityItems($var)
    {
        GPBUtil::checkDouble($var);
        $this->quantity_items = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getApplyTo()
    {
        return $this->whichOneof("apply_to");
    }

    /**
     * @return string
     */
    public function getReward()
    {
        return $this->whichOneof("reward");
    }

}

