<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupons.proto

namespace Lexmodo\V1\Coupons;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.coupons.CustomerEligibility</code>
 */
class CustomerEligibility extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CustomerEligibility.ELIGIBILITY_TYPE eligibility_type = 1;</code>
     */
    protected $eligibility_type = 0;
    /**
     * Generated from protobuf field <code>repeated string apply_eligibility_ids = 2;</code>
     */
    private $apply_eligibility_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $eligibility_type
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $apply_eligibility_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupons::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CustomerEligibility.ELIGIBILITY_TYPE eligibility_type = 1;</code>
     * @return int
     */
    public function getEligibilityType()
    {
        return $this->eligibility_type;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CustomerEligibility.ELIGIBILITY_TYPE eligibility_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEligibilityType($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Coupons\CustomerEligibility\ELIGIBILITY_TYPE::class);
        $this->eligibility_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string apply_eligibility_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApplyEligibilityIds()
    {
        return $this->apply_eligibility_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string apply_eligibility_ids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApplyEligibilityIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->apply_eligibility_ids = $arr;

        return $this;
    }

}

