<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupons.proto

namespace Lexmodo\V1\Coupons;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.coupons.ResultResponse</code>
 */
class ResultResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>bool failure = 2;</code>
     */
    protected $failure = false;
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponRequest coupon = 5;</code>
     */
    protected $coupon = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.order.modules.OrderTotal applied_order_module = 6;</code>
     */
    protected $applied_order_module = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponRuleRequest rule = 7;</code>
     */
    protected $rule = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponListing coupon_listing = 8;</code>
     */
    protected $coupon_listing = null;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.coupons.CouponRuleRequest rules = 9;</code>
     */
    private $rules;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type bool $failure
     *     @type string $code
     *     @type string $message
     *     @type \Lexmodo\V1\Coupons\CouponRequest $coupon
     *     @type \Lexmodo\V1\Order\Modules\OrderTotal $applied_order_module
     *     @type \Lexmodo\V1\Coupons\CouponRuleRequest $rule
     *     @type \Lexmodo\V1\Coupons\CouponListing $coupon_listing
     *     @type \Lexmodo\V1\Coupons\CouponRuleRequest[]|\Google\Protobuf\Internal\RepeatedField $rules
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupons::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool failure = 2;</code>
     * @return bool
     */
    public function getFailure()
    {
        return $this->failure;
    }

    /**
     * Generated from protobuf field <code>bool failure = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFailure($var)
    {
        GPBUtil::checkBool($var);
        $this->failure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponRequest coupon = 5;</code>
     * @return \Lexmodo\V1\Coupons\CouponRequest|null
     */
    public function getCoupon()
    {
        return isset($this->coupon) ? $this->coupon : null;
    }

    public function hasCoupon()
    {
        return isset($this->coupon);
    }

    public function clearCoupon()
    {
        unset($this->coupon);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponRequest coupon = 5;</code>
     * @param \Lexmodo\V1\Coupons\CouponRequest $var
     * @return $this
     */
    public function setCoupon($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Coupons\CouponRequest::class);
        $this->coupon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.order.modules.OrderTotal applied_order_module = 6;</code>
     * @return \Lexmodo\V1\Order\Modules\OrderTotal|null
     */
    public function getAppliedOrderModule()
    {
        return isset($this->applied_order_module) ? $this->applied_order_module : null;
    }

    public function hasAppliedOrderModule()
    {
        return isset($this->applied_order_module);
    }

    public function clearAppliedOrderModule()
    {
        unset($this->applied_order_module);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.order.modules.OrderTotal applied_order_module = 6;</code>
     * @param \Lexmodo\V1\Order\Modules\OrderTotal $var
     * @return $this
     */
    public function setAppliedOrderModule($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Order\Modules\OrderTotal::class);
        $this->applied_order_module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponRuleRequest rule = 7;</code>
     * @return \Lexmodo\V1\Coupons\CouponRuleRequest|null
     */
    public function getRule()
    {
        return isset($this->rule) ? $this->rule : null;
    }

    public function hasRule()
    {
        return isset($this->rule);
    }

    public function clearRule()
    {
        unset($this->rule);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponRuleRequest rule = 7;</code>
     * @param \Lexmodo\V1\Coupons\CouponRuleRequest $var
     * @return $this
     */
    public function setRule($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Coupons\CouponRuleRequest::class);
        $this->rule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponListing coupon_listing = 8;</code>
     * @return \Lexmodo\V1\Coupons\CouponListing|null
     */
    public function getCouponListing()
    {
        return isset($this->coupon_listing) ? $this->coupon_listing : null;
    }

    public function hasCouponListing()
    {
        return isset($this->coupon_listing);
    }

    public function clearCouponListing()
    {
        unset($this->coupon_listing);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.coupons.CouponListing coupon_listing = 8;</code>
     * @param \Lexmodo\V1\Coupons\CouponListing $var
     * @return $this
     */
    public function setCouponListing($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Coupons\CouponListing::class);
        $this->coupon_listing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.coupons.CouponRuleRequest rules = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.coupons.CouponRuleRequest rules = 9;</code>
     * @param \Lexmodo\V1\Coupons\CouponRuleRequest[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Coupons\CouponRuleRequest::class);
        $this->rules = $arr;

        return $this;
    }

}

