<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payments.proto

namespace Lexmodo\V1\Payments;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.payments.CreditCardInfo</code>
 */
class CreditCardInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string card_number = 1;</code>
     */
    protected $card_number = '';
    /**
     * Generated from protobuf field <code>uint32 card_exp_month = 2;</code>
     */
    protected $card_exp_month = 0;
    /**
     * Generated from protobuf field <code>uint32 card_exp_year = 3;</code>
     */
    protected $card_exp_year = 0;
    /**
     * Generated from protobuf field <code>string card_code = 4;</code>
     */
    protected $card_code = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue payment_profile_id = 5;</code>
     */
    protected $payment_profile_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $card_number
     *     @type int $card_exp_month
     *     @type int $card_exp_year
     *     @type string $card_code
     *     @type \Google\Protobuf\StringValue $payment_profile_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payments::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string card_number = 1;</code>
     * @return string
     */
    public function getCardNumber()
    {
        return $this->card_number;
    }

    /**
     * Generated from protobuf field <code>string card_number = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCardNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 card_exp_month = 2;</code>
     * @return int
     */
    public function getCardExpMonth()
    {
        return $this->card_exp_month;
    }

    /**
     * Generated from protobuf field <code>uint32 card_exp_month = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCardExpMonth($var)
    {
        GPBUtil::checkUint32($var);
        $this->card_exp_month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 card_exp_year = 3;</code>
     * @return int
     */
    public function getCardExpYear()
    {
        return $this->card_exp_year;
    }

    /**
     * Generated from protobuf field <code>uint32 card_exp_year = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCardExpYear($var)
    {
        GPBUtil::checkUint32($var);
        $this->card_exp_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string card_code = 4;</code>
     * @return string
     */
    public function getCardCode()
    {
        return $this->card_code;
    }

    /**
     * Generated from protobuf field <code>string card_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCardCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue payment_profile_id = 5;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getPaymentProfileId()
    {
        return isset($this->payment_profile_id) ? $this->payment_profile_id : null;
    }

    public function hasPaymentProfileId()
    {
        return isset($this->payment_profile_id);
    }

    public function clearPaymentProfileId()
    {
        unset($this->payment_profile_id);
    }

    /**
     * Returns the unboxed value from <code>getPaymentProfileId()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue payment_profile_id = 5;</code>
     * @return string|null
     */
    public function getPaymentProfileIdUnwrapped()
    {
        return $this->readWrapperValue("payment_profile_id");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue payment_profile_id = 5;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setPaymentProfileId($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->payment_profile_id = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue payment_profile_id = 5;</code>
     * @param string|null $var
     * @return $this
     */
    public function setPaymentProfileIdUnwrapped($var)
    {
        $this->writeWrapperValue("payment_profile_id", $var);
        return $this;}

}

