<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payments.proto

namespace Lexmodo\V1\Payments;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.payments.SetupFields</code>
 */
class SetupFields extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     */
    protected $field_name = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.FieldType field_type = 2;</code>
     */
    protected $field_type = 0;
    /**
     * Generated from protobuf field <code>bool field_required = 3;</code>
     */
    protected $field_required = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue field_value = 4;</code>
     */
    protected $field_value = null;
    /**
     * Generated from protobuf field <code>bool read_only = 5;</code>
     */
    protected $read_only = false;
    /**
     * Generated from protobuf field <code>string field_label = 6;</code>
     */
    protected $field_label = '';
    /**
     * Generated from protobuf field <code>repeated string field_value_set = 7;</code>
     */
    private $field_value_set;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_name
     *     @type int $field_type
     *     @type bool $field_required
     *     @type \Google\Protobuf\StringValue $field_value
     *     @type bool $read_only
     *     @type string $field_label
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $field_value_set
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payments::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.FieldType field_type = 2;</code>
     * @return int
     */
    public function getFieldType()
    {
        return $this->field_type;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.FieldType field_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldType($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Payments\FieldType::class);
        $this->field_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool field_required = 3;</code>
     * @return bool
     */
    public function getFieldRequired()
    {
        return $this->field_required;
    }

    /**
     * Generated from protobuf field <code>bool field_required = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFieldRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->field_required = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue field_value = 4;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getFieldValue()
    {
        return isset($this->field_value) ? $this->field_value : null;
    }

    public function hasFieldValue()
    {
        return isset($this->field_value);
    }

    public function clearFieldValue()
    {
        unset($this->field_value);
    }

    /**
     * Returns the unboxed value from <code>getFieldValue()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue field_value = 4;</code>
     * @return string|null
     */
    public function getFieldValueUnwrapped()
    {
        return $this->readWrapperValue("field_value");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue field_value = 4;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setFieldValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->field_value = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue field_value = 4;</code>
     * @param string|null $var
     * @return $this
     */
    public function setFieldValueUnwrapped($var)
    {
        $this->writeWrapperValue("field_value", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>bool read_only = 5;</code>
     * @return bool
     */
    public function getReadOnly()
    {
        return $this->read_only;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->read_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string field_label = 6;</code>
     * @return string
     */
    public function getFieldLabel()
    {
        return $this->field_label;
    }

    /**
     * Generated from protobuf field <code>string field_label = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string field_value_set = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldValueSet()
    {
        return $this->field_value_set;
    }

    /**
     * Generated from protobuf field <code>repeated string field_value_set = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldValueSet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->field_value_set = $arr;

        return $this;
    }

}

