<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_providers.proto

namespace Lexmodo\V1\Payments_providers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.payments_providers.PaymentProvider</code>
 */
class PaymentProvider extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 provider_id = 1;</code>
     */
    protected $provider_id = 0;
    /**
     * Generated from protobuf field <code>string provider_name = 2;</code>
     */
    protected $provider_name = '';
    /**
     * Generated from protobuf field <code>string provider_about = 3;</code>
     */
    protected $provider_about = '';
    /**
     * Generated from protobuf field <code>string provider_link = 4;</code>
     */
    protected $provider_link = '';
    /**
     * Generated from protobuf field <code>string provider_fees = 5;</code>
     */
    protected $provider_fees = '';
    /**
     * Generated from protobuf field <code>string credit_card_rate = 6;</code>
     */
    protected $credit_card_rate = '';
    /**
     * Generated from protobuf field <code>repeated string provider_accepted_currencies = 7;</code>
     */
    private $provider_accepted_currencies;
    /**
     * Generated from protobuf field <code>bool provider_allow_saved_cards = 8;</code>
     */
    protected $provider_allow_saved_cards = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $provider_id
     *     @type string $provider_name
     *     @type string $provider_about
     *     @type string $provider_link
     *     @type string $provider_fees
     *     @type string $credit_card_rate
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $provider_accepted_currencies
     *     @type bool $provider_allow_saved_cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PaymentProviders::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 provider_id = 1;</code>
     * @return int
     */
    public function getProviderId()
    {
        return $this->provider_id;
    }

    /**
     * Generated from protobuf field <code>uint32 provider_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProviderId($var)
    {
        GPBUtil::checkUint32($var);
        $this->provider_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string provider_name = 2;</code>
     * @return string
     */
    public function getProviderName()
    {
        return $this->provider_name;
    }

    /**
     * Generated from protobuf field <code>string provider_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string provider_about = 3;</code>
     * @return string
     */
    public function getProviderAbout()
    {
        return $this->provider_about;
    }

    /**
     * Generated from protobuf field <code>string provider_about = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderAbout($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_about = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string provider_link = 4;</code>
     * @return string
     */
    public function getProviderLink()
    {
        return $this->provider_link;
    }

    /**
     * Generated from protobuf field <code>string provider_link = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string provider_fees = 5;</code>
     * @return string
     */
    public function getProviderFees()
    {
        return $this->provider_fees;
    }

    /**
     * Generated from protobuf field <code>string provider_fees = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderFees($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_fees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string credit_card_rate = 6;</code>
     * @return string
     */
    public function getCreditCardRate()
    {
        return $this->credit_card_rate;
    }

    /**
     * Generated from protobuf field <code>string credit_card_rate = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreditCardRate($var)
    {
        GPBUtil::checkString($var, True);
        $this->credit_card_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string provider_accepted_currencies = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProviderAcceptedCurrencies()
    {
        return $this->provider_accepted_currencies;
    }

    /**
     * Generated from protobuf field <code>repeated string provider_accepted_currencies = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProviderAcceptedCurrencies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->provider_accepted_currencies = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool provider_allow_saved_cards = 8;</code>
     * @return bool
     */
    public function getProviderAllowSavedCards()
    {
        return $this->provider_allow_saved_cards;
    }

    /**
     * Generated from protobuf field <code>bool provider_allow_saved_cards = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setProviderAllowSavedCards($var)
    {
        GPBUtil::checkBool($var);
        $this->provider_allow_saved_cards = $var;

        return $this;
    }

}

