<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto

namespace Lexmodo\V1\Template;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.template.FileData</code>
 */
class FileData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Content = 1;</code>
     */
    protected $Content = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.FILE_TYPE file_type = 2;</code>
     */
    protected $file_type = 0;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.CORE_FILE core_file = 3;</code>
     */
    protected $core_file = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Content
     *     @type int $file_type
     *     @type int $core_file
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Template::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Generated from protobuf field <code>bytes Content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.FILE_TYPE file_type = 2;</code>
     * @return int
     */
    public function getFileType()
    {
        return $this->file_type;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.FILE_TYPE file_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFileType($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Template\FILE_TYPE::class);
        $this->file_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.CORE_FILE core_file = 3;</code>
     * @return int
     */
    public function getCoreFile()
    {
        return $this->core_file;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.CORE_FILE core_file = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCoreFile($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Template\CORE_FILE::class);
        $this->core_file = $var;

        return $this;
    }

}

