<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto

namespace Lexmodo\V1\Template;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.template.Node</code>
 */
class Node extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.FileInfo info = 2;</code>
     */
    protected $info = null;
    /**
     *Node Parent =4;
     *
     * Generated from protobuf field <code>repeated .lexmodo.v1.template.Node children = 3;</code>
     */
    private $children;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *     @type \Lexmodo\V1\Template\FileInfo $info
     *     @type \Lexmodo\V1\Template\Node[]|\Google\Protobuf\Internal\RepeatedField $children
     *          Node Parent =4;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Template::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.FileInfo info = 2;</code>
     * @return \Lexmodo\V1\Template\FileInfo|null
     */
    public function getInfo()
    {
        return isset($this->info) ? $this->info : null;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.template.FileInfo info = 2;</code>
     * @param \Lexmodo\V1\Template\FileInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Template\FileInfo::class);
        $this->info = $var;

        return $this;
    }

    /**
     *Node Parent =4;
     *
     * Generated from protobuf field <code>repeated .lexmodo.v1.template.Node children = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     *Node Parent =4;
     *
     * Generated from protobuf field <code>repeated .lexmodo.v1.template.Node children = 3;</code>
     * @param \Lexmodo\V1\Template\Node[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChildren($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Template\Node::class);
        $this->children = $arr;

        return $this;
    }

}

