<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store_credit.proto

namespace Lexmodo\V1\Store_credit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.store_credit.ApplyOrderModuleRequest</code>
 */
class ApplyOrderModuleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 1;</code>
     */
    protected $invoice = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.store_credit.AWARD_SETTINGS award_action = 2;</code>
     */
    protected $award_action = 0;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.store_credit.LedgerRequest ledger = 3;</code>
     */
    protected $ledger = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lexmodo\V1\Orders\Invoice $invoice
     *     @type int $award_action
     *     @type \Lexmodo\V1\Store_credit\LedgerRequest $ledger
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StoreCredit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 1;</code>
     * @return \Lexmodo\V1\Orders\Invoice|null
     */
    public function getInvoice()
    {
        return isset($this->invoice) ? $this->invoice : null;
    }

    public function hasInvoice()
    {
        return isset($this->invoice);
    }

    public function clearInvoice()
    {
        unset($this->invoice);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 1;</code>
     * @param \Lexmodo\V1\Orders\Invoice $var
     * @return $this
     */
    public function setInvoice($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\Invoice::class);
        $this->invoice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.store_credit.AWARD_SETTINGS award_action = 2;</code>
     * @return int
     */
    public function getAwardAction()
    {
        return $this->award_action;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.store_credit.AWARD_SETTINGS award_action = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAwardAction($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Store_credit\AWARD_SETTINGS::class);
        $this->award_action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.store_credit.LedgerRequest ledger = 3;</code>
     * @return \Lexmodo\V1\Store_credit\LedgerRequest|null
     */
    public function getLedger()
    {
        return isset($this->ledger) ? $this->ledger : null;
    }

    public function hasLedger()
    {
        return isset($this->ledger);
    }

    public function clearLedger()
    {
        unset($this->ledger);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.store_credit.LedgerRequest ledger = 3;</code>
     * @param \Lexmodo\V1\Store_credit\LedgerRequest $var
     * @return $this
     */
    public function setLedger($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Store_credit\LedgerRequest::class);
        $this->ledger = $var;

        return $this;
    }

}

