<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store_credit.proto

namespace Lexmodo\V1\Store_credit;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.store_credit.AWARD_SETTINGS</code>
 */
class AWARD_SETTINGS
{
    /**
     * Generated from protobuf enum <code>order_placed = 0;</code>
     */
    const order_placed = 0;
    /**
     * Generated from protobuf enum <code>order_shipped = 1;</code>
     */
    const order_shipped = 1;
    /**
     * Generated from protobuf enum <code>customer_signup = 2;</code>
     */
    const customer_signup = 2;
    /**
     * Generated from protobuf enum <code>customer_newsletter = 3;</code>
     */
    const customer_newsletter = 3;
    /**
     * Generated from protobuf enum <code>gift_card = 4;</code>
     */
    const gift_card = 4;
    /**
     * Generated from protobuf enum <code>custom_amount = 5;</code>
     */
    const custom_amount = 5;

    private static $valueToName = [
        self::order_placed => 'order_placed',
        self::order_shipped => 'order_shipped',
        self::customer_signup => 'customer_signup',
        self::customer_newsletter => 'customer_newsletter',
        self::gift_card => 'gift_card',
        self::custom_amount => 'custom_amount',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

