<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sitemap.proto

namespace Lexmodo\V1\Sitemap;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.sitemap.FileInfo</code>
 */
class FileInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>uint64 size = 2;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>uint64 modification_time = 3;</code>
     */
    protected $modification_time = 0;
    /**
     * Generated from protobuf field <code>bytes Content = 4;</code>
     */
    protected $Content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int|string $size
     *     @type int|string $modification_time
     *     @type string $Content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sitemap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 2;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 modification_time = 3;</code>
     * @return int|string
     */
    public function getModificationTime()
    {
        return $this->modification_time;
    }

    /**
     * Generated from protobuf field <code>uint64 modification_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setModificationTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->modification_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Generated from protobuf field <code>bytes Content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

}

