// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package image_handler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageHandlerClient is the client API for ImageHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageHandlerClient interface {
	ListImage(ctx context.Context, in *ImageListing, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ResultResponse, error)
	FetchImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (ImageHandler_FetchImageClient, error)
	UploadImage(ctx context.Context, opts ...grpc.CallOption) (ImageHandler_UploadImageClient, error)
}

type imageHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewImageHandlerClient(cc grpc.ClientConnInterface) ImageHandlerClient {
	return &imageHandlerClient{cc}
}

func (c *imageHandlerClient) ListImage(ctx context.Context, in *ImageListing, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.image_handler.ImageHandler/ListImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageHandlerClient) DeleteImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.image_handler.ImageHandler/DeleteImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageHandlerClient) FetchImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (ImageHandler_FetchImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImageHandler_ServiceDesc.Streams[0], "/lexmodo.v1.image_handler.ImageHandler/FetchImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageHandlerFetchImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ImageHandler_FetchImageClient interface {
	Recv() (*ResultResponse, error)
	grpc.ClientStream
}

type imageHandlerFetchImageClient struct {
	grpc.ClientStream
}

func (x *imageHandlerFetchImageClient) Recv() (*ResultResponse, error) {
	m := new(ResultResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imageHandlerClient) UploadImage(ctx context.Context, opts ...grpc.CallOption) (ImageHandler_UploadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImageHandler_ServiceDesc.Streams[1], "/lexmodo.v1.image_handler.ImageHandler/UploadImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageHandlerUploadImageClient{stream}
	return x, nil
}

type ImageHandler_UploadImageClient interface {
	Send(*Image) error
	CloseAndRecv() (*ResultResponse, error)
	grpc.ClientStream
}

type imageHandlerUploadImageClient struct {
	grpc.ClientStream
}

func (x *imageHandlerUploadImageClient) Send(m *Image) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageHandlerUploadImageClient) CloseAndRecv() (*ResultResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResultResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageHandlerServer is the server API for ImageHandler service.
// All implementations must embed UnimplementedImageHandlerServer
// for forward compatibility
type ImageHandlerServer interface {
	ListImage(context.Context, *ImageListing) (*ResultResponse, error)
	DeleteImage(context.Context, *Image) (*ResultResponse, error)
	FetchImage(*Image, ImageHandler_FetchImageServer) error
	UploadImage(ImageHandler_UploadImageServer) error
	mustEmbedUnimplementedImageHandlerServer()
}

// UnimplementedImageHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedImageHandlerServer struct {
}

func (UnimplementedImageHandlerServer) ListImage(context.Context, *ImageListing) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImage not implemented")
}
func (UnimplementedImageHandlerServer) DeleteImage(context.Context, *Image) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedImageHandlerServer) FetchImage(*Image, ImageHandler_FetchImageServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchImage not implemented")
}
func (UnimplementedImageHandlerServer) UploadImage(ImageHandler_UploadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedImageHandlerServer) mustEmbedUnimplementedImageHandlerServer() {}

// UnsafeImageHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageHandlerServer will
// result in compilation errors.
type UnsafeImageHandlerServer interface {
	mustEmbedUnimplementedImageHandlerServer()
}

func RegisterImageHandlerServer(s grpc.ServiceRegistrar, srv ImageHandlerServer) {
	s.RegisterService(&ImageHandler_ServiceDesc, srv)
}

func _ImageHandler_ListImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageListing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageHandlerServer).ListImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.image_handler.ImageHandler/ListImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageHandlerServer).ListImage(ctx, req.(*ImageListing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageHandler_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageHandlerServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.image_handler.ImageHandler/DeleteImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageHandlerServer).DeleteImage(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageHandler_FetchImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Image)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageHandlerServer).FetchImage(m, &imageHandlerFetchImageServer{stream})
}

type ImageHandler_FetchImageServer interface {
	Send(*ResultResponse) error
	grpc.ServerStream
}

type imageHandlerFetchImageServer struct {
	grpc.ServerStream
}

func (x *imageHandlerFetchImageServer) Send(m *ResultResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ImageHandler_UploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageHandlerServer).UploadImage(&imageHandlerUploadImageServer{stream})
}

type ImageHandler_UploadImageServer interface {
	SendAndClose(*ResultResponse) error
	Recv() (*Image, error)
	grpc.ServerStream
}

type imageHandlerUploadImageServer struct {
	grpc.ServerStream
}

func (x *imageHandlerUploadImageServer) SendAndClose(m *ResultResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageHandlerUploadImageServer) Recv() (*Image, error) {
	m := new(Image)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageHandler_ServiceDesc is the grpc.ServiceDesc for ImageHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.image_handler.ImageHandler",
	HandlerType: (*ImageHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImage",
			Handler:    _ImageHandler_ListImage_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImageHandler_DeleteImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchImage",
			Handler:       _ImageHandler_FetchImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadImage",
			Handler:       _ImageHandler_UploadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "image_handler.proto",
}
