<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labels.proto

namespace Lexmodo\V1\Labels;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.labels.CustomItem</code>
 */
class CustomItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>double quantity = 2;</code>
     */
    protected $quantity = 0.0;
    /**
     * in USD
     *
     * Generated from protobuf field <code>.lexmodo.v1.money.Money total_value = 3;</code>
     */
    protected $total_value = null;
    /**
     *Weights are in OUNCES (OZ) and go to one decimal point
     *
     * Generated from protobuf field <code>double weight = 4;</code>
     */
    protected $weight = 0.0;
    /**
     * Generated from protobuf field <code>string hs_tariff_number = 5;</code>
     */
    protected $hs_tariff_number = '';
    /**
     * Generated from protobuf field <code>string code = 6;</code>
     */
    protected $code = '';
    /**
     *Required, 2 char country code
     *
     * Generated from protobuf field <code>string origin_country = 7;</code>
     */
    protected $origin_country = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type float $quantity
     *     @type \Lexmodo\V1\Money\Money $total_value
     *           in USD
     *     @type float $weight
     *          Weights are in OUNCES (OZ) and go to one decimal point
     *     @type string $hs_tariff_number
     *     @type string $code
     *     @type string $origin_country
     *          Required, 2 char country code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Labels::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double quantity = 2;</code>
     * @return float
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>double quantity = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkDouble($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * in USD
     *
     * Generated from protobuf field <code>.lexmodo.v1.money.Money total_value = 3;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getTotalValue()
    {
        return isset($this->total_value) ? $this->total_value : null;
    }

    public function hasTotalValue()
    {
        return isset($this->total_value);
    }

    public function clearTotalValue()
    {
        unset($this->total_value);
    }

    /**
     * in USD
     *
     * Generated from protobuf field <code>.lexmodo.v1.money.Money total_value = 3;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setTotalValue($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->total_value = $var;

        return $this;
    }

    /**
     *Weights are in OUNCES (OZ) and go to one decimal point
     *
     * Generated from protobuf field <code>double weight = 4;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     *Weights are in OUNCES (OZ) and go to one decimal point
     *
     * Generated from protobuf field <code>double weight = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hs_tariff_number = 5;</code>
     * @return string
     */
    public function getHsTariffNumber()
    {
        return $this->hs_tariff_number;
    }

    /**
     * Generated from protobuf field <code>string hs_tariff_number = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHsTariffNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->hs_tariff_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 6;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     *Required, 2 char country code
     *
     * Generated from protobuf field <code>string origin_country = 7;</code>
     * @return string
     */
    public function getOriginCountry()
    {
        return $this->origin_country;
    }

    /**
     *Required, 2 char country code
     *
     * Generated from protobuf field <code>string origin_country = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin_country = $var;

        return $this;
    }

}

