// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package payments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentsClient is the client API for Payments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentsClient interface {
	ReAuthorizePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteCreditCard(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	SaveCreditCard(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	CapturePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	VoidPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	RefundPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	SetConfig(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetConfig(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetSavedCreditCard(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	AcceptedCards(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ExpressCheckout(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DisplayFields(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	PaymentLog(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type paymentsClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsClient(cc grpc.ClientConnInterface) PaymentsClient {
	return &paymentsClient{cc}
}

func (c *paymentsClient) ReAuthorizePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/ReAuthorizePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) DeleteCreditCard(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/DeleteCreditCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) SaveCreditCard(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/SaveCreditCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/ProcessPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) CapturePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/CapturePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) VoidPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/VoidPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) RefundPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/RefundPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) SetConfig(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) GetConfig(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) GetSavedCreditCard(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/GetSavedCreditCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) AcceptedCards(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/AcceptedCards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) ExpressCheckout(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/ExpressCheckout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) DisplayFields(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/DisplayFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) PaymentLog(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.payments.Payments/PaymentLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsServer is the server API for Payments service.
// All implementations must embed UnimplementedPaymentsServer
// for forward compatibility
type PaymentsServer interface {
	ReAuthorizePayment(context.Context, *PaymentRequest) (*ResultResponse, error)
	DeleteCreditCard(context.Context, *PaymentRequest) (*ResultResponse, error)
	SaveCreditCard(context.Context, *PaymentRequest) (*ResultResponse, error)
	ProcessPayment(context.Context, *PaymentRequest) (*ResultResponse, error)
	CapturePayment(context.Context, *PaymentRequest) (*ResultResponse, error)
	VoidPayment(context.Context, *PaymentRequest) (*ResultResponse, error)
	RefundPayment(context.Context, *PaymentRequest) (*ResultResponse, error)
	SetConfig(context.Context, *PaymentRequest) (*ResultResponse, error)
	GetConfig(context.Context, *PaymentRequest) (*ResultResponse, error)
	GetSavedCreditCard(context.Context, *PaymentRequest) (*ResultResponse, error)
	AcceptedCards(context.Context, *PaymentRequest) (*ResultResponse, error)
	ExpressCheckout(context.Context, *PaymentRequest) (*ResultResponse, error)
	DisplayFields(context.Context, *PaymentRequest) (*ResultResponse, error)
	PaymentLog(context.Context, *PaymentRequest) (*ResultResponse, error)
	mustEmbedUnimplementedPaymentsServer()
}

// UnimplementedPaymentsServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentsServer struct {
}

func (UnimplementedPaymentsServer) ReAuthorizePayment(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReAuthorizePayment not implemented")
}
func (UnimplementedPaymentsServer) DeleteCreditCard(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCreditCard not implemented")
}
func (UnimplementedPaymentsServer) SaveCreditCard(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCreditCard not implemented")
}
func (UnimplementedPaymentsServer) ProcessPayment(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPayment not implemented")
}
func (UnimplementedPaymentsServer) CapturePayment(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CapturePayment not implemented")
}
func (UnimplementedPaymentsServer) VoidPayment(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoidPayment not implemented")
}
func (UnimplementedPaymentsServer) RefundPayment(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundPayment not implemented")
}
func (UnimplementedPaymentsServer) SetConfig(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedPaymentsServer) GetConfig(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedPaymentsServer) GetSavedCreditCard(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSavedCreditCard not implemented")
}
func (UnimplementedPaymentsServer) AcceptedCards(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptedCards not implemented")
}
func (UnimplementedPaymentsServer) ExpressCheckout(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpressCheckout not implemented")
}
func (UnimplementedPaymentsServer) DisplayFields(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisplayFields not implemented")
}
func (UnimplementedPaymentsServer) PaymentLog(context.Context, *PaymentRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentLog not implemented")
}
func (UnimplementedPaymentsServer) mustEmbedUnimplementedPaymentsServer() {}

// UnsafePaymentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsServer will
// result in compilation errors.
type UnsafePaymentsServer interface {
	mustEmbedUnimplementedPaymentsServer()
}

func RegisterPaymentsServer(s grpc.ServiceRegistrar, srv PaymentsServer) {
	s.RegisterService(&Payments_ServiceDesc, srv)
}

func _Payments_ReAuthorizePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).ReAuthorizePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/ReAuthorizePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).ReAuthorizePayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_DeleteCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).DeleteCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/DeleteCreditCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).DeleteCreditCard(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_SaveCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).SaveCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/SaveCreditCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).SaveCreditCard(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/ProcessPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).ProcessPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_CapturePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).CapturePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/CapturePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).CapturePayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_VoidPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).VoidPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/VoidPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).VoidPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_RefundPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).RefundPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/RefundPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).RefundPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).SetConfig(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).GetConfig(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_GetSavedCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).GetSavedCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/GetSavedCreditCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).GetSavedCreditCard(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_AcceptedCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).AcceptedCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/AcceptedCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).AcceptedCards(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_ExpressCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).ExpressCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/ExpressCheckout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).ExpressCheckout(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_DisplayFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).DisplayFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/DisplayFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).DisplayFields(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_PaymentLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).PaymentLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.payments.Payments/PaymentLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).PaymentLog(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payments_ServiceDesc is the grpc.ServiceDesc for Payments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.payments.Payments",
	HandlerType: (*PaymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReAuthorizePayment",
			Handler:    _Payments_ReAuthorizePayment_Handler,
		},
		{
			MethodName: "DeleteCreditCard",
			Handler:    _Payments_DeleteCreditCard_Handler,
		},
		{
			MethodName: "SaveCreditCard",
			Handler:    _Payments_SaveCreditCard_Handler,
		},
		{
			MethodName: "ProcessPayment",
			Handler:    _Payments_ProcessPayment_Handler,
		},
		{
			MethodName: "CapturePayment",
			Handler:    _Payments_CapturePayment_Handler,
		},
		{
			MethodName: "VoidPayment",
			Handler:    _Payments_VoidPayment_Handler,
		},
		{
			MethodName: "RefundPayment",
			Handler:    _Payments_RefundPayment_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Payments_SetConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Payments_GetConfig_Handler,
		},
		{
			MethodName: "GetSavedCreditCard",
			Handler:    _Payments_GetSavedCreditCard_Handler,
		},
		{
			MethodName: "AcceptedCards",
			Handler:    _Payments_AcceptedCards_Handler,
		},
		{
			MethodName: "ExpressCheckout",
			Handler:    _Payments_ExpressCheckout_Handler,
		},
		{
			MethodName: "DisplayFields",
			Handler:    _Payments_DisplayFields_Handler,
		},
		{
			MethodName: "PaymentLog",
			Handler:    _Payments_PaymentLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments.proto",
}
