<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locations.proto

namespace Lexmodo\V1\Locations;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.locations.Location</code>
 */
class Location extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string location_id = 1;</code>
     */
    protected $location_id = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address location_address = 2;</code>
     */
    protected $location_address = null;
    /**
     * Generated from protobuf field <code>bool is_default = 3;</code>
     */
    protected $is_default = false;
    /**
     * Generated from protobuf field <code>bool active = 4;</code>
     */
    protected $active = false;
    /**
     * Generated from protobuf field <code>uint64 updated_on = 5;</code>
     */
    protected $updated_on = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $location_id
     *     @type \Lexmodo\V1\Address\Address $location_address
     *     @type bool $is_default
     *     @type bool $active
     *     @type int|string $updated_on
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Locations::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string location_id = 1;</code>
     * @return string
     */
    public function getLocationId()
    {
        return $this->location_id;
    }

    /**
     * Generated from protobuf field <code>string location_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLocationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->location_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address location_address = 2;</code>
     * @return \Lexmodo\V1\Address\Address|null
     */
    public function getLocationAddress()
    {
        return isset($this->location_address) ? $this->location_address : null;
    }

    public function hasLocationAddress()
    {
        return isset($this->location_address);
    }

    public function clearLocationAddress()
    {
        unset($this->location_address);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address location_address = 2;</code>
     * @param \Lexmodo\V1\Address\Address $var
     * @return $this
     */
    public function setLocationAddress($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Address\Address::class);
        $this->location_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_default = 3;</code>
     * @return bool
     */
    public function getIsDefault()
    {
        return $this->is_default;
    }

    /**
     * Generated from protobuf field <code>bool is_default = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefault($var)
    {
        GPBUtil::checkBool($var);
        $this->is_default = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool active = 4;</code>
     * @return bool
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Generated from protobuf field <code>bool active = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 updated_on = 5;</code>
     * @return int|string
     */
    public function getUpdatedOn()
    {
        return $this->updated_on;
    }

    /**
     * Generated from protobuf field <code>uint64 updated_on = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedOn($var)
    {
        GPBUtil::checkUint64($var);
        $this->updated_on = $var;

        return $this;
    }

}

