<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto

namespace Lexmodo\V1\Address\Address;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.address.Address.ADDRESS_TYPE</code>
 */
class ADDRESS_TYPE
{
    /**
     * Generated from protobuf enum <code>unkown = 0;</code>
     */
    const unkown = 0;
    /**
     * Generated from protobuf enum <code>customer = 1;</code>
     */
    const customer = 1;
    /**
     * Generated from protobuf enum <code>location = 2;</code>
     */
    const location = 2;
    /**
     * Generated from protobuf enum <code>store = 3;</code>
     */
    const store = 3;

    private static $valueToName = [
        self::unkown => 'unkown',
        self::customer => 'customer',
        self::location => 'location',
        self::store => 'store',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ADDRESS_TYPE::class, \Lexmodo\V1\Address\Address_ADDRESS_TYPE::class);

