<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labels.proto

namespace Lexmodo\V1\Labels\CustomsInfo;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.labels.CustomsInfo.RESTRICTION</code>
 */
class RESTRICTION
{
    /**
     * Generated from protobuf enum <code>none = 0;</code>
     */
    const none = 0;
    /**
     * Generated from protobuf enum <code>restriction_other = 1;</code>
     */
    const restriction_other = 1;
    /**
     * Generated from protobuf enum <code>quarantine = 2;</code>
     */
    const quarantine = 2;
    /**
     * Generated from protobuf enum <code>sanitary_phytosanitary_inspection = 3;</code>
     */
    const sanitary_phytosanitary_inspection = 3;

    private static $valueToName = [
        self::none => 'none',
        self::restriction_other => 'restriction_other',
        self::quarantine => 'quarantine',
        self::sanitary_phytosanitary_inspection => 'sanitary_phytosanitary_inspection',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RESTRICTION::class, \Lexmodo\V1\Labels\CustomsInfo_RESTRICTION::class);

