<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto

namespace Lexmodo\V1\Settings;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.settings.AutoFulfillOption</code>
 */
class AutoFulfillOption
{
    /**
     * Generated from protobuf enum <code>AUTO_FULFILL_LINE_ITEMS = 0;</code>
     */
    const AUTO_FULFILL_LINE_ITEMS = 0;
    /**
     * Generated from protobuf enum <code>AUTO_FULFILL_GIFT_CARDS = 1;</code>
     */
    const AUTO_FULFILL_GIFT_CARDS = 1;
    /**
     * Generated from protobuf enum <code>NOT_AUTO_FULFILL = 2;</code>
     */
    const NOT_AUTO_FULFILL = 2;

    private static $valueToName = [
        self::AUTO_FULFILL_LINE_ITEMS => 'AUTO_FULFILL_LINE_ITEMS',
        self::AUTO_FULFILL_GIFT_CARDS => 'AUTO_FULFILL_GIFT_CARDS',
        self::NOT_AUTO_FULFILL => 'NOT_AUTO_FULFILL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

