<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto

namespace Lexmodo\V1\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.settings.BlockedIPRequest</code>
 */
class BlockedIPRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ip_address = 1;</code>
     */
    protected $ip_address = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue blocked_reason = 2;</code>
     */
    protected $blocked_reason = null;
    /**
     * Generated from protobuf field <code>uint32 blocked_on = 3;</code>
     */
    protected $blocked_on = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ip_address
     *     @type \Google\Protobuf\StringValue $blocked_reason
     *     @type int $blocked_on
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Settings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ip_address = 1;</code>
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ip_address;
    }

    /**
     * Generated from protobuf field <code>string ip_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue blocked_reason = 2;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getBlockedReason()
    {
        return isset($this->blocked_reason) ? $this->blocked_reason : null;
    }

    public function hasBlockedReason()
    {
        return isset($this->blocked_reason);
    }

    public function clearBlockedReason()
    {
        unset($this->blocked_reason);
    }

    /**
     * Returns the unboxed value from <code>getBlockedReason()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue blocked_reason = 2;</code>
     * @return string|null
     */
    public function getBlockedReasonUnwrapped()
    {
        return $this->readWrapperValue("blocked_reason");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue blocked_reason = 2;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setBlockedReason($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->blocked_reason = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue blocked_reason = 2;</code>
     * @param string|null $var
     * @return $this
     */
    public function setBlockedReasonUnwrapped($var)
    {
        $this->writeWrapperValue("blocked_reason", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>uint32 blocked_on = 3;</code>
     * @return int
     */
    public function getBlockedOn()
    {
        return $this->blocked_on;
    }

    /**
     * Generated from protobuf field <code>uint32 blocked_on = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockedOn($var)
    {
        GPBUtil::checkUint32($var);
        $this->blocked_on = $var;

        return $this;
    }

}

