<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto

namespace Lexmodo\V1\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.settings.Google</code>
 */
class Google extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string website_id = 1;</code>
     */
    protected $website_id = '';
    /**
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string access_token = 3;</code>
     */
    protected $access_token = '';
    /**
     * Generated from protobuf field <code>string auth_url = 4;</code>
     */
    protected $auth_url = '';
    /**
     * Generated from protobuf field <code>string state = 5;</code>
     */
    protected $state = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $website_id
     *     @type string $code
     *     @type string $access_token
     *     @type string $auth_url
     *     @type string $state
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Settings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string website_id = 1;</code>
     * @return string
     */
    public function getWebsiteId()
    {
        return $this->website_id;
    }

    /**
     * Generated from protobuf field <code>string website_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWebsiteId($var)
    {
        GPBUtil::checkString($var, True);
        $this->website_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_token = 3;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     * Generated from protobuf field <code>string access_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string auth_url = 4;</code>
     * @return string
     */
    public function getAuthUrl()
    {
        return $this->auth_url;
    }

    /**
     * Generated from protobuf field <code>string auth_url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string state = 5;</code>
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>string state = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkString($var, True);
        $this->state = $var;

        return $this;
    }

}

