// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package countries

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CountriesClient is the client API for Countries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CountriesClient interface {
	GetCountries(ctx context.Context, in *CountriesEmptyRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCountry(ctx context.Context, in *CountryRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type countriesClient struct {
	cc grpc.ClientConnInterface
}

func NewCountriesClient(cc grpc.ClientConnInterface) CountriesClient {
	return &countriesClient{cc}
}

func (c *countriesClient) GetCountries(ctx context.Context, in *CountriesEmptyRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.countries.Countries/GetCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countriesClient) GetCountry(ctx context.Context, in *CountryRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.countries.Countries/GetCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountriesServer is the server API for Countries service.
// All implementations must embed UnimplementedCountriesServer
// for forward compatibility
type CountriesServer interface {
	GetCountries(context.Context, *CountriesEmptyRequest) (*ResultResponse, error)
	GetCountry(context.Context, *CountryRequest) (*ResultResponse, error)
	mustEmbedUnimplementedCountriesServer()
}

// UnimplementedCountriesServer must be embedded to have forward compatible implementations.
type UnimplementedCountriesServer struct {
}

func (UnimplementedCountriesServer) GetCountries(context.Context, *CountriesEmptyRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountries not implemented")
}
func (UnimplementedCountriesServer) GetCountry(context.Context, *CountryRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountry not implemented")
}
func (UnimplementedCountriesServer) mustEmbedUnimplementedCountriesServer() {}

// UnsafeCountriesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CountriesServer will
// result in compilation errors.
type UnsafeCountriesServer interface {
	mustEmbedUnimplementedCountriesServer()
}

func RegisterCountriesServer(s grpc.ServiceRegistrar, srv CountriesServer) {
	s.RegisterService(&Countries_ServiceDesc, srv)
}

func _Countries_GetCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountriesEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountriesServer).GetCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.countries.Countries/GetCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountriesServer).GetCountries(ctx, req.(*CountriesEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Countries_GetCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountriesServer).GetCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.countries.Countries/GetCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountriesServer).GetCountry(ctx, req.(*CountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Countries_ServiceDesc is the grpc.ServiceDesc for Countries service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Countries_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.countries.Countries",
	HandlerType: (*CountriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCountries",
			Handler:    _Countries_GetCountries_Handler,
		},
		{
			MethodName: "GetCountry",
			Handler:    _Countries_GetCountry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "countries.proto",
}
