// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package coupons

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CouponsClient is the client API for Coupons service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponsClient interface {
	CouponSearch(ctx context.Context, in *CouponRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GenerateCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	UpdateCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ApplyOrderModule(ctx context.Context, in *ApplyOrderModuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ProcessModule(ctx context.Context, in *ApplyOrderModuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	CreateCouponRule(ctx context.Context, in *CouponRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteCouponRule(ctx context.Context, in *CouponRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCouponListing(ctx context.Context, in *CouponListing, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCouponRule(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultResponse, error)
}

type couponsClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponsClient(cc grpc.ClientConnInterface) CouponsClient {
	return &couponsClient{cc}
}

func (c *couponsClient) CouponSearch(ctx context.Context, in *CouponRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/CouponSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) GetCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/GetCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) GenerateCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/GenerateCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) UpdateCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/UpdateCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) DeleteCoupon(ctx context.Context, in *CouponRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/DeleteCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) ApplyOrderModule(ctx context.Context, in *ApplyOrderModuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/ApplyOrderModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) ProcessModule(ctx context.Context, in *ApplyOrderModuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/ProcessModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) CreateCouponRule(ctx context.Context, in *CouponRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/CreateCouponRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) DeleteCouponRule(ctx context.Context, in *CouponRuleRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/DeleteCouponRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) GetCouponListing(ctx context.Context, in *CouponListing, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/GetCouponListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponsClient) GetCouponRule(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.coupons.Coupons/GetCouponRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponsServer is the server API for Coupons service.
// All implementations must embed UnimplementedCouponsServer
// for forward compatibility
type CouponsServer interface {
	CouponSearch(context.Context, *CouponRuleRequest) (*ResultResponse, error)
	GetCoupon(context.Context, *CouponRequest) (*ResultResponse, error)
	GenerateCoupon(context.Context, *CouponRequest) (*ResultResponse, error)
	UpdateCoupon(context.Context, *CouponRequest) (*ResultResponse, error)
	DeleteCoupon(context.Context, *CouponRequest) (*ResultResponse, error)
	ApplyOrderModule(context.Context, *ApplyOrderModuleRequest) (*ResultResponse, error)
	ProcessModule(context.Context, *ApplyOrderModuleRequest) (*ResultResponse, error)
	CreateCouponRule(context.Context, *CouponRuleRequest) (*ResultResponse, error)
	DeleteCouponRule(context.Context, *CouponRuleRequest) (*ResultResponse, error)
	GetCouponListing(context.Context, *CouponListing) (*ResultResponse, error)
	GetCouponRule(context.Context, *emptypb.Empty) (*ResultResponse, error)
	mustEmbedUnimplementedCouponsServer()
}

// UnimplementedCouponsServer must be embedded to have forward compatible implementations.
type UnimplementedCouponsServer struct {
}

func (UnimplementedCouponsServer) CouponSearch(context.Context, *CouponRuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponSearch not implemented")
}
func (UnimplementedCouponsServer) GetCoupon(context.Context, *CouponRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoupon not implemented")
}
func (UnimplementedCouponsServer) GenerateCoupon(context.Context, *CouponRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCoupon not implemented")
}
func (UnimplementedCouponsServer) UpdateCoupon(context.Context, *CouponRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCoupon not implemented")
}
func (UnimplementedCouponsServer) DeleteCoupon(context.Context, *CouponRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCoupon not implemented")
}
func (UnimplementedCouponsServer) ApplyOrderModule(context.Context, *ApplyOrderModuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyOrderModule not implemented")
}
func (UnimplementedCouponsServer) ProcessModule(context.Context, *ApplyOrderModuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessModule not implemented")
}
func (UnimplementedCouponsServer) CreateCouponRule(context.Context, *CouponRuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCouponRule not implemented")
}
func (UnimplementedCouponsServer) DeleteCouponRule(context.Context, *CouponRuleRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCouponRule not implemented")
}
func (UnimplementedCouponsServer) GetCouponListing(context.Context, *CouponListing) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCouponListing not implemented")
}
func (UnimplementedCouponsServer) GetCouponRule(context.Context, *emptypb.Empty) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCouponRule not implemented")
}
func (UnimplementedCouponsServer) mustEmbedUnimplementedCouponsServer() {}

// UnsafeCouponsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponsServer will
// result in compilation errors.
type UnsafeCouponsServer interface {
	mustEmbedUnimplementedCouponsServer()
}

func RegisterCouponsServer(s grpc.ServiceRegistrar, srv CouponsServer) {
	s.RegisterService(&Coupons_ServiceDesc, srv)
}

func _Coupons_CouponSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).CouponSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/CouponSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).CouponSearch(ctx, req.(*CouponRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_GetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).GetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/GetCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).GetCoupon(ctx, req.(*CouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_GenerateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).GenerateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/GenerateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).GenerateCoupon(ctx, req.(*CouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_UpdateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).UpdateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/UpdateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).UpdateCoupon(ctx, req.(*CouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_DeleteCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).DeleteCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/DeleteCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).DeleteCoupon(ctx, req.(*CouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_ApplyOrderModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyOrderModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).ApplyOrderModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/ApplyOrderModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).ApplyOrderModule(ctx, req.(*ApplyOrderModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_ProcessModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyOrderModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).ProcessModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/ProcessModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).ProcessModule(ctx, req.(*ApplyOrderModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_CreateCouponRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).CreateCouponRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/CreateCouponRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).CreateCouponRule(ctx, req.(*CouponRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_DeleteCouponRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).DeleteCouponRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/DeleteCouponRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).DeleteCouponRule(ctx, req.(*CouponRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_GetCouponListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponListing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).GetCouponListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/GetCouponListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).GetCouponListing(ctx, req.(*CouponListing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupons_GetCouponRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponsServer).GetCouponRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.coupons.Coupons/GetCouponRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponsServer).GetCouponRule(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Coupons_ServiceDesc is the grpc.ServiceDesc for Coupons service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coupons_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.coupons.Coupons",
	HandlerType: (*CouponsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CouponSearch",
			Handler:    _Coupons_CouponSearch_Handler,
		},
		{
			MethodName: "GetCoupon",
			Handler:    _Coupons_GetCoupon_Handler,
		},
		{
			MethodName: "GenerateCoupon",
			Handler:    _Coupons_GenerateCoupon_Handler,
		},
		{
			MethodName: "UpdateCoupon",
			Handler:    _Coupons_UpdateCoupon_Handler,
		},
		{
			MethodName: "DeleteCoupon",
			Handler:    _Coupons_DeleteCoupon_Handler,
		},
		{
			MethodName: "ApplyOrderModule",
			Handler:    _Coupons_ApplyOrderModule_Handler,
		},
		{
			MethodName: "ProcessModule",
			Handler:    _Coupons_ProcessModule_Handler,
		},
		{
			MethodName: "CreateCouponRule",
			Handler:    _Coupons_CreateCouponRule_Handler,
		},
		{
			MethodName: "DeleteCouponRule",
			Handler:    _Coupons_DeleteCouponRule_Handler,
		},
		{
			MethodName: "GetCouponListing",
			Handler:    _Coupons_GetCouponListing_Handler,
		},
		{
			MethodName: "GetCouponRule",
			Handler:    _Coupons_GetCouponRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupons.proto",
}
