<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: money.proto

namespace Lexmodo\V1\Money;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.money.CurrencyCountry</code>
 */
class CurrencyCountry
{
    /**
     * Generated from protobuf enum <code>UNITED_STATES_DOLLAR = 0;</code>
     */
    const UNITED_STATES_DOLLAR = 0;
    /**
     * Generated from protobuf enum <code>AFGHAN_AFGHANI = 1;</code>
     */
    const AFGHAN_AFGHANI = 1;
    /**
     * Generated from protobuf enum <code>ALBANIAN_LEK = 2;</code>
     */
    const ALBANIAN_LEK = 2;
    /**
     * Generated from protobuf enum <code>ARMENIAN_DRAM = 3;</code>
     */
    const ARMENIAN_DRAM = 3;
    /**
     * Generated from protobuf enum <code>NETHERLANDS_ANTILLEAN_GUILDER = 4;</code>
     */
    const NETHERLANDS_ANTILLEAN_GUILDER = 4;
    /**
     * Generated from protobuf enum <code>ANGOLAN_KWANZA = 5;</code>
     */
    const ANGOLAN_KWANZA = 5;
    /**
     * Generated from protobuf enum <code>ARGENTINE_PESO = 6;</code>
     */
    const ARGENTINE_PESO = 6;
    /**
     * Generated from protobuf enum <code>AUSTRALIAN_DOLLAR = 7;</code>
     */
    const AUSTRALIAN_DOLLAR = 7;
    /**
     * Generated from protobuf enum <code>ARUBAN_FLORIN = 8;</code>
     */
    const ARUBAN_FLORIN = 8;
    /**
     * Generated from protobuf enum <code>AZERBAIJANI_MANAT = 9;</code>
     */
    const AZERBAIJANI_MANAT = 9;
    /**
     * Generated from protobuf enum <code>BOSNIA_HERZEGOVINA_CONVERTIBLE_MARK = 10;</code>
     */
    const BOSNIA_HERZEGOVINA_CONVERTIBLE_MARK = 10;
    /**
     * Generated from protobuf enum <code>BARBADIAN_DOLLAR = 11;</code>
     */
    const BARBADIAN_DOLLAR = 11;
    /**
     * Generated from protobuf enum <code>BANGLADESHI_TAKA = 12;</code>
     */
    const BANGLADESHI_TAKA = 12;
    /**
     * Generated from protobuf enum <code>BULGARIAN_LEV = 13;</code>
     */
    const BULGARIAN_LEV = 13;
    /**
     * Generated from protobuf enum <code>BAHRAINI_DINAR = 14;</code>
     */
    const BAHRAINI_DINAR = 14;
    /**
     * Generated from protobuf enum <code>BURUNDIAN_FRANC = 15;</code>
     */
    const BURUNDIAN_FRANC = 15;
    /**
     * Generated from protobuf enum <code>BERMUDAN_DOLLAR = 16;</code>
     */
    const BERMUDAN_DOLLAR = 16;
    /**
     * Generated from protobuf enum <code>BRUNEI_DOLLAR = 17;</code>
     */
    const BRUNEI_DOLLAR = 17;
    /**
     * Generated from protobuf enum <code>BOLIVIAN_BOLIVIANO = 18;</code>
     */
    const BOLIVIAN_BOLIVIANO = 18;
    /**
     * Generated from protobuf enum <code>BRAZILIAN_REAL = 19;</code>
     */
    const BRAZILIAN_REAL = 19;
    /**
     * Generated from protobuf enum <code>BAHAMIAN_DOLLAR = 20;</code>
     */
    const BAHAMIAN_DOLLAR = 20;
    /**
     * Generated from protobuf enum <code>BITCOIN = 21;</code>
     */
    const BITCOIN = 21;
    /**
     * Generated from protobuf enum <code>BHUTANESE_NGULTRUM = 22;</code>
     */
    const BHUTANESE_NGULTRUM = 22;
    /**
     * Generated from protobuf enum <code>BOTSWANAN_PULA = 23;</code>
     */
    const BOTSWANAN_PULA = 23;
    /**
     * Generated from protobuf enum <code>BELARUSIAN_RUBLE = 24;</code>
     */
    const BELARUSIAN_RUBLE = 24;
    /**
     * Generated from protobuf enum <code>BELIZE_DOLLAR = 25;</code>
     */
    const BELIZE_DOLLAR = 25;
    /**
     * Generated from protobuf enum <code>CANADIAN_DOLLAR = 26;</code>
     */
    const CANADIAN_DOLLAR = 26;
    /**
     * Generated from protobuf enum <code>CONGOLESE_FRANC = 27;</code>
     */
    const CONGOLESE_FRANC = 27;
    /**
     * Generated from protobuf enum <code>SWISS_FRANC = 28;</code>
     */
    const SWISS_FRANC = 28;
    /**
     * Generated from protobuf enum <code>CHILEAN_UNIT_OF_ACCOUNT_UF = 29;</code>
     */
    const CHILEAN_UNIT_OF_ACCOUNT_UF = 29;
    /**
     * Generated from protobuf enum <code>CHILEAN_PESO = 30;</code>
     */
    const CHILEAN_PESO = 30;
    /**
     * Generated from protobuf enum <code>CHINESE_YUAN_OFFSHORE = 31;</code>
     */
    const CHINESE_YUAN_OFFSHORE = 31;
    /**
     * Generated from protobuf enum <code>CHINESE_YUAN = 32;</code>
     */
    const CHINESE_YUAN = 32;
    /**
     * Generated from protobuf enum <code>COLOMBIAN_PESO = 33;</code>
     */
    const COLOMBIAN_PESO = 33;
    /**
     * Generated from protobuf enum <code>COSTA_RICAN_COLON = 34;</code>
     */
    const COSTA_RICAN_COLON = 34;
    /**
     * Generated from protobuf enum <code>CUBAN_CONVERTIBLE_PESO = 35;</code>
     */
    const CUBAN_CONVERTIBLE_PESO = 35;
    /**
     * Generated from protobuf enum <code>CUBAN_PESO = 36;</code>
     */
    const CUBAN_PESO = 36;
    /**
     * Generated from protobuf enum <code>CAPE_VERDEAN_ESCUDO = 37;</code>
     */
    const CAPE_VERDEAN_ESCUDO = 37;
    /**
     * Generated from protobuf enum <code>CZECH_REPUBLIC_KORUNA = 38;</code>
     */
    const CZECH_REPUBLIC_KORUNA = 38;
    /**
     * Generated from protobuf enum <code>DJIBOUTIAN_FRANC = 39;</code>
     */
    const DJIBOUTIAN_FRANC = 39;
    /**
     * Generated from protobuf enum <code>DANISH_KRONE = 40;</code>
     */
    const DANISH_KRONE = 40;
    /**
     * Generated from protobuf enum <code>DOMINICAN_PESO = 41;</code>
     */
    const DOMINICAN_PESO = 41;
    /**
     * Generated from protobuf enum <code>ALGERIAN_DINAR = 42;</code>
     */
    const ALGERIAN_DINAR = 42;
    /**
     * Generated from protobuf enum <code>EGYPTIAN_POUND = 43;</code>
     */
    const EGYPTIAN_POUND = 43;
    /**
     * Generated from protobuf enum <code>ERITREAN_NAKFA = 44;</code>
     */
    const ERITREAN_NAKFA = 44;
    /**
     * Generated from protobuf enum <code>ETHIOPIAN_BIRR = 45;</code>
     */
    const ETHIOPIAN_BIRR = 45;
    /**
     * Generated from protobuf enum <code>EURO = 46;</code>
     */
    const EURO = 46;
    /**
     * Generated from protobuf enum <code>FIJIAN_DOLLAR = 47;</code>
     */
    const FIJIAN_DOLLAR = 47;
    /**
     * Generated from protobuf enum <code>FALKLAND_ISLANDS_POUND = 48;</code>
     */
    const FALKLAND_ISLANDS_POUND = 48;
    /**
     * Generated from protobuf enum <code>BRITISH_POUND_STERLING = 49;</code>
     */
    const BRITISH_POUND_STERLING = 49;
    /**
     * Generated from protobuf enum <code>GEORGIAN_LARI = 50;</code>
     */
    const GEORGIAN_LARI = 50;
    /**
     * Generated from protobuf enum <code>GUERNSEY_POUND = 51;</code>
     */
    const GUERNSEY_POUND = 51;
    /**
     * Generated from protobuf enum <code>GHANAIAN_CEDI = 52;</code>
     */
    const GHANAIAN_CEDI = 52;
    /**
     * Generated from protobuf enum <code>GIBRALTAR_POUND = 53;</code>
     */
    const GIBRALTAR_POUND = 53;
    /**
     * Generated from protobuf enum <code>GAMBIAN_DALASI = 54;</code>
     */
    const GAMBIAN_DALASI = 54;
    /**
     * Generated from protobuf enum <code>GUINEAN_FRANC = 55;</code>
     */
    const GUINEAN_FRANC = 55;
    /**
     * Generated from protobuf enum <code>GUATEMALAN_QUETZAL = 56;</code>
     */
    const GUATEMALAN_QUETZAL = 56;
    /**
     * Generated from protobuf enum <code>GUYANAESE_DOLLAR = 57;</code>
     */
    const GUYANAESE_DOLLAR = 57;
    /**
     * Generated from protobuf enum <code>HONG_KONG_DOLLAR = 58;</code>
     */
    const HONG_KONG_DOLLAR = 58;
    /**
     * Generated from protobuf enum <code>HONDURAN_LEMPIRA = 59;</code>
     */
    const HONDURAN_LEMPIRA = 59;
    /**
     * Generated from protobuf enum <code>CROATIAN_KUNA = 60;</code>
     */
    const CROATIAN_KUNA = 60;
    /**
     * Generated from protobuf enum <code>HAITIAN_GOURDE = 61;</code>
     */
    const HAITIAN_GOURDE = 61;
    /**
     * Generated from protobuf enum <code>HUNGARIAN_FORINT = 62;</code>
     */
    const HUNGARIAN_FORINT = 62;
    /**
     * Generated from protobuf enum <code>INDONESIAN_RUPIAH = 63;</code>
     */
    const INDONESIAN_RUPIAH = 63;
    /**
     * Generated from protobuf enum <code>ISRAELI_NEW_SHEQEL = 64;</code>
     */
    const ISRAELI_NEW_SHEQEL = 64;
    /**
     * Generated from protobuf enum <code>MANX_POUND = 65;</code>
     */
    const MANX_POUND = 65;
    /**
     * Generated from protobuf enum <code>INDIAN_RUPEE = 66;</code>
     */
    const INDIAN_RUPEE = 66;
    /**
     * Generated from protobuf enum <code>IRAQI_DINAR = 67;</code>
     */
    const IRAQI_DINAR = 67;
    /**
     * Generated from protobuf enum <code>IRANIAN_RIAL = 68;</code>
     */
    const IRANIAN_RIAL = 68;
    /**
     * Generated from protobuf enum <code>ICELANDIC_KRONA = 69;</code>
     */
    const ICELANDIC_KRONA = 69;
    /**
     * Generated from protobuf enum <code>JERSEY_POUND = 70;</code>
     */
    const JERSEY_POUND = 70;
    /**
     * Generated from protobuf enum <code>JAMAICAN_DOLLAR = 71;</code>
     */
    const JAMAICAN_DOLLAR = 71;
    /**
     * Generated from protobuf enum <code>JORDANIAN_DINAR = 72;</code>
     */
    const JORDANIAN_DINAR = 72;
    /**
     * Generated from protobuf enum <code>JAPANESE_YEN = 73;</code>
     */
    const JAPANESE_YEN = 73;
    /**
     * Generated from protobuf enum <code>KENYAN_SHILLING = 74;</code>
     */
    const KENYAN_SHILLING = 74;
    /**
     * Generated from protobuf enum <code>KYRGYSTANI_SOM = 75;</code>
     */
    const KYRGYSTANI_SOM = 75;
    /**
     * Generated from protobuf enum <code>CAMBODIAN_RIEL = 76;</code>
     */
    const CAMBODIAN_RIEL = 76;
    /**
     * Generated from protobuf enum <code>COMORIAN_FRANC = 77;</code>
     */
    const COMORIAN_FRANC = 77;
    /**
     * Generated from protobuf enum <code>NORTH_KOREAN_WON = 78;</code>
     */
    const NORTH_KOREAN_WON = 78;
    /**
     * Generated from protobuf enum <code>SOUTH_KOREAN_WON = 79;</code>
     */
    const SOUTH_KOREAN_WON = 79;
    /**
     * Generated from protobuf enum <code>KUWAITI_DINAR = 80;</code>
     */
    const KUWAITI_DINAR = 80;
    /**
     * Generated from protobuf enum <code>CAYMAN_ISLANDS_DOLLAR = 81;</code>
     */
    const CAYMAN_ISLANDS_DOLLAR = 81;
    /**
     * Generated from protobuf enum <code>KAZAKHSTANI_TENGE = 82;</code>
     */
    const KAZAKHSTANI_TENGE = 82;
    /**
     * Generated from protobuf enum <code>LAOTIAN_KIP = 83;</code>
     */
    const LAOTIAN_KIP = 83;
    /**
     * Generated from protobuf enum <code>LEBANESE_POUND = 84;</code>
     */
    const LEBANESE_POUND = 84;
    /**
     * Generated from protobuf enum <code>SRI_LANKAN_RUPEE = 85;</code>
     */
    const SRI_LANKAN_RUPEE = 85;
    /**
     * Generated from protobuf enum <code>LIBERIAN_DOLLAR = 86;</code>
     */
    const LIBERIAN_DOLLAR = 86;
    /**
     * Generated from protobuf enum <code>LESOTHO_LOTI = 87;</code>
     */
    const LESOTHO_LOTI = 87;
    /**
     * Generated from protobuf enum <code>LIBYAN_DINAR = 88;</code>
     */
    const LIBYAN_DINAR = 88;
    /**
     * Generated from protobuf enum <code>MOROCCAN_DIRHAM = 89;</code>
     */
    const MOROCCAN_DIRHAM = 89;
    /**
     * Generated from protobuf enum <code>MOLDOVAN_LEU = 90;</code>
     */
    const MOLDOVAN_LEU = 90;
    /**
     * Generated from protobuf enum <code>MALAGASY_ARIARY = 91;</code>
     */
    const MALAGASY_ARIARY = 91;
    /**
     * Generated from protobuf enum <code>MACEDONIAN_DENAR = 92;</code>
     */
    const MACEDONIAN_DENAR = 92;
    /**
     * Generated from protobuf enum <code>MYANMA_KYAT = 93;</code>
     */
    const MYANMA_KYAT = 93;
    /**
     * Generated from protobuf enum <code>MONGOLIAN_TUGRIK = 94;</code>
     */
    const MONGOLIAN_TUGRIK = 94;
    /**
     * Generated from protobuf enum <code>MACANESE_PATACA = 95;</code>
     */
    const MACANESE_PATACA = 95;
    /**
     * Generated from protobuf enum <code>MAURITANIAN_OUGUIYA_PRE_2018 = 96;</code>
     */
    const MAURITANIAN_OUGUIYA_PRE_2018 = 96;
    /**
     * Generated from protobuf enum <code>MAURITANIAN_OUGUIYA = 97;</code>
     */
    const MAURITANIAN_OUGUIYA = 97;
    /**
     * Generated from protobuf enum <code>MAURITIAN_RUPEE = 98;</code>
     */
    const MAURITIAN_RUPEE = 98;
    /**
     * Generated from protobuf enum <code>MALDIVIAN_RUFIYAA = 99;</code>
     */
    const MALDIVIAN_RUFIYAA = 99;
    /**
     * Generated from protobuf enum <code>MALAWIAN_KWACHA = 100;</code>
     */
    const MALAWIAN_KWACHA = 100;
    /**
     * Generated from protobuf enum <code>MEXICAN_PESO = 101;</code>
     */
    const MEXICAN_PESO = 101;
    /**
     * Generated from protobuf enum <code>MALAYSIAN_RINGGIT = 102;</code>
     */
    const MALAYSIAN_RINGGIT = 102;
    /**
     * Generated from protobuf enum <code>MOZAMBICAN_METICAL = 103;</code>
     */
    const MOZAMBICAN_METICAL = 103;
    /**
     * Generated from protobuf enum <code>NAMIBIAN_DOLLAR = 104;</code>
     */
    const NAMIBIAN_DOLLAR = 104;
    /**
     * Generated from protobuf enum <code>NIGERIAN_NAIRA = 105;</code>
     */
    const NIGERIAN_NAIRA = 105;
    /**
     * Generated from protobuf enum <code>NICARAGUAN_CORDOBA = 106;</code>
     */
    const NICARAGUAN_CORDOBA = 106;
    /**
     * Generated from protobuf enum <code>NORWEGIAN_KRONE = 107;</code>
     */
    const NORWEGIAN_KRONE = 107;
    /**
     * Generated from protobuf enum <code>NEPALESE_RUPEE = 108;</code>
     */
    const NEPALESE_RUPEE = 108;
    /**
     * Generated from protobuf enum <code>NEW_ZEALAND_DOLLAR = 109;</code>
     */
    const NEW_ZEALAND_DOLLAR = 109;
    /**
     * Generated from protobuf enum <code>OMANI_RIAL = 110;</code>
     */
    const OMANI_RIAL = 110;
    /**
     * Generated from protobuf enum <code>PANAMANIAN_BALBOA = 111;</code>
     */
    const PANAMANIAN_BALBOA = 111;
    /**
     * Generated from protobuf enum <code>PERUVIAN_NUEVO_SOL = 112;</code>
     */
    const PERUVIAN_NUEVO_SOL = 112;
    /**
     * Generated from protobuf enum <code>PAPUA_NEW_GUINEAN_KINA = 113;</code>
     */
    const PAPUA_NEW_GUINEAN_KINA = 113;
    /**
     * Generated from protobuf enum <code>PHILIPPINE_PESO = 114;</code>
     */
    const PHILIPPINE_PESO = 114;
    /**
     * Generated from protobuf enum <code>PAKISTANI_RUPEE = 115;</code>
     */
    const PAKISTANI_RUPEE = 115;
    /**
     * Generated from protobuf enum <code>POLISH_ZLOTY = 116;</code>
     */
    const POLISH_ZLOTY = 116;
    /**
     * Generated from protobuf enum <code>PARAGUAYAN_GUARANI = 117;</code>
     */
    const PARAGUAYAN_GUARANI = 117;
    /**
     * Generated from protobuf enum <code>QATARI_RIAL = 118;</code>
     */
    const QATARI_RIAL = 118;
    /**
     * Generated from protobuf enum <code>ROMANIAN_LEU = 119;</code>
     */
    const ROMANIAN_LEU = 119;
    /**
     * Generated from protobuf enum <code>SERBIAN_DINAR = 120;</code>
     */
    const SERBIAN_DINAR = 120;
    /**
     * Generated from protobuf enum <code>RUSSIAN_RUBLE = 121;</code>
     */
    const RUSSIAN_RUBLE = 121;
    /**
     * Generated from protobuf enum <code>RWANDAN_FRANC = 122;</code>
     */
    const RWANDAN_FRANC = 122;
    /**
     * Generated from protobuf enum <code>SAUDI_RIYAL = 123;</code>
     */
    const SAUDI_RIYAL = 123;
    /**
     * Generated from protobuf enum <code>SOLOMON_ISLANDS_DOLLAR = 124;</code>
     */
    const SOLOMON_ISLANDS_DOLLAR = 124;
    /**
     * Generated from protobuf enum <code>SEYCHELLOIS_RUPEE = 125;</code>
     */
    const SEYCHELLOIS_RUPEE = 125;
    /**
     * Generated from protobuf enum <code>SUDANESE_POUND = 126;</code>
     */
    const SUDANESE_POUND = 126;
    /**
     * Generated from protobuf enum <code>SWEDISH_KRONA = 127;</code>
     */
    const SWEDISH_KRONA = 127;
    /**
     * Generated from protobuf enum <code>SINGAPORE_DOLLAR = 128;</code>
     */
    const SINGAPORE_DOLLAR = 128;
    /**
     * Generated from protobuf enum <code>SAINT_HELENA_POUND = 129;</code>
     */
    const SAINT_HELENA_POUND = 129;
    /**
     * Generated from protobuf enum <code>SIERRA_LEONEAN_LEONE = 130;</code>
     */
    const SIERRA_LEONEAN_LEONE = 130;
    /**
     * Generated from protobuf enum <code>SOMALI_SHILLING = 131;</code>
     */
    const SOMALI_SHILLING = 131;
    /**
     * Generated from protobuf enum <code>SURINAMESE_DOLLAR = 132;</code>
     */
    const SURINAMESE_DOLLAR = 132;
    /**
     * Generated from protobuf enum <code>SOUTH_SUDANESE_POUND = 133;</code>
     */
    const SOUTH_SUDANESE_POUND = 133;
    /**
     * Generated from protobuf enum <code>SAO_TOME_AND_PRINCIPE_DOBRA_PRE_2018 = 134;</code>
     */
    const SAO_TOME_AND_PRINCIPE_DOBRA_PRE_2018 = 134;
    /**
     * Generated from protobuf enum <code>SAO_TOME_AND_PRINCIPE_DOBRA = 135;</code>
     */
    const SAO_TOME_AND_PRINCIPE_DOBRA = 135;
    /**
     * Generated from protobuf enum <code>SALVADORAN_COLON = 136;</code>
     */
    const SALVADORAN_COLON = 136;
    /**
     * Generated from protobuf enum <code>SYRIAN_POUND = 137;</code>
     */
    const SYRIAN_POUND = 137;
    /**
     * Generated from protobuf enum <code>SWAZI_LILANGENI = 138;</code>
     */
    const SWAZI_LILANGENI = 138;
    /**
     * Generated from protobuf enum <code>THAI_BAHT = 139;</code>
     */
    const THAI_BAHT = 139;
    /**
     * Generated from protobuf enum <code>TAJIKISTANI_SOMONI = 140;</code>
     */
    const TAJIKISTANI_SOMONI = 140;
    /**
     * Generated from protobuf enum <code>TURKMENISTANI_MANAT = 141;</code>
     */
    const TURKMENISTANI_MANAT = 141;
    /**
     * Generated from protobuf enum <code>TUNISIAN_DINAR = 142;</code>
     */
    const TUNISIAN_DINAR = 142;
    /**
     * Generated from protobuf enum <code>TONGAN_PAANGA = 143;</code>
     */
    const TONGAN_PAANGA = 143;
    /**
     * Generated from protobuf enum <code>TURKISH_LIRA = 144;</code>
     */
    const TURKISH_LIRA = 144;
    /**
     * Generated from protobuf enum <code>TRINIDAD_AND_TOBAGO_DOLLAR = 145;</code>
     */
    const TRINIDAD_AND_TOBAGO_DOLLAR = 145;
    /**
     * Generated from protobuf enum <code>NEW_TAIWAN_DOLLAR = 146;</code>
     */
    const NEW_TAIWAN_DOLLAR = 146;
    /**
     * Generated from protobuf enum <code>TANZANIAN_SHILLING = 147;</code>
     */
    const TANZANIAN_SHILLING = 147;
    /**
     * Generated from protobuf enum <code>UKRAINIAN_HRYVNIA = 148;</code>
     */
    const UKRAINIAN_HRYVNIA = 148;
    /**
     * Generated from protobuf enum <code>UGANDAN_SHILLING = 149;</code>
     */
    const UGANDAN_SHILLING = 149;
    /**
     * Generated from protobuf enum <code>UNITED_ARAB_EMIRATES_DIRHAM = 150;</code>
     */
    const UNITED_ARAB_EMIRATES_DIRHAM = 150;
    /**
     * Generated from protobuf enum <code>URUGUAYAN_PESO = 151;</code>
     */
    const URUGUAYAN_PESO = 151;
    /**
     * Generated from protobuf enum <code>UZBEKISTAN_SOM = 152;</code>
     */
    const UZBEKISTAN_SOM = 152;
    /**
     * Generated from protobuf enum <code>VENEZUELAN_BOLIVAR_FUERTE = 153;</code>
     */
    const VENEZUELAN_BOLIVAR_FUERTE = 153;
    /**
     * Generated from protobuf enum <code>VIETNAMESE_DONG = 154;</code>
     */
    const VIETNAMESE_DONG = 154;
    /**
     * Generated from protobuf enum <code>VANUATU_VATU = 155;</code>
     */
    const VANUATU_VATU = 155;
    /**
     * Generated from protobuf enum <code>SAMOAN_TALA = 156;</code>
     */
    const SAMOAN_TALA = 156;
    /**
     * Generated from protobuf enum <code>CFA_FRANC_BEAC = 157;</code>
     */
    const CFA_FRANC_BEAC = 157;
    /**
     * Generated from protobuf enum <code>SILVER_OUNCE = 158;</code>
     */
    const SILVER_OUNCE = 158;
    /**
     * Generated from protobuf enum <code>GOLD_OUNCE = 159;</code>
     */
    const GOLD_OUNCE = 159;
    /**
     * Generated from protobuf enum <code>EAST_CARIBBEAN_DOLLAR = 160;</code>
     */
    const EAST_CARIBBEAN_DOLLAR = 160;
    /**
     * Generated from protobuf enum <code>SPECIAL_DRAWING_RIGHTS = 161;</code>
     */
    const SPECIAL_DRAWING_RIGHTS = 161;
    /**
     * Generated from protobuf enum <code>CFA_FRANC_BCEAO = 162;</code>
     */
    const CFA_FRANC_BCEAO = 162;
    /**
     * Generated from protobuf enum <code>PALLADIUM_OUNCE = 163;</code>
     */
    const PALLADIUM_OUNCE = 163;
    /**
     * Generated from protobuf enum <code>CFP_FRANC = 164;</code>
     */
    const CFP_FRANC = 164;
    /**
     * Generated from protobuf enum <code>PLATINUM_OUNCE = 165;</code>
     */
    const PLATINUM_OUNCE = 165;
    /**
     * Generated from protobuf enum <code>YEMENI_RIAL = 166;</code>
     */
    const YEMENI_RIAL = 166;
    /**
     * Generated from protobuf enum <code>SOUTH_AFRICAN_RAND = 167;</code>
     */
    const SOUTH_AFRICAN_RAND = 167;
    /**
     * Generated from protobuf enum <code>ZAMBIAN_KWACHA = 168;</code>
     */
    const ZAMBIAN_KWACHA = 168;
    /**
     * Generated from protobuf enum <code>ZIMBABWEAN_DOLLAR = 169;</code>
     */
    const ZIMBABWEAN_DOLLAR = 169;

    private static $valueToName = [
        self::UNITED_STATES_DOLLAR => 'UNITED_STATES_DOLLAR',
        self::AFGHAN_AFGHANI => 'AFGHAN_AFGHANI',
        self::ALBANIAN_LEK => 'ALBANIAN_LEK',
        self::ARMENIAN_DRAM => 'ARMENIAN_DRAM',
        self::NETHERLANDS_ANTILLEAN_GUILDER => 'NETHERLANDS_ANTILLEAN_GUILDER',
        self::ANGOLAN_KWANZA => 'ANGOLAN_KWANZA',
        self::ARGENTINE_PESO => 'ARGENTINE_PESO',
        self::AUSTRALIAN_DOLLAR => 'AUSTRALIAN_DOLLAR',
        self::ARUBAN_FLORIN => 'ARUBAN_FLORIN',
        self::AZERBAIJANI_MANAT => 'AZERBAIJANI_MANAT',
        self::BOSNIA_HERZEGOVINA_CONVERTIBLE_MARK => 'BOSNIA_HERZEGOVINA_CONVERTIBLE_MARK',
        self::BARBADIAN_DOLLAR => 'BARBADIAN_DOLLAR',
        self::BANGLADESHI_TAKA => 'BANGLADESHI_TAKA',
        self::BULGARIAN_LEV => 'BULGARIAN_LEV',
        self::BAHRAINI_DINAR => 'BAHRAINI_DINAR',
        self::BURUNDIAN_FRANC => 'BURUNDIAN_FRANC',
        self::BERMUDAN_DOLLAR => 'BERMUDAN_DOLLAR',
        self::BRUNEI_DOLLAR => 'BRUNEI_DOLLAR',
        self::BOLIVIAN_BOLIVIANO => 'BOLIVIAN_BOLIVIANO',
        self::BRAZILIAN_REAL => 'BRAZILIAN_REAL',
        self::BAHAMIAN_DOLLAR => 'BAHAMIAN_DOLLAR',
        self::BITCOIN => 'BITCOIN',
        self::BHUTANESE_NGULTRUM => 'BHUTANESE_NGULTRUM',
        self::BOTSWANAN_PULA => 'BOTSWANAN_PULA',
        self::BELARUSIAN_RUBLE => 'BELARUSIAN_RUBLE',
        self::BELIZE_DOLLAR => 'BELIZE_DOLLAR',
        self::CANADIAN_DOLLAR => 'CANADIAN_DOLLAR',
        self::CONGOLESE_FRANC => 'CONGOLESE_FRANC',
        self::SWISS_FRANC => 'SWISS_FRANC',
        self::CHILEAN_UNIT_OF_ACCOUNT_UF => 'CHILEAN_UNIT_OF_ACCOUNT_UF',
        self::CHILEAN_PESO => 'CHILEAN_PESO',
        self::CHINESE_YUAN_OFFSHORE => 'CHINESE_YUAN_OFFSHORE',
        self::CHINESE_YUAN => 'CHINESE_YUAN',
        self::COLOMBIAN_PESO => 'COLOMBIAN_PESO',
        self::COSTA_RICAN_COLON => 'COSTA_RICAN_COLON',
        self::CUBAN_CONVERTIBLE_PESO => 'CUBAN_CONVERTIBLE_PESO',
        self::CUBAN_PESO => 'CUBAN_PESO',
        self::CAPE_VERDEAN_ESCUDO => 'CAPE_VERDEAN_ESCUDO',
        self::CZECH_REPUBLIC_KORUNA => 'CZECH_REPUBLIC_KORUNA',
        self::DJIBOUTIAN_FRANC => 'DJIBOUTIAN_FRANC',
        self::DANISH_KRONE => 'DANISH_KRONE',
        self::DOMINICAN_PESO => 'DOMINICAN_PESO',
        self::ALGERIAN_DINAR => 'ALGERIAN_DINAR',
        self::EGYPTIAN_POUND => 'EGYPTIAN_POUND',
        self::ERITREAN_NAKFA => 'ERITREAN_NAKFA',
        self::ETHIOPIAN_BIRR => 'ETHIOPIAN_BIRR',
        self::EURO => 'EURO',
        self::FIJIAN_DOLLAR => 'FIJIAN_DOLLAR',
        self::FALKLAND_ISLANDS_POUND => 'FALKLAND_ISLANDS_POUND',
        self::BRITISH_POUND_STERLING => 'BRITISH_POUND_STERLING',
        self::GEORGIAN_LARI => 'GEORGIAN_LARI',
        self::GUERNSEY_POUND => 'GUERNSEY_POUND',
        self::GHANAIAN_CEDI => 'GHANAIAN_CEDI',
        self::GIBRALTAR_POUND => 'GIBRALTAR_POUND',
        self::GAMBIAN_DALASI => 'GAMBIAN_DALASI',
        self::GUINEAN_FRANC => 'GUINEAN_FRANC',
        self::GUATEMALAN_QUETZAL => 'GUATEMALAN_QUETZAL',
        self::GUYANAESE_DOLLAR => 'GUYANAESE_DOLLAR',
        self::HONG_KONG_DOLLAR => 'HONG_KONG_DOLLAR',
        self::HONDURAN_LEMPIRA => 'HONDURAN_LEMPIRA',
        self::CROATIAN_KUNA => 'CROATIAN_KUNA',
        self::HAITIAN_GOURDE => 'HAITIAN_GOURDE',
        self::HUNGARIAN_FORINT => 'HUNGARIAN_FORINT',
        self::INDONESIAN_RUPIAH => 'INDONESIAN_RUPIAH',
        self::ISRAELI_NEW_SHEQEL => 'ISRAELI_NEW_SHEQEL',
        self::MANX_POUND => 'MANX_POUND',
        self::INDIAN_RUPEE => 'INDIAN_RUPEE',
        self::IRAQI_DINAR => 'IRAQI_DINAR',
        self::IRANIAN_RIAL => 'IRANIAN_RIAL',
        self::ICELANDIC_KRONA => 'ICELANDIC_KRONA',
        self::JERSEY_POUND => 'JERSEY_POUND',
        self::JAMAICAN_DOLLAR => 'JAMAICAN_DOLLAR',
        self::JORDANIAN_DINAR => 'JORDANIAN_DINAR',
        self::JAPANESE_YEN => 'JAPANESE_YEN',
        self::KENYAN_SHILLING => 'KENYAN_SHILLING',
        self::KYRGYSTANI_SOM => 'KYRGYSTANI_SOM',
        self::CAMBODIAN_RIEL => 'CAMBODIAN_RIEL',
        self::COMORIAN_FRANC => 'COMORIAN_FRANC',
        self::NORTH_KOREAN_WON => 'NORTH_KOREAN_WON',
        self::SOUTH_KOREAN_WON => 'SOUTH_KOREAN_WON',
        self::KUWAITI_DINAR => 'KUWAITI_DINAR',
        self::CAYMAN_ISLANDS_DOLLAR => 'CAYMAN_ISLANDS_DOLLAR',
        self::KAZAKHSTANI_TENGE => 'KAZAKHSTANI_TENGE',
        self::LAOTIAN_KIP => 'LAOTIAN_KIP',
        self::LEBANESE_POUND => 'LEBANESE_POUND',
        self::SRI_LANKAN_RUPEE => 'SRI_LANKAN_RUPEE',
        self::LIBERIAN_DOLLAR => 'LIBERIAN_DOLLAR',
        self::LESOTHO_LOTI => 'LESOTHO_LOTI',
        self::LIBYAN_DINAR => 'LIBYAN_DINAR',
        self::MOROCCAN_DIRHAM => 'MOROCCAN_DIRHAM',
        self::MOLDOVAN_LEU => 'MOLDOVAN_LEU',
        self::MALAGASY_ARIARY => 'MALAGASY_ARIARY',
        self::MACEDONIAN_DENAR => 'MACEDONIAN_DENAR',
        self::MYANMA_KYAT => 'MYANMA_KYAT',
        self::MONGOLIAN_TUGRIK => 'MONGOLIAN_TUGRIK',
        self::MACANESE_PATACA => 'MACANESE_PATACA',
        self::MAURITANIAN_OUGUIYA_PRE_2018 => 'MAURITANIAN_OUGUIYA_PRE_2018',
        self::MAURITANIAN_OUGUIYA => 'MAURITANIAN_OUGUIYA',
        self::MAURITIAN_RUPEE => 'MAURITIAN_RUPEE',
        self::MALDIVIAN_RUFIYAA => 'MALDIVIAN_RUFIYAA',
        self::MALAWIAN_KWACHA => 'MALAWIAN_KWACHA',
        self::MEXICAN_PESO => 'MEXICAN_PESO',
        self::MALAYSIAN_RINGGIT => 'MALAYSIAN_RINGGIT',
        self::MOZAMBICAN_METICAL => 'MOZAMBICAN_METICAL',
        self::NAMIBIAN_DOLLAR => 'NAMIBIAN_DOLLAR',
        self::NIGERIAN_NAIRA => 'NIGERIAN_NAIRA',
        self::NICARAGUAN_CORDOBA => 'NICARAGUAN_CORDOBA',
        self::NORWEGIAN_KRONE => 'NORWEGIAN_KRONE',
        self::NEPALESE_RUPEE => 'NEPALESE_RUPEE',
        self::NEW_ZEALAND_DOLLAR => 'NEW_ZEALAND_DOLLAR',
        self::OMANI_RIAL => 'OMANI_RIAL',
        self::PANAMANIAN_BALBOA => 'PANAMANIAN_BALBOA',
        self::PERUVIAN_NUEVO_SOL => 'PERUVIAN_NUEVO_SOL',
        self::PAPUA_NEW_GUINEAN_KINA => 'PAPUA_NEW_GUINEAN_KINA',
        self::PHILIPPINE_PESO => 'PHILIPPINE_PESO',
        self::PAKISTANI_RUPEE => 'PAKISTANI_RUPEE',
        self::POLISH_ZLOTY => 'POLISH_ZLOTY',
        self::PARAGUAYAN_GUARANI => 'PARAGUAYAN_GUARANI',
        self::QATARI_RIAL => 'QATARI_RIAL',
        self::ROMANIAN_LEU => 'ROMANIAN_LEU',
        self::SERBIAN_DINAR => 'SERBIAN_DINAR',
        self::RUSSIAN_RUBLE => 'RUSSIAN_RUBLE',
        self::RWANDAN_FRANC => 'RWANDAN_FRANC',
        self::SAUDI_RIYAL => 'SAUDI_RIYAL',
        self::SOLOMON_ISLANDS_DOLLAR => 'SOLOMON_ISLANDS_DOLLAR',
        self::SEYCHELLOIS_RUPEE => 'SEYCHELLOIS_RUPEE',
        self::SUDANESE_POUND => 'SUDANESE_POUND',
        self::SWEDISH_KRONA => 'SWEDISH_KRONA',
        self::SINGAPORE_DOLLAR => 'SINGAPORE_DOLLAR',
        self::SAINT_HELENA_POUND => 'SAINT_HELENA_POUND',
        self::SIERRA_LEONEAN_LEONE => 'SIERRA_LEONEAN_LEONE',
        self::SOMALI_SHILLING => 'SOMALI_SHILLING',
        self::SURINAMESE_DOLLAR => 'SURINAMESE_DOLLAR',
        self::SOUTH_SUDANESE_POUND => 'SOUTH_SUDANESE_POUND',
        self::SAO_TOME_AND_PRINCIPE_DOBRA_PRE_2018 => 'SAO_TOME_AND_PRINCIPE_DOBRA_PRE_2018',
        self::SAO_TOME_AND_PRINCIPE_DOBRA => 'SAO_TOME_AND_PRINCIPE_DOBRA',
        self::SALVADORAN_COLON => 'SALVADORAN_COLON',
        self::SYRIAN_POUND => 'SYRIAN_POUND',
        self::SWAZI_LILANGENI => 'SWAZI_LILANGENI',
        self::THAI_BAHT => 'THAI_BAHT',
        self::TAJIKISTANI_SOMONI => 'TAJIKISTANI_SOMONI',
        self::TURKMENISTANI_MANAT => 'TURKMENISTANI_MANAT',
        self::TUNISIAN_DINAR => 'TUNISIAN_DINAR',
        self::TONGAN_PAANGA => 'TONGAN_PAANGA',
        self::TURKISH_LIRA => 'TURKISH_LIRA',
        self::TRINIDAD_AND_TOBAGO_DOLLAR => 'TRINIDAD_AND_TOBAGO_DOLLAR',
        self::NEW_TAIWAN_DOLLAR => 'NEW_TAIWAN_DOLLAR',
        self::TANZANIAN_SHILLING => 'TANZANIAN_SHILLING',
        self::UKRAINIAN_HRYVNIA => 'UKRAINIAN_HRYVNIA',
        self::UGANDAN_SHILLING => 'UGANDAN_SHILLING',
        self::UNITED_ARAB_EMIRATES_DIRHAM => 'UNITED_ARAB_EMIRATES_DIRHAM',
        self::URUGUAYAN_PESO => 'URUGUAYAN_PESO',
        self::UZBEKISTAN_SOM => 'UZBEKISTAN_SOM',
        self::VENEZUELAN_BOLIVAR_FUERTE => 'VENEZUELAN_BOLIVAR_FUERTE',
        self::VIETNAMESE_DONG => 'VIETNAMESE_DONG',
        self::VANUATU_VATU => 'VANUATU_VATU',
        self::SAMOAN_TALA => 'SAMOAN_TALA',
        self::CFA_FRANC_BEAC => 'CFA_FRANC_BEAC',
        self::SILVER_OUNCE => 'SILVER_OUNCE',
        self::GOLD_OUNCE => 'GOLD_OUNCE',
        self::EAST_CARIBBEAN_DOLLAR => 'EAST_CARIBBEAN_DOLLAR',
        self::SPECIAL_DRAWING_RIGHTS => 'SPECIAL_DRAWING_RIGHTS',
        self::CFA_FRANC_BCEAO => 'CFA_FRANC_BCEAO',
        self::PALLADIUM_OUNCE => 'PALLADIUM_OUNCE',
        self::CFP_FRANC => 'CFP_FRANC',
        self::PLATINUM_OUNCE => 'PLATINUM_OUNCE',
        self::YEMENI_RIAL => 'YEMENI_RIAL',
        self::SOUTH_AFRICAN_RAND => 'SOUTH_AFRICAN_RAND',
        self::ZAMBIAN_KWACHA => 'ZAMBIAN_KWACHA',
        self::ZIMBABWEAN_DOLLAR => 'ZIMBABWEAN_DOLLAR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

