<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: money.proto

namespace Lexmodo\V1\Money;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.money.Money</code>
 */
class Money extends \Google\Protobuf\Internal\Message
{
    /**
     *$2.30
     *
     * Generated from protobuf field <code>string decimal = 1;</code>
     */
    protected $decimal = '';
    /**
     *USD
     *
     * Generated from protobuf field <code>string currency_code = 2;</code>
     */
    protected $currency_code = '';
    /**
     *$
     *
     * Generated from protobuf field <code>string symbol = 3;</code>
     */
    protected $symbol = '';
    /**
     *230
     *
     * Generated from protobuf field <code>uint32 amount = 4;</code>
     */
    protected $amount = 0;
    /**
     * -2.30 +2.30
     *
     * Generated from protobuf field <code>.lexmodo.v1.money.BINARY_OPERATOR binary_operator = 5;</code>
     */
    protected $binary_operator = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $decimal
     *          $2.30
     *     @type string $currency_code
     *          USD
     *     @type string $symbol
     *          $
     *     @type int $amount
     *          230
     *     @type int $binary_operator
     *           -2.30 +2.30
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Money::initOnce();
        parent::__construct($data);
    }

    /**
     *$2.30
     *
     * Generated from protobuf field <code>string decimal = 1;</code>
     * @return string
     */
    public function getDecimal()
    {
        return $this->decimal;
    }

    /**
     *$2.30
     *
     * Generated from protobuf field <code>string decimal = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDecimal($var)
    {
        GPBUtil::checkString($var, True);
        $this->decimal = $var;

        return $this;
    }

    /**
     *USD
     *
     * Generated from protobuf field <code>string currency_code = 2;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currency_code;
    }

    /**
     *USD
     *
     * Generated from protobuf field <code>string currency_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_code = $var;

        return $this;
    }

    /**
     *$
     *
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     *$
     *
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     *230
     *
     * Generated from protobuf field <code>uint32 amount = 4;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *230
     *
     * Generated from protobuf field <code>uint32 amount = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * -2.30 +2.30
     *
     * Generated from protobuf field <code>.lexmodo.v1.money.BINARY_OPERATOR binary_operator = 5;</code>
     * @return int
     */
    public function getBinaryOperator()
    {
        return $this->binary_operator;
    }

    /**
     * -2.30 +2.30
     *
     * Generated from protobuf field <code>.lexmodo.v1.money.BINARY_OPERATOR binary_operator = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBinaryOperator($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Money\BINARY_OPERATOR::class);
        $this->binary_operator = $var;

        return $this;
    }

}

