<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Lexmodo\V1\Products;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.products.LinkedFields</code>
 */
class LinkedFields extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field_name_key = 1;</code>
     */
    protected $field_name_key = '';
    /**
     * Generated from protobuf field <code>string field_value_key = 2;</code>
     */
    protected $field_value_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_name_key
     *     @type string $field_value_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field_name_key = 1;</code>
     * @return string
     */
    public function getFieldNameKey()
    {
        return $this->field_name_key;
    }

    /**
     * Generated from protobuf field <code>string field_name_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldNameKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string field_value_key = 2;</code>
     * @return string
     */
    public function getFieldValueKey()
    {
        return $this->field_value_key;
    }

    /**
     * Generated from protobuf field <code>string field_value_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldValueKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_value_key = $var;

        return $this;
    }

}

