<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Lexmodo\V1\Products;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.products.ProductVariantUpdateCustomFields</code>
 */
class ProductVariantUpdateCustomFields extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string product_id = 1;</code>
     */
    protected $product_id = '';
    /**
     * Generated from protobuf field <code>string variant_id = 2;</code>
     */
    protected $variant_id = '';
    /**
     * Generated from protobuf field <code>map<string, string> value = 3;</code>
     */
    private $value;
    /**
     * Generated from protobuf field <code>bool append_data = 4;</code>
     */
    protected $append_data = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $product_id
     *     @type string $variant_id
     *     @type array|\Google\Protobuf\Internal\MapField $value
     *     @type bool $append_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string product_id = 1;</code>
     * @return string
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Generated from protobuf field <code>string product_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string variant_id = 2;</code>
     * @return string
     */
    public function getVariantId()
    {
        return $this->variant_id;
    }

    /**
     * Generated from protobuf field <code>string variant_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVariantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> value = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>map<string, string> value = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setValue($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool append_data = 4;</code>
     * @return bool
     */
    public function getAppendData()
    {
        return $this->append_data;
    }

    /**
     * Generated from protobuf field <code>bool append_data = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAppendData($var)
    {
        GPBUtil::checkBool($var);
        $this->append_data = $var;

        return $this;
    }

}

