<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Lexmodo\V1\Products;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.products.QtyDiscount</code>
 */
class QtyDiscount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double variant_qty = 1;</code>
     */
    protected $variant_qty = 0.0;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_price = 2;</code>
     */
    protected $variant_price = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_discount_price = 3;</code>
     */
    protected $variant_discount_price = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_wholesale_price = 4;</code>
     */
    protected $variant_wholesale_price = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_wholesale_discount_price = 5;</code>
     */
    protected $variant_wholesale_discount_price = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue custom_rule = 6;</code>
     */
    protected $custom_rule = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue group_tag = 7;</code>
     */
    protected $group_tag = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $variant_qty
     *     @type \Lexmodo\V1\Money\Money $variant_price
     *     @type \Lexmodo\V1\Money\Money $variant_discount_price
     *     @type \Lexmodo\V1\Money\Money $variant_wholesale_price
     *     @type \Lexmodo\V1\Money\Money $variant_wholesale_discount_price
     *     @type \Google\Protobuf\StringValue $custom_rule
     *     @type \Google\Protobuf\StringValue $group_tag
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double variant_qty = 1;</code>
     * @return float
     */
    public function getVariantQty()
    {
        return $this->variant_qty;
    }

    /**
     * Generated from protobuf field <code>double variant_qty = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setVariantQty($var)
    {
        GPBUtil::checkDouble($var);
        $this->variant_qty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_price = 2;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getVariantPrice()
    {
        return isset($this->variant_price) ? $this->variant_price : null;
    }

    public function hasVariantPrice()
    {
        return isset($this->variant_price);
    }

    public function clearVariantPrice()
    {
        unset($this->variant_price);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_price = 2;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setVariantPrice($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->variant_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_discount_price = 3;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getVariantDiscountPrice()
    {
        return isset($this->variant_discount_price) ? $this->variant_discount_price : null;
    }

    public function hasVariantDiscountPrice()
    {
        return isset($this->variant_discount_price);
    }

    public function clearVariantDiscountPrice()
    {
        unset($this->variant_discount_price);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_discount_price = 3;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setVariantDiscountPrice($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->variant_discount_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_wholesale_price = 4;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getVariantWholesalePrice()
    {
        return isset($this->variant_wholesale_price) ? $this->variant_wholesale_price : null;
    }

    public function hasVariantWholesalePrice()
    {
        return isset($this->variant_wholesale_price);
    }

    public function clearVariantWholesalePrice()
    {
        unset($this->variant_wholesale_price);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_wholesale_price = 4;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setVariantWholesalePrice($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->variant_wholesale_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_wholesale_discount_price = 5;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getVariantWholesaleDiscountPrice()
    {
        return isset($this->variant_wholesale_discount_price) ? $this->variant_wholesale_discount_price : null;
    }

    public function hasVariantWholesaleDiscountPrice()
    {
        return isset($this->variant_wholesale_discount_price);
    }

    public function clearVariantWholesaleDiscountPrice()
    {
        unset($this->variant_wholesale_discount_price);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money variant_wholesale_discount_price = 5;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setVariantWholesaleDiscountPrice($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->variant_wholesale_discount_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue custom_rule = 6;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getCustomRule()
    {
        return isset($this->custom_rule) ? $this->custom_rule : null;
    }

    public function hasCustomRule()
    {
        return isset($this->custom_rule);
    }

    public function clearCustomRule()
    {
        unset($this->custom_rule);
    }

    /**
     * Returns the unboxed value from <code>getCustomRule()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue custom_rule = 6;</code>
     * @return string|null
     */
    public function getCustomRuleUnwrapped()
    {
        return $this->readWrapperValue("custom_rule");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue custom_rule = 6;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setCustomRule($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->custom_rule = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue custom_rule = 6;</code>
     * @param string|null $var
     * @return $this
     */
    public function setCustomRuleUnwrapped($var)
    {
        $this->writeWrapperValue("custom_rule", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue group_tag = 7;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getGroupTag()
    {
        return isset($this->group_tag) ? $this->group_tag : null;
    }

    public function hasGroupTag()
    {
        return isset($this->group_tag);
    }

    public function clearGroupTag()
    {
        unset($this->group_tag);
    }

    /**
     * Returns the unboxed value from <code>getGroupTag()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue group_tag = 7;</code>
     * @return string|null
     */
    public function getGroupTagUnwrapped()
    {
        return $this->readWrapperValue("group_tag");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue group_tag = 7;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setGroupTag($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->group_tag = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue group_tag = 7;</code>
     * @param string|null $var
     * @return $this
     */
    public function setGroupTagUnwrapped($var)
    {
        $this->writeWrapperValue("group_tag", $var);
        return $this;}

}

