<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Lexmodo\V1\Products;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.products.Weight</code>
 */
class Weight
{
    /**
     * Generated from protobuf enum <code>w_v = 0;</code>
     */
    const w_v = 0;
    /**
     * Generated from protobuf enum <code>lbs = 1;</code>
     */
    const lbs = 1;
    /**
     * Generated from protobuf enum <code>kgs = 2;</code>
     */
    const kgs = 2;
    /**
     * Generated from protobuf enum <code>oz = 3;</code>
     */
    const oz = 3;
    /**
     * Generated from protobuf enum <code>g = 4;</code>
     */
    const g = 4;

    private static $valueToName = [
        self::w_v => 'w_v',
        self::lbs => 'lbs',
        self::kgs => 'kgs',
        self::oz => 'oz',
        self::g => 'g',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

