// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CartsClient is the client API for Carts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartsClient interface {
	GetCustomerCartUUID(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCartUUID(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	GetCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	SetCartType(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteFromCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DeleteCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	PurgeCustomerInfo(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	CalculatePriceNoCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	AddToCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	UpdateCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type cartsClient struct {
	cc grpc.ClientConnInterface
}

func NewCartsClient(cc grpc.ClientConnInterface) CartsClient {
	return &cartsClient{cc}
}

func (c *cartsClient) GetCustomerCartUUID(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/GetCustomerCartUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) GetCartUUID(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/GetCartUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) GetCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/GetCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) SetCartType(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/SetCartType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) DeleteFromCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/DeleteFromCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) DeleteCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/DeleteCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) PurgeCustomerInfo(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/PurgeCustomerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) CalculatePriceNoCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/CalculatePriceNoCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) AddToCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/AddToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartsClient) UpdateCart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/lexmodo.v1.carts.Carts/UpdateCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartsServer is the server API for Carts service.
// All implementations must embed UnimplementedCartsServer
// for forward compatibility
type CartsServer interface {
	GetCustomerCartUUID(context.Context, *CartRequest) (*ResultResponse, error)
	GetCartUUID(context.Context, *CartRequest) (*ResultResponse, error)
	GetCart(context.Context, *CartRequest) (*ResultResponse, error)
	SetCartType(context.Context, *CartRequest) (*ResultResponse, error)
	DeleteFromCart(context.Context, *CartRequest) (*ResultResponse, error)
	DeleteCart(context.Context, *CartRequest) (*ResultResponse, error)
	PurgeCustomerInfo(context.Context, *CartRequest) (*ResultResponse, error)
	CalculatePriceNoCart(context.Context, *CartRequest) (*ResultResponse, error)
	AddToCart(context.Context, *CartRequest) (*ResultResponse, error)
	UpdateCart(context.Context, *CartRequest) (*ResultResponse, error)
	mustEmbedUnimplementedCartsServer()
}

// UnimplementedCartsServer must be embedded to have forward compatible implementations.
type UnimplementedCartsServer struct {
}

func (UnimplementedCartsServer) GetCustomerCartUUID(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerCartUUID not implemented")
}
func (UnimplementedCartsServer) GetCartUUID(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartUUID not implemented")
}
func (UnimplementedCartsServer) GetCart(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCart not implemented")
}
func (UnimplementedCartsServer) SetCartType(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCartType not implemented")
}
func (UnimplementedCartsServer) DeleteFromCart(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFromCart not implemented")
}
func (UnimplementedCartsServer) DeleteCart(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCart not implemented")
}
func (UnimplementedCartsServer) PurgeCustomerInfo(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeCustomerInfo not implemented")
}
func (UnimplementedCartsServer) CalculatePriceNoCart(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePriceNoCart not implemented")
}
func (UnimplementedCartsServer) AddToCart(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedCartsServer) UpdateCart(context.Context, *CartRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCart not implemented")
}
func (UnimplementedCartsServer) mustEmbedUnimplementedCartsServer() {}

// UnsafeCartsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartsServer will
// result in compilation errors.
type UnsafeCartsServer interface {
	mustEmbedUnimplementedCartsServer()
}

func RegisterCartsServer(s grpc.ServiceRegistrar, srv CartsServer) {
	s.RegisterService(&Carts_ServiceDesc, srv)
}

func _Carts_GetCustomerCartUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).GetCustomerCartUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/GetCustomerCartUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).GetCustomerCartUUID(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_GetCartUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).GetCartUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/GetCartUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).GetCartUUID(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_GetCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).GetCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/GetCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).GetCart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_SetCartType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).SetCartType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/SetCartType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).SetCartType(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_DeleteFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).DeleteFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/DeleteFromCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).DeleteFromCart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_DeleteCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).DeleteCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/DeleteCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).DeleteCart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_PurgeCustomerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).PurgeCustomerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/PurgeCustomerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).PurgeCustomerInfo(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_CalculatePriceNoCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).CalculatePriceNoCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/CalculatePriceNoCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).CalculatePriceNoCart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/AddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).AddToCart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carts_UpdateCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServer).UpdateCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lexmodo.v1.carts.Carts/UpdateCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServer).UpdateCart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Carts_ServiceDesc is the grpc.ServiceDesc for Carts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Carts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lexmodo.v1.carts.Carts",
	HandlerType: (*CartsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomerCartUUID",
			Handler:    _Carts_GetCustomerCartUUID_Handler,
		},
		{
			MethodName: "GetCartUUID",
			Handler:    _Carts_GetCartUUID_Handler,
		},
		{
			MethodName: "GetCart",
			Handler:    _Carts_GetCart_Handler,
		},
		{
			MethodName: "SetCartType",
			Handler:    _Carts_SetCartType_Handler,
		},
		{
			MethodName: "DeleteFromCart",
			Handler:    _Carts_DeleteFromCart_Handler,
		},
		{
			MethodName: "DeleteCart",
			Handler:    _Carts_DeleteCart_Handler,
		},
		{
			MethodName: "PurgeCustomerInfo",
			Handler:    _Carts_PurgeCustomerInfo_Handler,
		},
		{
			MethodName: "CalculatePriceNoCart",
			Handler:    _Carts_CalculatePriceNoCart_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _Carts_AddToCart_Handler,
		},
		{
			MethodName: "UpdateCart",
			Handler:    _Carts_UpdateCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
