<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoice_items.proto

namespace Lexmodo\V1\Order\Invoice\Items;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.order.invoice.items.BackorderInfo</code>
 */
class BackorderInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool placed_on_backorder = 1;</code>
     */
    protected $placed_on_backorder = false;
    /**
     * Generated from protobuf field <code>double orders_products_qty_backorder = 2;</code>
     */
    protected $orders_products_qty_backorder = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $placed_on_backorder
     *     @type float $orders_products_qty_backorder
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\InvoiceItems::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool placed_on_backorder = 1;</code>
     * @return bool
     */
    public function getPlacedOnBackorder()
    {
        return $this->placed_on_backorder;
    }

    /**
     * Generated from protobuf field <code>bool placed_on_backorder = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setPlacedOnBackorder($var)
    {
        GPBUtil::checkBool($var);
        $this->placed_on_backorder = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double orders_products_qty_backorder = 2;</code>
     * @return float
     */
    public function getOrdersProductsQtyBackorder()
    {
        return $this->orders_products_qty_backorder;
    }

    /**
     * Generated from protobuf field <code>double orders_products_qty_backorder = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setOrdersProductsQtyBackorder($var)
    {
        GPBUtil::checkDouble($var);
        $this->orders_products_qty_backorder = $var;

        return $this;
    }

}

