<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

use UnexpectedValueException;

/**
 * Protobuf type <code>lexmodo.v1.orders.FULFILLED_STATUS</code>
 */
class FULFILLED_STATUS
{
    /**
     * Generated from protobuf enum <code>none_FULFILLED_status = 0;</code>
     */
    const none_FULFILLED_status = 0;
    /**
     * Generated from protobuf enum <code>unfulfilled = 1;</code>
     */
    const unfulfilled = 1;
    /**
     * Generated from protobuf enum <code>fulfilled = 2;</code>
     */
    const fulfilled = 2;

    private static $valueToName = [
        self::none_FULFILLED_status => 'none_FULFILLED_status',
        self::unfulfilled => 'unfulfilled',
        self::fulfilled => 'fulfilled',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

