<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.orders.Invoice</code>
 */
class Invoice extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string invoice_uuid = 1;</code>
     */
    protected $invoice_uuid = '';
    /**
     * Generated from protobuf field <code>string invoice_id = 2;</code>
     */
    protected $invoice_id = '';
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.invoice.items.InvoiceLineItem invoice_line_items = 3;</code>
     */
    private $invoice_line_items;
    /**
     * Generated from protobuf field <code>uint64 invoice_date = 5;</code>
     */
    protected $invoice_date = 0;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address bill_to = 6;</code>
     */
    protected $bill_to = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address ship_to = 7;</code>
     */
    protected $ship_to = null;
    /**
     * Generated from protobuf field <code>string customers_id = 8;</code>
     */
    protected $customers_id = '';
    /**
     * Generated from protobuf field <code>string customers_email_address = 9;</code>
     */
    protected $customers_email_address = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money payments_collected = 10;</code>
     */
    protected $payments_collected = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money payments_owed = 11;</code>
     */
    protected $payments_owed = null;
    /**
     * Generated from protobuf field <code>repeated string tags = 12;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.FULFILLED_STATUS fulfillment_status = 13;</code>
     */
    protected $fulfillment_status = 0;
    /**
     * Generated from protobuf field <code>string shipping_method = 14;</code>
     */
    protected $shipping_method = '';
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.modules.OrderTotal order_total = 15;</code>
     */
    private $order_total;
    /**
     * Generated from protobuf field <code>string payment_method = 16;</code>
     */
    protected $payment_method = '';
    /**
     * Generated from protobuf field <code>string payment_processor_code = 17;</code>
     */
    protected $payment_processor_code = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice.PAYMENT_STATUS payment_status = 18;</code>
     */
    protected $payment_status = 0;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money order_value = 19;</code>
     */
    protected $order_value = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 20;</code>
     */
    protected $customer_note = null;
    /**
     * Generated from protobuf field <code>uint32 number_of_order_items = 21;</code>
     */
    protected $number_of_order_items = 0;
    /**
     * Generated from protobuf field <code>bool order_is_taxable = 22;</code>
     */
    protected $order_is_taxable = false;
    /**
     * Generated from protobuf field <code>map<string, int64> invoice_line_items_map = 23;</code>
     */
    private $invoice_line_items_map;
    /**
     * Generated from protobuf field <code>bool require_module_reloads = 24;</code>
     */
    protected $require_module_reloads = false;
    /**
     * Generated from protobuf field <code>map<string, bool> order_module_manual_edit = 25;</code>
     */
    private $order_module_manual_edit;
    /**
     * Generated from protobuf field <code>uint64 client_id = 26;</code>
     */
    protected $client_id = 0;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.modules.OrderTotal payments_collected_order_total = 27;</code>
     */
    private $payments_collected_order_total;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Refunds refunded_invoices = 28;</code>
     */
    protected $refunded_invoices = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.ORDER_STATUS order_status = 29;</code>
     */
    protected $order_status = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue refund_reason = 30;</code>
     */
    protected $refund_reason = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue order_update_code = 31;</code>
     */
    protected $order_update_code = null;
    /**
     * Generated from protobuf field <code>string order_origin_ip = 32;</code>
     */
    protected $order_origin_ip = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $invoice_uuid
     *     @type string $invoice_id
     *     @type \Lexmodo\V1\Order\Invoice\Items\InvoiceLineItem[]|\Google\Protobuf\Internal\RepeatedField $invoice_line_items
     *     @type int|string $invoice_date
     *     @type \Lexmodo\V1\Address\Address $bill_to
     *     @type \Lexmodo\V1\Address\Address $ship_to
     *     @type string $customers_id
     *     @type string $customers_email_address
     *     @type \Lexmodo\V1\Money\Money $payments_collected
     *     @type \Lexmodo\V1\Money\Money $payments_owed
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *     @type int $fulfillment_status
     *     @type string $shipping_method
     *     @type \Lexmodo\V1\Order\Modules\OrderTotal[]|\Google\Protobuf\Internal\RepeatedField $order_total
     *     @type string $payment_method
     *     @type string $payment_processor_code
     *     @type int $payment_status
     *     @type \Lexmodo\V1\Money\Money $order_value
     *     @type \Google\Protobuf\StringValue $customer_note
     *     @type int $number_of_order_items
     *     @type bool $order_is_taxable
     *     @type array|\Google\Protobuf\Internal\MapField $invoice_line_items_map
     *     @type bool $require_module_reloads
     *     @type array|\Google\Protobuf\Internal\MapField $order_module_manual_edit
     *     @type int|string $client_id
     *     @type \Lexmodo\V1\Order\Modules\OrderTotal[]|\Google\Protobuf\Internal\RepeatedField $payments_collected_order_total
     *     @type \Lexmodo\V1\Orders\Refunds $refunded_invoices
     *     @type int $order_status
     *     @type \Google\Protobuf\StringValue $refund_reason
     *     @type \Google\Protobuf\StringValue $order_update_code
     *     @type string $order_origin_ip
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string invoice_uuid = 1;</code>
     * @return string
     */
    public function getInvoiceUuid()
    {
        return $this->invoice_uuid;
    }

    /**
     * Generated from protobuf field <code>string invoice_uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->invoice_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invoice_id = 2;</code>
     * @return string
     */
    public function getInvoiceId()
    {
        return $this->invoice_id;
    }

    /**
     * Generated from protobuf field <code>string invoice_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->invoice_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.invoice.items.InvoiceLineItem invoice_line_items = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInvoiceLineItems()
    {
        return $this->invoice_line_items;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.invoice.items.InvoiceLineItem invoice_line_items = 3;</code>
     * @param \Lexmodo\V1\Order\Invoice\Items\InvoiceLineItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInvoiceLineItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Order\Invoice\Items\InvoiceLineItem::class);
        $this->invoice_line_items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 invoice_date = 5;</code>
     * @return int|string
     */
    public function getInvoiceDate()
    {
        return $this->invoice_date;
    }

    /**
     * Generated from protobuf field <code>uint64 invoice_date = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInvoiceDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->invoice_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address bill_to = 6;</code>
     * @return \Lexmodo\V1\Address\Address|null
     */
    public function getBillTo()
    {
        return isset($this->bill_to) ? $this->bill_to : null;
    }

    public function hasBillTo()
    {
        return isset($this->bill_to);
    }

    public function clearBillTo()
    {
        unset($this->bill_to);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address bill_to = 6;</code>
     * @param \Lexmodo\V1\Address\Address $var
     * @return $this
     */
    public function setBillTo($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Address\Address::class);
        $this->bill_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address ship_to = 7;</code>
     * @return \Lexmodo\V1\Address\Address|null
     */
    public function getShipTo()
    {
        return isset($this->ship_to) ? $this->ship_to : null;
    }

    public function hasShipTo()
    {
        return isset($this->ship_to);
    }

    public function clearShipTo()
    {
        unset($this->ship_to);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.address.Address ship_to = 7;</code>
     * @param \Lexmodo\V1\Address\Address $var
     * @return $this
     */
    public function setShipTo($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Address\Address::class);
        $this->ship_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customers_id = 8;</code>
     * @return string
     */
    public function getCustomersId()
    {
        return $this->customers_id;
    }

    /**
     * Generated from protobuf field <code>string customers_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomersId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customers_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customers_email_address = 9;</code>
     * @return string
     */
    public function getCustomersEmailAddress()
    {
        return $this->customers_email_address;
    }

    /**
     * Generated from protobuf field <code>string customers_email_address = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomersEmailAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->customers_email_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money payments_collected = 10;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getPaymentsCollected()
    {
        return isset($this->payments_collected) ? $this->payments_collected : null;
    }

    public function hasPaymentsCollected()
    {
        return isset($this->payments_collected);
    }

    public function clearPaymentsCollected()
    {
        unset($this->payments_collected);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money payments_collected = 10;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setPaymentsCollected($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->payments_collected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money payments_owed = 11;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getPaymentsOwed()
    {
        return isset($this->payments_owed) ? $this->payments_owed : null;
    }

    public function hasPaymentsOwed()
    {
        return isset($this->payments_owed);
    }

    public function clearPaymentsOwed()
    {
        unset($this->payments_owed);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money payments_owed = 11;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setPaymentsOwed($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->payments_owed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.FULFILLED_STATUS fulfillment_status = 13;</code>
     * @return int
     */
    public function getFulfillmentStatus()
    {
        return $this->fulfillment_status;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.FULFILLED_STATUS fulfillment_status = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setFulfillmentStatus($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Orders\FULFILLED_STATUS::class);
        $this->fulfillment_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shipping_method = 14;</code>
     * @return string
     */
    public function getShippingMethod()
    {
        return $this->shipping_method;
    }

    /**
     * Generated from protobuf field <code>string shipping_method = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->shipping_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.modules.OrderTotal order_total = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderTotal()
    {
        return $this->order_total;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.modules.OrderTotal order_total = 15;</code>
     * @param \Lexmodo\V1\Order\Modules\OrderTotal[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderTotal($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Order\Modules\OrderTotal::class);
        $this->order_total = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_method = 16;</code>
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->payment_method;
    }

    /**
     * Generated from protobuf field <code>string payment_method = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_processor_code = 17;</code>
     * @return string
     */
    public function getPaymentProcessorCode()
    {
        return $this->payment_processor_code;
    }

    /**
     * Generated from protobuf field <code>string payment_processor_code = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentProcessorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_processor_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice.PAYMENT_STATUS payment_status = 18;</code>
     * @return int
     */
    public function getPaymentStatus()
    {
        return $this->payment_status;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice.PAYMENT_STATUS payment_status = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setPaymentStatus($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Orders\Invoice\PAYMENT_STATUS::class);
        $this->payment_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money order_value = 19;</code>
     * @return \Lexmodo\V1\Money\Money|null
     */
    public function getOrderValue()
    {
        return isset($this->order_value) ? $this->order_value : null;
    }

    public function hasOrderValue()
    {
        return isset($this->order_value);
    }

    public function clearOrderValue()
    {
        unset($this->order_value);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.money.Money order_value = 19;</code>
     * @param \Lexmodo\V1\Money\Money $var
     * @return $this
     */
    public function setOrderValue($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Money\Money::class);
        $this->order_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 20;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getCustomerNote()
    {
        return isset($this->customer_note) ? $this->customer_note : null;
    }

    public function hasCustomerNote()
    {
        return isset($this->customer_note);
    }

    public function clearCustomerNote()
    {
        unset($this->customer_note);
    }

    /**
     * Returns the unboxed value from <code>getCustomerNote()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 20;</code>
     * @return string|null
     */
    public function getCustomerNoteUnwrapped()
    {
        return $this->readWrapperValue("customer_note");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 20;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setCustomerNote($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->customer_note = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 20;</code>
     * @param string|null $var
     * @return $this
     */
    public function setCustomerNoteUnwrapped($var)
    {
        $this->writeWrapperValue("customer_note", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>uint32 number_of_order_items = 21;</code>
     * @return int
     */
    public function getNumberOfOrderItems()
    {
        return $this->number_of_order_items;
    }

    /**
     * Generated from protobuf field <code>uint32 number_of_order_items = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfOrderItems($var)
    {
        GPBUtil::checkUint32($var);
        $this->number_of_order_items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool order_is_taxable = 22;</code>
     * @return bool
     */
    public function getOrderIsTaxable()
    {
        return $this->order_is_taxable;
    }

    /**
     * Generated from protobuf field <code>bool order_is_taxable = 22;</code>
     * @param bool $var
     * @return $this
     */
    public function setOrderIsTaxable($var)
    {
        GPBUtil::checkBool($var);
        $this->order_is_taxable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> invoice_line_items_map = 23;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getInvoiceLineItemsMap()
    {
        return $this->invoice_line_items_map;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> invoice_line_items_map = 23;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setInvoiceLineItemsMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT64);
        $this->invoice_line_items_map = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool require_module_reloads = 24;</code>
     * @return bool
     */
    public function getRequireModuleReloads()
    {
        return $this->require_module_reloads;
    }

    /**
     * Generated from protobuf field <code>bool require_module_reloads = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequireModuleReloads($var)
    {
        GPBUtil::checkBool($var);
        $this->require_module_reloads = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, bool> order_module_manual_edit = 25;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOrderModuleManualEdit()
    {
        return $this->order_module_manual_edit;
    }

    /**
     * Generated from protobuf field <code>map<string, bool> order_module_manual_edit = 25;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOrderModuleManualEdit($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->order_module_manual_edit = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 client_id = 26;</code>
     * @return int|string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>uint64 client_id = 26;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkUint64($var);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.modules.OrderTotal payments_collected_order_total = 27;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPaymentsCollectedOrderTotal()
    {
        return $this->payments_collected_order_total;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.order.modules.OrderTotal payments_collected_order_total = 27;</code>
     * @param \Lexmodo\V1\Order\Modules\OrderTotal[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPaymentsCollectedOrderTotal($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Order\Modules\OrderTotal::class);
        $this->payments_collected_order_total = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Refunds refunded_invoices = 28;</code>
     * @return \Lexmodo\V1\Orders\Refunds|null
     */
    public function getRefundedInvoices()
    {
        return isset($this->refunded_invoices) ? $this->refunded_invoices : null;
    }

    public function hasRefundedInvoices()
    {
        return isset($this->refunded_invoices);
    }

    public function clearRefundedInvoices()
    {
        unset($this->refunded_invoices);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Refunds refunded_invoices = 28;</code>
     * @param \Lexmodo\V1\Orders\Refunds $var
     * @return $this
     */
    public function setRefundedInvoices($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\Refunds::class);
        $this->refunded_invoices = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.ORDER_STATUS order_status = 29;</code>
     * @return int
     */
    public function getOrderStatus()
    {
        return $this->order_status;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.ORDER_STATUS order_status = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Orders\ORDER_STATUS::class);
        $this->order_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue refund_reason = 30;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getRefundReason()
    {
        return isset($this->refund_reason) ? $this->refund_reason : null;
    }

    public function hasRefundReason()
    {
        return isset($this->refund_reason);
    }

    public function clearRefundReason()
    {
        unset($this->refund_reason);
    }

    /**
     * Returns the unboxed value from <code>getRefundReason()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue refund_reason = 30;</code>
     * @return string|null
     */
    public function getRefundReasonUnwrapped()
    {
        return $this->readWrapperValue("refund_reason");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue refund_reason = 30;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setRefundReason($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->refund_reason = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue refund_reason = 30;</code>
     * @param string|null $var
     * @return $this
     */
    public function setRefundReasonUnwrapped($var)
    {
        $this->writeWrapperValue("refund_reason", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue order_update_code = 31;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getOrderUpdateCode()
    {
        return isset($this->order_update_code) ? $this->order_update_code : null;
    }

    public function hasOrderUpdateCode()
    {
        return isset($this->order_update_code);
    }

    public function clearOrderUpdateCode()
    {
        unset($this->order_update_code);
    }

    /**
     * Returns the unboxed value from <code>getOrderUpdateCode()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue order_update_code = 31;</code>
     * @return string|null
     */
    public function getOrderUpdateCodeUnwrapped()
    {
        return $this->readWrapperValue("order_update_code");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue order_update_code = 31;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setOrderUpdateCode($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->order_update_code = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue order_update_code = 31;</code>
     * @param string|null $var
     * @return $this
     */
    public function setOrderUpdateCodeUnwrapped($var)
    {
        $this->writeWrapperValue("order_update_code", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>string order_origin_ip = 32;</code>
     * @return string
     */
    public function getOrderOriginIp()
    {
        return $this->order_origin_ip;
    }

    /**
     * Generated from protobuf field <code>string order_origin_ip = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderOriginIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_origin_ip = $var;

        return $this;
    }

}

