<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.orders.OrdersRequest</code>
 */
class OrdersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * cart & customer id  
     *
     * Generated from protobuf field <code>.lexmodo.v1.carts.CartRequest cart = 1;</code>
     */
    protected $cart = null;
    /**
     *dynaimc rates that you get from GetShippingMethods
     *
     * Generated from protobuf field <code>.lexmodo.v1.shipping.ShippingQuoteRequest shipping_info = 2;</code>
     */
    protected $shipping_info = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue coupon_code = 3;</code>
     */
    protected $coupon_code = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value store_credit = 4;</code>
     */
    protected $store_credit = null;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.CustomLineItem custom_line_items = 6;</code>
     */
    private $custom_line_items;
    /**
     * Generated from protobuf field <code>uint32 reserve_order = 7;</code>
     */
    protected $reserve_order = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 8;</code>
     */
    protected $customer_note = null;
    /**
     * Generated from protobuf field <code>repeated string tags = 9;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.order.modules.OrderTotal order_module = 10;</code>
     */
    protected $order_module = null;
    /**
     * Generated from protobuf field <code>string invoice_uuid = 11;</code>
     */
    protected $invoice_uuid = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Analytical customer_value = 12;</code>
     */
    protected $customer_value = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.TimeLineAction timeline_action = 13;</code>
     */
    protected $timeline_action = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.PaymentRequest payment = 14;</code>
     */
    protected $payment = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value invoice_id_numeric = 15;</code>
     */
    protected $invoice_id_numeric = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue order_is_taxable = 16;</code>
     */
    protected $order_is_taxable = null;
    /**
     * Generated from protobuf field <code>bool show_only_unpaid_items = 17;</code>
     */
    protected $show_only_unpaid_items = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue replaces_order_uuid = 18;</code>
     */
    protected $replaces_order_uuid = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue gift_code = 19;</code>
     */
    protected $gift_code = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.ORDER_STATUS order_status = 20;</code>
     */
    protected $order_status = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value use_outstanding_balance = 21;</code>
     */
    protected $use_outstanding_balance = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue allow_duplicate = 22;</code>
     */
    protected $allow_duplicate = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lexmodo\V1\Carts\CartRequest $cart
     *           cart & customer id  
     *     @type \Lexmodo\V1\Shipping\ShippingQuoteRequest $shipping_info
     *          dynaimc rates that you get from GetShippingMethods
     *     @type \Google\Protobuf\StringValue $coupon_code
     *     @type \Google\Protobuf\Int32Value $store_credit
     *     @type \Lexmodo\V1\Orders\CustomLineItem[]|\Google\Protobuf\Internal\RepeatedField $custom_line_items
     *     @type int $reserve_order
     *     @type \Google\Protobuf\StringValue $customer_note
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *     @type \Lexmodo\V1\Order\Modules\OrderTotal $order_module
     *     @type string $invoice_uuid
     *     @type \Lexmodo\V1\Orders\Analytical $customer_value
     *     @type \Lexmodo\V1\Orders\TimeLineAction $timeline_action
     *     @type \Lexmodo\V1\Payments\PaymentRequest $payment
     *     @type \Google\Protobuf\Int32Value $invoice_id_numeric
     *     @type \Google\Protobuf\BoolValue $order_is_taxable
     *     @type bool $show_only_unpaid_items
     *     @type \Google\Protobuf\StringValue $replaces_order_uuid
     *     @type \Google\Protobuf\StringValue $gift_code
     *     @type int $order_status
     *     @type \Google\Protobuf\Int32Value $use_outstanding_balance
     *     @type \Google\Protobuf\BoolValue $allow_duplicate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     * cart & customer id  
     *
     * Generated from protobuf field <code>.lexmodo.v1.carts.CartRequest cart = 1;</code>
     * @return \Lexmodo\V1\Carts\CartRequest|null
     */
    public function getCart()
    {
        return isset($this->cart) ? $this->cart : null;
    }

    public function hasCart()
    {
        return isset($this->cart);
    }

    public function clearCart()
    {
        unset($this->cart);
    }

    /**
     * cart & customer id  
     *
     * Generated from protobuf field <code>.lexmodo.v1.carts.CartRequest cart = 1;</code>
     * @param \Lexmodo\V1\Carts\CartRequest $var
     * @return $this
     */
    public function setCart($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Carts\CartRequest::class);
        $this->cart = $var;

        return $this;
    }

    /**
     *dynaimc rates that you get from GetShippingMethods
     *
     * Generated from protobuf field <code>.lexmodo.v1.shipping.ShippingQuoteRequest shipping_info = 2;</code>
     * @return \Lexmodo\V1\Shipping\ShippingQuoteRequest|null
     */
    public function getShippingInfo()
    {
        return isset($this->shipping_info) ? $this->shipping_info : null;
    }

    public function hasShippingInfo()
    {
        return isset($this->shipping_info);
    }

    public function clearShippingInfo()
    {
        unset($this->shipping_info);
    }

    /**
     *dynaimc rates that you get from GetShippingMethods
     *
     * Generated from protobuf field <code>.lexmodo.v1.shipping.ShippingQuoteRequest shipping_info = 2;</code>
     * @param \Lexmodo\V1\Shipping\ShippingQuoteRequest $var
     * @return $this
     */
    public function setShippingInfo($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Shipping\ShippingQuoteRequest::class);
        $this->shipping_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue coupon_code = 3;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getCouponCode()
    {
        return isset($this->coupon_code) ? $this->coupon_code : null;
    }

    public function hasCouponCode()
    {
        return isset($this->coupon_code);
    }

    public function clearCouponCode()
    {
        unset($this->coupon_code);
    }

    /**
     * Returns the unboxed value from <code>getCouponCode()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue coupon_code = 3;</code>
     * @return string|null
     */
    public function getCouponCodeUnwrapped()
    {
        return $this->readWrapperValue("coupon_code");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue coupon_code = 3;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setCouponCode($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->coupon_code = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue coupon_code = 3;</code>
     * @param string|null $var
     * @return $this
     */
    public function setCouponCodeUnwrapped($var)
    {
        $this->writeWrapperValue("coupon_code", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value store_credit = 4;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getStoreCredit()
    {
        return isset($this->store_credit) ? $this->store_credit : null;
    }

    public function hasStoreCredit()
    {
        return isset($this->store_credit);
    }

    public function clearStoreCredit()
    {
        unset($this->store_credit);
    }

    /**
     * Returns the unboxed value from <code>getStoreCredit()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value store_credit = 4;</code>
     * @return int|null
     */
    public function getStoreCreditUnwrapped()
    {
        return $this->readWrapperValue("store_credit");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value store_credit = 4;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setStoreCredit($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->store_credit = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value store_credit = 4;</code>
     * @param int|null $var
     * @return $this
     */
    public function setStoreCreditUnwrapped($var)
    {
        $this->writeWrapperValue("store_credit", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.CustomLineItem custom_line_items = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomLineItems()
    {
        return $this->custom_line_items;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.CustomLineItem custom_line_items = 6;</code>
     * @param \Lexmodo\V1\Orders\CustomLineItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomLineItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Orders\CustomLineItem::class);
        $this->custom_line_items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 reserve_order = 7;</code>
     * @return int
     */
    public function getReserveOrder()
    {
        return $this->reserve_order;
    }

    /**
     * Generated from protobuf field <code>uint32 reserve_order = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setReserveOrder($var)
    {
        GPBUtil::checkUint32($var);
        $this->reserve_order = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 8;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getCustomerNote()
    {
        return isset($this->customer_note) ? $this->customer_note : null;
    }

    public function hasCustomerNote()
    {
        return isset($this->customer_note);
    }

    public function clearCustomerNote()
    {
        unset($this->customer_note);
    }

    /**
     * Returns the unboxed value from <code>getCustomerNote()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 8;</code>
     * @return string|null
     */
    public function getCustomerNoteUnwrapped()
    {
        return $this->readWrapperValue("customer_note");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 8;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setCustomerNote($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->customer_note = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue customer_note = 8;</code>
     * @param string|null $var
     * @return $this
     */
    public function setCustomerNoteUnwrapped($var)
    {
        $this->writeWrapperValue("customer_note", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>repeated string tags = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.order.modules.OrderTotal order_module = 10;</code>
     * @return \Lexmodo\V1\Order\Modules\OrderTotal|null
     */
    public function getOrderModule()
    {
        return isset($this->order_module) ? $this->order_module : null;
    }

    public function hasOrderModule()
    {
        return isset($this->order_module);
    }

    public function clearOrderModule()
    {
        unset($this->order_module);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.order.modules.OrderTotal order_module = 10;</code>
     * @param \Lexmodo\V1\Order\Modules\OrderTotal $var
     * @return $this
     */
    public function setOrderModule($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Order\Modules\OrderTotal::class);
        $this->order_module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invoice_uuid = 11;</code>
     * @return string
     */
    public function getInvoiceUuid()
    {
        return $this->invoice_uuid;
    }

    /**
     * Generated from protobuf field <code>string invoice_uuid = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->invoice_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Analytical customer_value = 12;</code>
     * @return \Lexmodo\V1\Orders\Analytical|null
     */
    public function getCustomerValue()
    {
        return isset($this->customer_value) ? $this->customer_value : null;
    }

    public function hasCustomerValue()
    {
        return isset($this->customer_value);
    }

    public function clearCustomerValue()
    {
        unset($this->customer_value);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Analytical customer_value = 12;</code>
     * @param \Lexmodo\V1\Orders\Analytical $var
     * @return $this
     */
    public function setCustomerValue($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\Analytical::class);
        $this->customer_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.TimeLineAction timeline_action = 13;</code>
     * @return \Lexmodo\V1\Orders\TimeLineAction|null
     */
    public function getTimelineAction()
    {
        return isset($this->timeline_action) ? $this->timeline_action : null;
    }

    public function hasTimelineAction()
    {
        return isset($this->timeline_action);
    }

    public function clearTimelineAction()
    {
        unset($this->timeline_action);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.TimeLineAction timeline_action = 13;</code>
     * @param \Lexmodo\V1\Orders\TimeLineAction $var
     * @return $this
     */
    public function setTimelineAction($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\TimeLineAction::class);
        $this->timeline_action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.PaymentRequest payment = 14;</code>
     * @return \Lexmodo\V1\Payments\PaymentRequest|null
     */
    public function getPayment()
    {
        return isset($this->payment) ? $this->payment : null;
    }

    public function hasPayment()
    {
        return isset($this->payment);
    }

    public function clearPayment()
    {
        unset($this->payment);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.PaymentRequest payment = 14;</code>
     * @param \Lexmodo\V1\Payments\PaymentRequest $var
     * @return $this
     */
    public function setPayment($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Payments\PaymentRequest::class);
        $this->payment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value invoice_id_numeric = 15;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getInvoiceIdNumeric()
    {
        return isset($this->invoice_id_numeric) ? $this->invoice_id_numeric : null;
    }

    public function hasInvoiceIdNumeric()
    {
        return isset($this->invoice_id_numeric);
    }

    public function clearInvoiceIdNumeric()
    {
        unset($this->invoice_id_numeric);
    }

    /**
     * Returns the unboxed value from <code>getInvoiceIdNumeric()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value invoice_id_numeric = 15;</code>
     * @return int|null
     */
    public function getInvoiceIdNumericUnwrapped()
    {
        return $this->readWrapperValue("invoice_id_numeric");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value invoice_id_numeric = 15;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setInvoiceIdNumeric($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->invoice_id_numeric = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value invoice_id_numeric = 15;</code>
     * @param int|null $var
     * @return $this
     */
    public function setInvoiceIdNumericUnwrapped($var)
    {
        $this->writeWrapperValue("invoice_id_numeric", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue order_is_taxable = 16;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getOrderIsTaxable()
    {
        return isset($this->order_is_taxable) ? $this->order_is_taxable : null;
    }

    public function hasOrderIsTaxable()
    {
        return isset($this->order_is_taxable);
    }

    public function clearOrderIsTaxable()
    {
        unset($this->order_is_taxable);
    }

    /**
     * Returns the unboxed value from <code>getOrderIsTaxable()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue order_is_taxable = 16;</code>
     * @return bool|null
     */
    public function getOrderIsTaxableUnwrapped()
    {
        return $this->readWrapperValue("order_is_taxable");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue order_is_taxable = 16;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setOrderIsTaxable($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->order_is_taxable = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue order_is_taxable = 16;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setOrderIsTaxableUnwrapped($var)
    {
        $this->writeWrapperValue("order_is_taxable", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>bool show_only_unpaid_items = 17;</code>
     * @return bool
     */
    public function getShowOnlyUnpaidItems()
    {
        return $this->show_only_unpaid_items;
    }

    /**
     * Generated from protobuf field <code>bool show_only_unpaid_items = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowOnlyUnpaidItems($var)
    {
        GPBUtil::checkBool($var);
        $this->show_only_unpaid_items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue replaces_order_uuid = 18;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getReplacesOrderUuid()
    {
        return isset($this->replaces_order_uuid) ? $this->replaces_order_uuid : null;
    }

    public function hasReplacesOrderUuid()
    {
        return isset($this->replaces_order_uuid);
    }

    public function clearReplacesOrderUuid()
    {
        unset($this->replaces_order_uuid);
    }

    /**
     * Returns the unboxed value from <code>getReplacesOrderUuid()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue replaces_order_uuid = 18;</code>
     * @return string|null
     */
    public function getReplacesOrderUuidUnwrapped()
    {
        return $this->readWrapperValue("replaces_order_uuid");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue replaces_order_uuid = 18;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setReplacesOrderUuid($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->replaces_order_uuid = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue replaces_order_uuid = 18;</code>
     * @param string|null $var
     * @return $this
     */
    public function setReplacesOrderUuidUnwrapped($var)
    {
        $this->writeWrapperValue("replaces_order_uuid", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue gift_code = 19;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getGiftCode()
    {
        return isset($this->gift_code) ? $this->gift_code : null;
    }

    public function hasGiftCode()
    {
        return isset($this->gift_code);
    }

    public function clearGiftCode()
    {
        unset($this->gift_code);
    }

    /**
     * Returns the unboxed value from <code>getGiftCode()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue gift_code = 19;</code>
     * @return string|null
     */
    public function getGiftCodeUnwrapped()
    {
        return $this->readWrapperValue("gift_code");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue gift_code = 19;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setGiftCode($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->gift_code = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue gift_code = 19;</code>
     * @param string|null $var
     * @return $this
     */
    public function setGiftCodeUnwrapped($var)
    {
        $this->writeWrapperValue("gift_code", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.ORDER_STATUS order_status = 20;</code>
     * @return int
     */
    public function getOrderStatus()
    {
        return $this->order_status;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.ORDER_STATUS order_status = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Orders\ORDER_STATUS::class);
        $this->order_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value use_outstanding_balance = 21;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getUseOutstandingBalance()
    {
        return isset($this->use_outstanding_balance) ? $this->use_outstanding_balance : null;
    }

    public function hasUseOutstandingBalance()
    {
        return isset($this->use_outstanding_balance);
    }

    public function clearUseOutstandingBalance()
    {
        unset($this->use_outstanding_balance);
    }

    /**
     * Returns the unboxed value from <code>getUseOutstandingBalance()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value use_outstanding_balance = 21;</code>
     * @return int|null
     */
    public function getUseOutstandingBalanceUnwrapped()
    {
        return $this->readWrapperValue("use_outstanding_balance");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value use_outstanding_balance = 21;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setUseOutstandingBalance($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->use_outstanding_balance = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value use_outstanding_balance = 21;</code>
     * @param int|null $var
     * @return $this
     */
    public function setUseOutstandingBalanceUnwrapped($var)
    {
        $this->writeWrapperValue("use_outstanding_balance", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue allow_duplicate = 22;</code>
     * @return \Google\Protobuf\BoolValue|null
     */
    public function getAllowDuplicate()
    {
        return isset($this->allow_duplicate) ? $this->allow_duplicate : null;
    }

    public function hasAllowDuplicate()
    {
        return isset($this->allow_duplicate);
    }

    public function clearAllowDuplicate()
    {
        unset($this->allow_duplicate);
    }

    /**
     * Returns the unboxed value from <code>getAllowDuplicate()</code>

     * Generated from protobuf field <code>.google.protobuf.BoolValue allow_duplicate = 22;</code>
     * @return bool|null
     */
    public function getAllowDuplicateUnwrapped()
    {
        return $this->readWrapperValue("allow_duplicate");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.BoolValue allow_duplicate = 22;</code>
     * @param \Google\Protobuf\BoolValue $var
     * @return $this
     */
    public function setAllowDuplicate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\BoolValue::class);
        $this->allow_duplicate = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\BoolValue object.

     * Generated from protobuf field <code>.google.protobuf.BoolValue allow_duplicate = 22;</code>
     * @param bool|null $var
     * @return $this
     */
    public function setAllowDuplicateUnwrapped($var)
    {
        $this->writeWrapperValue("allow_duplicate", $var);
        return $this;}

}

