<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

if (false) {
    /**
     * This class is deprecated. Use Lexmodo\V1\Orders\OrderScript\RUN_SCRIPT instead.
     * @deprecated
     */
    class OrderScript_RUN_SCRIPT {}
}
class_exists(OrderScript\RUN_SCRIPT::class);
@trigger_error('Lexmodo\V1\Orders\OrderScript_RUN_SCRIPT is deprecated and will be removed in the next major release. Use Lexmodo\V1\Orders\OrderScript\RUN_SCRIPT instead', E_USER_DEPRECATED);

