<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.orders.OrderScript</code>
 */
class OrderScript extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string script_uuid = 1;</code>
     */
    protected $script_uuid = '';
    /**
     * Generated from protobuf field <code>string script_name = 2;</code>
     */
    protected $script_name = '';
    /**
     * Generated from protobuf field <code>string script = 3;</code>
     */
    protected $script = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice input_data = 4;</code>
     */
    protected $input_data = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrderScript.RUN_SCRIPT initiate_at = 5;</code>
     */
    protected $initiate_at = 0;
    /**
     * Generated from protobuf field <code>uint32 sort_order = 6;</code>
     */
    protected $sort_order = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $script_uuid
     *     @type string $script_name
     *     @type string $script
     *     @type \Lexmodo\V1\Orders\Invoice $input_data
     *     @type int $initiate_at
     *     @type int $sort_order
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string script_uuid = 1;</code>
     * @return string
     */
    public function getScriptUuid()
    {
        return $this->script_uuid;
    }

    /**
     * Generated from protobuf field <code>string script_uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setScriptUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->script_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string script_name = 2;</code>
     * @return string
     */
    public function getScriptName()
    {
        return $this->script_name;
    }

    /**
     * Generated from protobuf field <code>string script_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setScriptName($var)
    {
        GPBUtil::checkString($var, True);
        $this->script_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string script = 3;</code>
     * @return string
     */
    public function getScript()
    {
        return $this->script;
    }

    /**
     * Generated from protobuf field <code>string script = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScript($var)
    {
        GPBUtil::checkString($var, True);
        $this->script = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice input_data = 4;</code>
     * @return \Lexmodo\V1\Orders\Invoice|null
     */
    public function getInputData()
    {
        return isset($this->input_data) ? $this->input_data : null;
    }

    public function hasInputData()
    {
        return isset($this->input_data);
    }

    public function clearInputData()
    {
        unset($this->input_data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice input_data = 4;</code>
     * @param \Lexmodo\V1\Orders\Invoice $var
     * @return $this
     */
    public function setInputData($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\Invoice::class);
        $this->input_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrderScript.RUN_SCRIPT initiate_at = 5;</code>
     * @return int
     */
    public function getInitiateAt()
    {
        return $this->initiate_at;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrderScript.RUN_SCRIPT initiate_at = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setInitiateAt($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Orders\OrderScript\RUN_SCRIPT::class);
        $this->initiate_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sort_order = 6;</code>
     * @return int
     */
    public function getSortOrder()
    {
        return $this->sort_order;
    }

    /**
     * Generated from protobuf field <code>uint32 sort_order = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSortOrder($var)
    {
        GPBUtil::checkUint32($var);
        $this->sort_order = $var;

        return $this;
    }

}

