<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.orders.OrdersRuleRequest</code>
 */
class OrdersRuleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string rule_id = 1;</code>
     */
    protected $rule_id = '';
    /**
     * Generated from protobuf field <code>string rule_name = 2;</code>
     */
    protected $rule_name = '';
    /**
     * Generated from protobuf field <code>string customer_id = 3;</code>
     */
    protected $customer_id = '';
    /**
     * Generated from protobuf field <code>string rule_query = 4;</code>
     */
    protected $rule_query = '';
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.RuleSortBy sort_by = 5;</code>
     */
    private $sort_by;
    /**
     * Generated from protobuf field <code>bool store_view = 6;</code>
     */
    protected $store_view = false;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.RuleReplace sort_rule = 7;</code>
     */
    private $sort_rule;
    /**
     * Generated from protobuf field <code>map<string, string> custom_data = 8;</code>
     */
    private $custom_data;
    /**
     * Generated from protobuf field <code>uint64 sort_order = 9;</code>
     */
    protected $sort_order = 0;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersListing orders_listing = 10;</code>
     */
    protected $orders_listing = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $rule_id
     *     @type string $rule_name
     *     @type string $customer_id
     *     @type string $rule_query
     *     @type \Lexmodo\V1\Orders\RuleSortBy[]|\Google\Protobuf\Internal\RepeatedField $sort_by
     *     @type bool $store_view
     *     @type \Lexmodo\V1\Orders\RuleReplace[]|\Google\Protobuf\Internal\RepeatedField $sort_rule
     *     @type array|\Google\Protobuf\Internal\MapField $custom_data
     *     @type int|string $sort_order
     *     @type \Lexmodo\V1\Orders\OrdersListing $orders_listing
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string rule_id = 1;</code>
     * @return string
     */
    public function getRuleId()
    {
        return $this->rule_id;
    }

    /**
     * Generated from protobuf field <code>string rule_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->rule_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rule_name = 2;</code>
     * @return string
     */
    public function getRuleName()
    {
        return $this->rule_name;
    }

    /**
     * Generated from protobuf field <code>string rule_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->rule_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_id = 3;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }

    /**
     * Generated from protobuf field <code>string customer_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rule_query = 4;</code>
     * @return string
     */
    public function getRuleQuery()
    {
        return $this->rule_query;
    }

    /**
     * Generated from protobuf field <code>string rule_query = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->rule_query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.RuleSortBy sort_by = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSortBy()
    {
        return $this->sort_by;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.RuleSortBy sort_by = 5;</code>
     * @param \Lexmodo\V1\Orders\RuleSortBy[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSortBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Orders\RuleSortBy::class);
        $this->sort_by = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool store_view = 6;</code>
     * @return bool
     */
    public function getStoreView()
    {
        return $this->store_view;
    }

    /**
     * Generated from protobuf field <code>bool store_view = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setStoreView($var)
    {
        GPBUtil::checkBool($var);
        $this->store_view = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.RuleReplace sort_rule = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSortRule()
    {
        return $this->sort_rule;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.RuleReplace sort_rule = 7;</code>
     * @param \Lexmodo\V1\Orders\RuleReplace[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSortRule($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Orders\RuleReplace::class);
        $this->sort_rule = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> custom_data = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCustomData()
    {
        return $this->custom_data;
    }

    /**
     * Generated from protobuf field <code>map<string, string> custom_data = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCustomData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->custom_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sort_order = 9;</code>
     * @return int|string
     */
    public function getSortOrder()
    {
        return $this->sort_order;
    }

    /**
     * Generated from protobuf field <code>uint64 sort_order = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSortOrder($var)
    {
        GPBUtil::checkUint64($var);
        $this->sort_order = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersListing orders_listing = 10;</code>
     * @return \Lexmodo\V1\Orders\OrdersListing|null
     */
    public function getOrdersListing()
    {
        return isset($this->orders_listing) ? $this->orders_listing : null;
    }

    public function hasOrdersListing()
    {
        return isset($this->orders_listing);
    }

    public function clearOrdersListing()
    {
        unset($this->orders_listing);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersListing orders_listing = 10;</code>
     * @param \Lexmodo\V1\Orders\OrdersListing $var
     * @return $this
     */
    public function setOrdersListing($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\OrdersListing::class);
        $this->orders_listing = $var;

        return $this;
    }

}

