<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.orders.ResultResponse</code>
 */
class ResultResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>bool failure = 2;</code>
     */
    protected $failure = false;
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 5;</code>
     */
    protected $invoice = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Analytical customer_value = 6;</code>
     */
    protected $customer_value = null;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.TimeLine order_timeline = 7;</code>
     */
    private $order_timeline;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrdersRuleRequest rules = 8;</code>
     */
    private $rules;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersListing order_listing = 9;</code>
     */
    protected $order_listing = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersRuleRequest rule = 10;</code>
     */
    protected $rule = null;
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrderTransactionDetails order_transaction_history = 11;</code>
     */
    private $order_transaction_history;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.PaymentResultDetails payment_confirmation = 12;</code>
     */
    protected $payment_confirmation = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.LabelData label_data = 13;</code>
     */
    protected $label_data = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OPC opc = 14;</code>
     */
    protected $opc = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.PackingSlip packing_slip = 15;</code>
     */
    protected $packing_slip = null;
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersScript orders_script = 16;</code>
     */
    protected $orders_script = null;
    /**
     * Generated from protobuf field <code>string script_result = 17;</code>
     */
    protected $script_result = '';
    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrderReports sales_report = 18;</code>
     */
    private $sales_report;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type bool $failure
     *     @type string $code
     *     @type string $message
     *     @type \Lexmodo\V1\Orders\Invoice $invoice
     *     @type \Lexmodo\V1\Orders\Analytical $customer_value
     *     @type \Lexmodo\V1\Orders\TimeLine[]|\Google\Protobuf\Internal\RepeatedField $order_timeline
     *     @type \Lexmodo\V1\Orders\OrdersRuleRequest[]|\Google\Protobuf\Internal\RepeatedField $rules
     *     @type \Lexmodo\V1\Orders\OrdersListing $order_listing
     *     @type \Lexmodo\V1\Orders\OrdersRuleRequest $rule
     *     @type \Lexmodo\V1\Orders\OrderTransactionDetails[]|\Google\Protobuf\Internal\RepeatedField $order_transaction_history
     *     @type \Lexmodo\V1\Payments\PaymentResultDetails $payment_confirmation
     *     @type \Lexmodo\V1\Orders\LabelData $label_data
     *     @type \Lexmodo\V1\Orders\OPC $opc
     *     @type \Lexmodo\V1\Orders\PackingSlip $packing_slip
     *     @type \Lexmodo\V1\Orders\OrdersScript $orders_script
     *     @type string $script_result
     *     @type \Lexmodo\V1\Orders\OrderReports[]|\Google\Protobuf\Internal\RepeatedField $sales_report
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool failure = 2;</code>
     * @return bool
     */
    public function getFailure()
    {
        return $this->failure;
    }

    /**
     * Generated from protobuf field <code>bool failure = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFailure($var)
    {
        GPBUtil::checkBool($var);
        $this->failure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 5;</code>
     * @return \Lexmodo\V1\Orders\Invoice|null
     */
    public function getInvoice()
    {
        return isset($this->invoice) ? $this->invoice : null;
    }

    public function hasInvoice()
    {
        return isset($this->invoice);
    }

    public function clearInvoice()
    {
        unset($this->invoice);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Invoice invoice = 5;</code>
     * @param \Lexmodo\V1\Orders\Invoice $var
     * @return $this
     */
    public function setInvoice($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\Invoice::class);
        $this->invoice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Analytical customer_value = 6;</code>
     * @return \Lexmodo\V1\Orders\Analytical|null
     */
    public function getCustomerValue()
    {
        return isset($this->customer_value) ? $this->customer_value : null;
    }

    public function hasCustomerValue()
    {
        return isset($this->customer_value);
    }

    public function clearCustomerValue()
    {
        unset($this->customer_value);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.Analytical customer_value = 6;</code>
     * @param \Lexmodo\V1\Orders\Analytical $var
     * @return $this
     */
    public function setCustomerValue($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\Analytical::class);
        $this->customer_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.TimeLine order_timeline = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderTimeline()
    {
        return $this->order_timeline;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.TimeLine order_timeline = 7;</code>
     * @param \Lexmodo\V1\Orders\TimeLine[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderTimeline($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Orders\TimeLine::class);
        $this->order_timeline = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrdersRuleRequest rules = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrdersRuleRequest rules = 8;</code>
     * @param \Lexmodo\V1\Orders\OrdersRuleRequest[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Orders\OrdersRuleRequest::class);
        $this->rules = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersListing order_listing = 9;</code>
     * @return \Lexmodo\V1\Orders\OrdersListing|null
     */
    public function getOrderListing()
    {
        return isset($this->order_listing) ? $this->order_listing : null;
    }

    public function hasOrderListing()
    {
        return isset($this->order_listing);
    }

    public function clearOrderListing()
    {
        unset($this->order_listing);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersListing order_listing = 9;</code>
     * @param \Lexmodo\V1\Orders\OrdersListing $var
     * @return $this
     */
    public function setOrderListing($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\OrdersListing::class);
        $this->order_listing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersRuleRequest rule = 10;</code>
     * @return \Lexmodo\V1\Orders\OrdersRuleRequest|null
     */
    public function getRule()
    {
        return isset($this->rule) ? $this->rule : null;
    }

    public function hasRule()
    {
        return isset($this->rule);
    }

    public function clearRule()
    {
        unset($this->rule);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersRuleRequest rule = 10;</code>
     * @param \Lexmodo\V1\Orders\OrdersRuleRequest $var
     * @return $this
     */
    public function setRule($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\OrdersRuleRequest::class);
        $this->rule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrderTransactionDetails order_transaction_history = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderTransactionHistory()
    {
        return $this->order_transaction_history;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrderTransactionDetails order_transaction_history = 11;</code>
     * @param \Lexmodo\V1\Orders\OrderTransactionDetails[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderTransactionHistory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Orders\OrderTransactionDetails::class);
        $this->order_transaction_history = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.PaymentResultDetails payment_confirmation = 12;</code>
     * @return \Lexmodo\V1\Payments\PaymentResultDetails|null
     */
    public function getPaymentConfirmation()
    {
        return isset($this->payment_confirmation) ? $this->payment_confirmation : null;
    }

    public function hasPaymentConfirmation()
    {
        return isset($this->payment_confirmation);
    }

    public function clearPaymentConfirmation()
    {
        unset($this->payment_confirmation);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.payments.PaymentResultDetails payment_confirmation = 12;</code>
     * @param \Lexmodo\V1\Payments\PaymentResultDetails $var
     * @return $this
     */
    public function setPaymentConfirmation($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Payments\PaymentResultDetails::class);
        $this->payment_confirmation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.LabelData label_data = 13;</code>
     * @return \Lexmodo\V1\Orders\LabelData|null
     */
    public function getLabelData()
    {
        return isset($this->label_data) ? $this->label_data : null;
    }

    public function hasLabelData()
    {
        return isset($this->label_data);
    }

    public function clearLabelData()
    {
        unset($this->label_data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.LabelData label_data = 13;</code>
     * @param \Lexmodo\V1\Orders\LabelData $var
     * @return $this
     */
    public function setLabelData($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\LabelData::class);
        $this->label_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OPC opc = 14;</code>
     * @return \Lexmodo\V1\Orders\OPC|null
     */
    public function getOpc()
    {
        return isset($this->opc) ? $this->opc : null;
    }

    public function hasOpc()
    {
        return isset($this->opc);
    }

    public function clearOpc()
    {
        unset($this->opc);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OPC opc = 14;</code>
     * @param \Lexmodo\V1\Orders\OPC $var
     * @return $this
     */
    public function setOpc($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\OPC::class);
        $this->opc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.PackingSlip packing_slip = 15;</code>
     * @return \Lexmodo\V1\Orders\PackingSlip|null
     */
    public function getPackingSlip()
    {
        return isset($this->packing_slip) ? $this->packing_slip : null;
    }

    public function hasPackingSlip()
    {
        return isset($this->packing_slip);
    }

    public function clearPackingSlip()
    {
        unset($this->packing_slip);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.PackingSlip packing_slip = 15;</code>
     * @param \Lexmodo\V1\Orders\PackingSlip $var
     * @return $this
     */
    public function setPackingSlip($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\PackingSlip::class);
        $this->packing_slip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersScript orders_script = 16;</code>
     * @return \Lexmodo\V1\Orders\OrdersScript|null
     */
    public function getOrdersScript()
    {
        return isset($this->orders_script) ? $this->orders_script : null;
    }

    public function hasOrdersScript()
    {
        return isset($this->orders_script);
    }

    public function clearOrdersScript()
    {
        unset($this->orders_script);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.OrdersScript orders_script = 16;</code>
     * @param \Lexmodo\V1\Orders\OrdersScript $var
     * @return $this
     */
    public function setOrdersScript($var)
    {
        GPBUtil::checkMessage($var, \Lexmodo\V1\Orders\OrdersScript::class);
        $this->orders_script = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string script_result = 17;</code>
     * @return string
     */
    public function getScriptResult()
    {
        return $this->script_result;
    }

    /**
     * Generated from protobuf field <code>string script_result = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setScriptResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->script_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrderReports sales_report = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSalesReport()
    {
        return $this->sales_report;
    }

    /**
     * Generated from protobuf field <code>repeated .lexmodo.v1.orders.OrderReports sales_report = 18;</code>
     * @param \Lexmodo\V1\Orders\OrderReports[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSalesReport($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lexmodo\V1\Orders\OrderReports::class);
        $this->sales_report = $arr;

        return $this;
    }

}

