<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

if (false) {
    /**
     * This class is deprecated. Use Lexmodo\V1\Orders\TimeLineAction\ACTION_STATUS instead.
     * @deprecated
     */
    class TimeLineAction_ACTION_STATUS {}
}
class_exists(TimeLineAction\ACTION_STATUS::class);
@trigger_error('Lexmodo\V1\Orders\TimeLineAction_ACTION_STATUS is deprecated and will be removed in the next major release. Use Lexmodo\V1\Orders\TimeLineAction\ACTION_STATUS instead', E_USER_DEPRECATED);

