<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Lexmodo\V1\Orders;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lexmodo.v1.orders.TimeLineAction</code>
 */
class TimeLineAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.TimeLineAction.ACTION_STATUS action_type = 1;</code>
     */
    protected $action_type = 0;
    /**
     * Generated from protobuf field <code>string comment = 2;</code>
     */
    protected $comment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action_type
     *     @type string $comment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.TimeLineAction.ACTION_STATUS action_type = 1;</code>
     * @return int
     */
    public function getActionType()
    {
        return $this->action_type;
    }

    /**
     * Generated from protobuf field <code>.lexmodo.v1.orders.TimeLineAction.ACTION_STATUS action_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setActionType($var)
    {
        GPBUtil::checkEnum($var, \Lexmodo\V1\Orders\TimeLineAction\ACTION_STATUS::class);
        $this->action_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 2;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

}

